import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
const db=new PGlite();
const uid='00000000-0000-4000-8000-000000000001',session='00000000-0000-4000-8000-000000000002',request='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id),not_after timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
for(const name of ['20260925094836_aco_access_foundation.sql','20260925125207_aco_command_transactions.sql'])await db.exec(await readFile(new URL('../../supabase/migrations/'+name,import.meta.url),'utf8'));
await db.query('insert into auth.users values($1)',[uid]);await db.query('insert into auth.sessions values($1,$2,null)',[session,uid]);await db.query("insert into aco_private.identities(user_id,role,enabled) values($1,'admin',true)",[uid]);
async function as(role,fn){await db.exec('begin;set local role '+role);try{const result=await fn();await db.exec('commit');return result}catch(e){await db.exec('rollback');throw e}}
const load=()=>db.query('select public.aco_runtime_load($1,$2,null) value',[uid,session]);
const commit=(revision,requestId=request,hash='a'.repeat(64),rows=[{kind:'clients',id:'one',payload:{id:'one',name:"Robert'); DROP TABLE auth.users;--"}}])=>db.query('select public.aco_runtime_commit($1,$2,$3,$4,$5,$6,$7,$8) value',[uid,session,revision,requestId,hash,JSON.stringify(rows),'[]','test']);
test('browser roles cannot read or invoke the private runtime',async()=>{for(const role of ['anon','authenticated']){await assert.rejects(()=>as(role,load),/permission denied/);await assert.rejects(()=>as(role,()=>commit(0)),/permission denied/);await assert.rejects(()=>as(role,()=>db.query('select * from aco_private.runtime_entities')),/permission denied/)}});
test('atomic commit accepts parameterized data, duplicate is idempotent',async()=>{const result=await as('service_role',()=>commit(0));assert.equal(result.rows[0].value.revision,1);const replay=await as('service_role',()=>commit(0));assert.equal(replay.rows[0].value.replayed,true);assert.equal((await db.query('select count(*)::int n from aco_private.runtime_entities')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from auth.users')).rows[0].n,1)});
test('stale revision and request-id reuse fail without overwriting',async()=>{await assert.rejects(()=>as('service_role',()=>commit(0,'00000000-0000-4000-8000-000000000004')),/Concurrent/);await assert.rejects(()=>as('service_role',()=>commit(1,request,'b'.repeat(64))),/different command/);assert.equal((await as('service_role',load)).rows[0].value.revision,1)});
test('credentials and malformed second record roll back whole command',async()=>{await assert.rejects(()=>as('service_role',()=>commit(1,'00000000-0000-4000-8000-000000000005','c'.repeat(64),[{kind:'clients',id:'two',payload:{id:'two'}},{kind:'accounts',id:'bad',payload:{id:'bad',password:{hash:'secret'}}}])),/Credentials/);assert.equal((await db.query("select count(*)::int n from aco_private.runtime_entities where id='two'")).rows[0].n,0)});
test('disabled identity and expired/revoked session stop service operations',async()=>{await db.query('update aco_private.identities set enabled=false');await assert.rejects(()=>as('service_role',load),/disabled/);await db.query('update aco_private.identities set enabled=true');await db.query("update auth.sessions set not_after=now()-interval '1 second'");await assert.rejects(()=>as('service_role',load),/revoked/);await db.query('delete from auth.sessions');await assert.rejects(()=>as('service_role',load),/revoked/)});

after(()=>db.close());
