import {DialogActions} from './dialog-actions';
import React,{useState} from 'react';
import {Field,useApp} from './context';
import {Input} from './controls';
import {PhotoPicker} from './admin-ui';
import {dateOf} from './domain';
export function ClientProfileEditor({id}:{id:string}){
 const {db,run,open}=useApp(),c=db.clients.find(c=>c.id===id)!;
 const [photo,setPhoto]=useState(c.photo||''),[name,setName]=useState(c.name),[phone,setPhone]=useState(c.phone),[birthDate,setBirthDate]=useState(c.birthDate||''),[answers,setAnswers]=useState(c.answers),[confirmed,setConfirmed]=useState(false);
 const account=db.accounts.find(a=>a.clientId===id);
 return <><div className="modal-title"><h2>Dane klienta</h2><p>{c.name}</p></div><form onSubmit={async e=>{e.preventDefault();if(birthDate!==c.birthDate&&!confirmed)return;if(await run({type:'clientProfile',id,name,phone,birthDate,answers,photo},'Dane klienta zapisane.'))open(null)}}><PhotoPicker value={photo} onChange={setPhoto}/><Field label="Imię i nazwisko"><Input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Telefon"><Input value={phone} onChange={e=>setPhone(e.target.value)}/></Field><Field label="Data urodzenia"><Input required type="date" max={dateOf(new Date(db.now))} value={birthDate} onChange={e=>{setBirthDate(e.target.value);setConfirmed(false)}}/></Field>{birthDate!==c.birthDate&&<label className="alert"><Input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Potwierdzam zmianę daty używanej do aktywacji konta.</label>}{['W czym moglibyśmy Ci pomóc?','Preferowana liczba spotkań w tygodniu','Preferowane godziny współpracy'].map((label,i)=><Field key={label} label={label}><textarea value={answers[i]||''} maxLength={2000} onChange={e=>setAnswers(Array.from({length:Math.max(3,answers.length)},(_,j)=>j===i?e.target.value:answers[j]||''))}/></Field>)}{account&&<section className="inset spaced"><h3>E-mail i login</h3><p>{account.email}</p><button type="button" className="button secondary" onClick={()=>open({type:'adminEmail',id:account.id})}>Zmień e-mail i login</button></section>}<DialogActions><button type="button" className="button secondary" onClick={()=>open(null)}>Anuluj</button><button className="button primary" disabled={birthDate!==c.birthDate&&!confirmed}>Zapisz dane</button></DialogActions></form></>;
}
export function AdminEmailEditor({id}:{id:string}){
 const {db,adminTool,open}=useApp(),account=db.accounts.find(a=>a.id===id)!;
 const [email,setEmail]=useState(account.pendingEmail||account.email),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><div className="modal-title"><h2>Zmień e-mail i login</h2><p>{account.name||db.clients.find(c=>c.id===account.clientId)?.name||db.trainers.find(t=>t.id===account.trainerId)?.name}</p></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await adminTool('adminEmail',{accountId:id,email,confirmation});open(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="Obecny e-mail"><Input value={account.email} readOnly/></Field><Field label="Nowy e-mail do logowania"><Input type="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></Field><div className="alert">Zmiana zadziała od razu, bez potwierdzenia przez użytkownika. Jego dotychczasowe sesje zostaną wylogowane. Przed zmianą potwierdź tożsamość osoby.</div>{account.pendingEmail&&<p className="alert">Dokończ rozpoczętą zmianę na {account.pendingEmail}.</p>}<Field label="Aby zatwierdzić, wpisz ZMIEŃ E-MAIL"><Input value={confirmation} autoComplete="off" onChange={e=>setConfirmation(e.target.value)}/></Field>{error&&<p role="alert" className="alert">{error}</p>}<DialogActions><button type="button" className="button secondary" disabled={busy} onClick={()=>open(null)}>Anuluj</button><button className="button primary" disabled={busy||confirmation!=='ZMIEŃ E-MAIL'||email.trim().toLowerCase()===account.email&&!account.pendingEmail}>{busy?'Zapisywanie…':'Zmień login'}</button></DialogActions></form></>;
}
export function OwnPasswordEditor(){
 const {changePassword,open}=useApp();const [old,setOld]=useState(''),[password,setPassword]=useState(''),[repeat,setRepeat]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <><h2>Zmień hasło</h2><form onSubmit={async e=>{e.preventDefault();setError('');if(password!==repeat){setError('Hasła muszą być takie same.');return}setBusy(true);try{await changePassword(old,password);open(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="Obecne hasło"><Input required type="password" autoComplete="current-password" value={old} onChange={e=>setOld(e.target.value)}/></Field><Field label="Nowe hasło"><Input required type="password" autoComplete="new-password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></Field><Field label="Powtórz nowe hasło"><Input required type="password" autoComplete="new-password" minLength={12} value={repeat} onChange={e=>setRepeat(e.target.value)}/></Field>{error&&<p role="alert" className="alert">{error}</p>}<button className="button primary" disabled={busy}>Zapisz hasło</button></form></>;
}
