import {test} from 'node:test';
import assert from 'node:assert/strict';
import {publicAction,type AccountServices} from '../server/accounts';
import {encodeRelational} from '../server/relational-store';
import {initialDatabase} from './auth';
const req=new Request('https://example.test',{headers:{'x-forwarded-for':'192.0.2.1'}});
async function fixture(){const db=await initialDatabase();db.now='2026-10-07T12:00:00.000Z';db.accounts=[];db.clients=[];db.sessions=[];db.trainers=[{id:'t',name:'Coach',rate:50,days:[0,1,2,3,4,5,6],hours:[8,9,10],products:['personal']}];for(let i=1;i<=3;i++){db.accounts.push({id:'user'+i,email:`client${i}@example.test`,role:'client',clientId:'c'+i});db.clients.push({id:'c'+i,name:'Client '+i,email:`client${i}@example.test`,phone:'',birthDate:'1990-01-01',trainerId:'t',service:'personal',intensity:1,active:false,invited:true,prescribed:true,answers:[]})}return db}
test('three clients sharing an IP can both verify and activate without consuming one combined five-attempt quota',async()=>{const db=await fixture(),counts=new Map<string,number>();let completed=0;const svc:AccountServices={hash:async s=>s,credentialProof:async s=>s,auth:async()=>({}),rpc:async(name,args)=>{if(name==='aco_rate_limit'){const key=String(args.p_key),n=(counts.get(key)||0)+1;counts.set(key,n);return n<=Number(args.p_max) as any}if(name==='aco_relational_public_load')return {revision:1,now:db.now,rows:encodeRelational(db)} as any;if(name==='aco_claim_activation_retry')return {fresh:true,canWrite:true,userId:'user'+String(args.p_email)[6],requestId:args.p_request} as any;if(name==='aco_complete_activation'){completed++;return true as any}throw Error(name)}};for(let i=1;i<=3;i++)for(const password of [undefined,'TestOnlyPassword123'])await publicAction({action:'activation',email:`client${i}@example.test`,birthDate:'1990-01-01',password,requestId:'r'+i},req,svc);assert.equal(completed,3)});
test('activation recovers from rejected Auth write using the same credential proof',async()=>{const db=await fixture();let claimed=false,writes=0,saved=false,completed=false;const svc:AccountServices={hash:async s=>s,credentialProof:async s=>s,rpc:async(name,args)=>{if(name==='aco_rate_limit')return true as any;if(name==='aco_relational_public_load')return {revision:1,now:db.now,rows:encodeRelational(db)} as any;if(name==='aco_claim_activation_retry'){const fresh=!claimed;claimed=true;return {fresh,canWrite:true,userId:'user1',requestId:'first'} as any}if(name==='aco_release_activation_attempt')return null as any;if(name==='aco_complete_activation'){completed=true;return true as any}throw Error(name)},auth:async(path,method)=>{if(method==='PUT'){writes++;if(writes===1)throw Object.assign(Error('Rejected before write'),{status:422});saved=true;return {}}if(saved)return {user:{id:'user1'}};throw Error('No password yet')}};const body={action:'activation',email:'client1@example.test',birthDate:'1990-01-01',password:'TestOnlyPassword123',requestId:'first'};await assert.rejects(publicAction(body,req,svc));assert.equal(completed,false);assert.deepEqual(await publicAction(body,req,svc),{ok:true});assert.equal(writes,2);assert.equal(completed,true)});
test('registration retry recovers its own Auth identity after database failure without a second user',async()=>{const db=await fixture();db.accounts=[];db.clients=[];let user:string|null=null,create=0,commits=0;const svc:AccountServices={hash:async s=>s,credentialProof:async s=>s,rpc:async(name)=>{if(name==='aco_rate_limit')return true as any;if(name==='aco_registration_receipt')return false as any;if(name==='aco_registration_identity')return user as any;if(name==='aco_relational_public_load')return {revision:1,now:db.now,rows:encodeRelational(db)} as any;if(name==='aco_relational_commit'){commits++;if(commits===1)throw Error('Temporary failure');return true as any}throw Error(name)},auth:async(path,method,body:any)=>{assert.equal(body.app_metadata.aco_registration.requestId,'registration');create++;user='created-user';return {id:user}}};const body={action:'register',requestId:'registration',command:{type:'register',name:'Test',email:'new@example.test',phone:'500100200',birthDate:'1990-01-01',trainerId:'t',date:'2026-10-09',hour:8,answers:[]}};await assert.rejects(publicAction(body,req,svc));assert.deepEqual(await publicAction(body,req,svc),{ok:true});assert.equal(create,1);assert.equal(commits,2)});
