import {PhotoCrop} from './photo-crop';
import React,{useState,useRef,useEffect} from 'react';
import {Camera,Upload,Check,Bell,X,ChevronRight,Coins,Clock,UserRound} from 'lucide-react';
import {useApp,Field,Avatar} from './context';
import {accountOf,accountName,notifications} from './management';
import {money} from './domain';
export function PhotoPicker({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const input=useRef<HTMLInputElement>(null),alert=useRef<HTMLDivElement>(null);
 const [error,setError]=useState(''),[crop,setCrop]=useState('');
 useEffect(()=>{if(error){alert.current?.focus({preventScroll:true});alert.current?.scrollIntoView({block:'nearest',behavior:'smooth'})}},[error]);
 return <>
  <div className="photo-picker"><div className="photo-preview">{value?<img src={value} alt="Zdjęcie profilowe"/>:<Camera size={25}/>}</div>
   <div><strong>Zdjęcie profilowe</strong><p>JPG, PNG lub WebP · do 2 MB</p><div className="photo-actions">
    <button type="button" className="button secondary" onClick={()=>input.current?.click()}><Upload size={15}/>{value?'Zmień zdjęcie':'Dodaj zdjęcie'}</button>
    {value&&<><button type="button" className="text-button" onClick={()=>setCrop(value)}>Kadruj</button><button type="button" className="text-button" onClick={()=>onChange('')}>Usuń</button></>}
   </div>
   <input ref={input} className="visually-hidden" aria-label="Wybierz zdjęcie profilowe" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{
    const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(!f)return;
    setCrop('');setError('');
    if(f.size>2*1024*1024){const size=(Math.ceil(f.size/1024/1024*10)/10).toLocaleString('pl-PL');setError(`Plik jest za duży (${size} MB). Maksymalny rozmiar zdjęcia to 2 MB. Wybierz mniejszy plik.`);return}
    if(!['image/png','image/jpeg','image/webp'].includes(f.type)){setError('Nieobsługiwany format zdjęcia. Wybierz plik JPG, PNG lub WebP.');return}
    const reader=new FileReader();reader.onload=()=>setCrop(String(reader.result));reader.onerror=()=>setError('Nie udało się odczytać zdjęcia. Spróbuj wybrać plik ponownie.');reader.readAsDataURL(f);
   }}/></div>
  </div>
  {error&&<div ref={alert} tabIndex={-1} role="alert" aria-atomic="true" className="photo-upload-error"><strong>Nie dodano zdjęcia</strong><p>{error}</p></div>}
  {crop&&<PhotoCrop key={crop} src={crop} onCancel={()=>setCrop('')} onSave={s=>{onChange(s);setCrop('')}}/>}
 </>;
}
export function AmountInput({name,value,onChange,label='Kwota'}:{name?:string;value:number;onChange:(n:number)=>void;label?:string}){const [draft,setDraft]=useState(''),[editing,setEditing]=useState(false);const format=(n:number)=>Number.isFinite(n)?n.toLocaleString('pl-PL',{minimumFractionDigits:2,maximumFractionDigits:2}):'';return <div className="amount-input"><input aria-label={label} name={name} inputMode="decimal" required value={editing?draft:format(value)} onFocus={()=>{setDraft(Number.isFinite(value)?String(value).replace('.',','):'');setEditing(true)}} onChange={e=>{const text=e.target.value;setDraft(text);const normalized=text.replace(/\s/g,'').replace(',','.');onChange(normalized.trim()!==''&&/^\d+(\.\d{0,2})?$/.test(normalized)?Number(normalized):NaN)}} onBlur={()=>setEditing(false)}/><span>zł</span></div>}
export function ProfileSettings(){const {db,actor,run,open}=useApp();const me=accountOf(db,actor)!;const person=actor.role==='trainer'?db.trainers.find(t=>t.id===actor.trainerId):actor.role==='client'?db.clients.find(c=>c.id===actor.clientId):me;const [name,setName]=useState(person?.name||me.name||accountName(db,me)),[email,setEmail]=useState(me.email),[phone,setPhone]=useState(person?.phone||''),[photo,setPhoto]=useState(person?.photo||'');return <><div className="modal-title"><h2>Mój profil</h2><p>Dane kontaktowe i zdjęcie konta.</p></div><form onSubmit={async e=>{e.preventDefault();if(await run({type:'updateProfile',name,email,phone,photo},'Profil został zapisany.'))open(null)}}><PhotoPicker value={photo} onChange={setPhoto}/><Field label="Imię i nazwisko"><input required value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="E-mail do logowania"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Telefon"><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></Field><div className="form-actions"><button type="button" className="button secondary" onClick={()=>open(null)}>Anuluj</button><button className="button primary">Zapisz profil</button></div></form></>}
export function NotificationBell(){const {db,actor,openNotice}=useApp();const [shown,setShown]=useState(false);const wrap=useRef<HTMLDivElement>(null);const me=accountOf(db,actor);const incoming=(db.letters||[]).filter(m=>m.to===me?.id&&!m.read).map(m=>({id:'letter:'+m.id,title:'Wiadomość od '+m.fromName,body:m.subject+' - '+m.body,at:m.at}));const list=[...incoming,...notifications(db,actor)].slice().sort((a,b)=>Number(b.id.startsWith('letter:'))-Number(a.id.startsWith('letter:'))||b.at.localeCompare(a.at)).slice(0,6);const unread=incoming.length+notifications(db,actor).filter(n=>!(db.noticeReads?.[me?.id||'']||[]).includes(n.id)).length;useEffect(()=>{const close=(e:MouseEvent)=>{if(!wrap.current?.contains(e.target as Node))setShown(false)};const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setShown(false)};document.addEventListener('mousedown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',key)}},[]);return <div className="notification-anchor" ref={wrap}><button className="icon-btn" aria-label="Powiadomienia" aria-expanded={shown} aria-controls="notification-popover" onClick={()=>setShown(!shown)}><Bell size={20}/>{unread>0&&<i/>}</button>{shown&&<section className="notification-popover" id="notification-popover" aria-label="Najnowsze powiadomienia"><header><h3>Powiadomienia</h3><button className="icon-btn" aria-label="Zamknij powiadomienia" onClick={()=>setShown(false)}><X size={16}/></button></header>{list.length?list.map(n=><button className="notification-preview" key={n.id} onClick={async()=>{setShown(false);openNotice(n.id)}}><span className={!(db.noticeReads?.[me?.id||'']||[]).includes(n.id)?'notification-dot unread':'notification-dot'}/><span><strong>{n.title}</strong><small>{n.body}</small></span><ChevronRight size={14}/></button>):<div className="notification-empty"><Bell size={24}/><p>Brak nowych powiadomień.</p></div>}</section>}</div>}
export {SettingsPage} from './settings-page';
