import {dateOf} from './domain';
import {AdminWorkSummary} from './work-summary';
import {Pencil,Trash2,CalendarDays,Clock,KeyRound} from 'lucide-react';
import React,{useState} from 'react';
import {useApp,Avatar,Empty,Field} from './context';
import {notifications,accountOf,accountName,recipients} from './management';
import {money,serviceName,dayAdd,at,trainerHours} from './domain';
export function AdminDashboard(){const {db,go,open}=useApp();const today=dateOf(new Date(db.now)),month=today.slice(0,7);const trainers=db.trainers.filter(t=>!t.deleted),pending=db.clients.filter(c=>!c.active),unpaid=db.holds.filter(h=>h.status!=='paid');return <><div className="page-heading"><h1>Podsumowanie firmy</h1></div><div className="stats-grid">{[['Aktywni klienci',db.clients.filter(c=>c.active).length],['Trenerzy',trainers.length],['Konta do aktywacji',pending.length],['Sprzedaż w miesiącu',money(db.sales.filter(s=>s.date.startsWith(month)).reduce((n,s)=>n+s.amount,0))]].map(([label,value])=><section className="stat" key={label}><span>{label}</span><strong>{value}</strong></section>)}</div><div className="settings-layout"><section className="card pad"><h2>Wymaga działania</h2><button className="quick-action" onClick={()=>go('Klienci')}>Klienci bez aktywnego konta <strong>{pending.length}</strong></button><button className="quick-action" onClick={()=>go('Sprzedaż')}>Nieopłacone rezerwacje <strong>{unpaid.length}</strong></button><button className="quick-action" onClick={()=>go('Grafik')}>Nierozliczone wizyty <strong>{db.sessions.filter(s=>s.status==='scheduled'&&at(s.date,s.hour)<new Date(db.now)).length}</strong></button></section><section className="card pad"><h2>Obciążenie zespołu - 7 dni</h2>{trainers.map(t=><div className="audit-row" key={t.id}><strong>{t.name}</strong><span>{db.clients.filter(c=>c.trainerId===t.id).length} klientów · {db.sessions.filter(s=>s.trainerId===t.id&&s.kind==='training'&&s.status==='scheduled'&&s.date>=today&&s.date<dayAdd(today,7)).length} treningów · {db.sessions.filter(s=>s.trainerId===t.id&&s.kind==='consultation'&&s.status==='scheduled'&&s.date>=today&&s.date<dayAdd(today,7)).length} konsultacji</span></div>)}{!trainers.length&&<p>Nie dodano trenerów.</p>}</section></div><AdminWorkSummary/><section className="card pad spaced"><h2>Ostatnie działania</h2>{db.audit.slice(0,8).map(a=><div className="audit-row" key={a.id}><span>{a.text}</span><small>{new Date(a.at).toLocaleString('pl-PL')}</small></div>)}</section></>}
export function TrainersPage(){const {db,open,run}=useApp();return <><div className="page-heading"><h1>Trenerzy</h1><button className="button primary" onClick={()=>open({type:'newTrainer'})}>+ Dodaj trenera</button></div><section className="card table-wrap trainers-table"><table><thead><tr><th>Trener</th><th>Kontakt</th><th>Produkty / stawki</th><th>Klienci</th><th>Działania</th></tr></thead><tbody>{db.trainers.filter(t=>!t.deleted).map(t=>{const count=db.clients.filter(c=>c.trainerId===t.id).length;return <tr key={t.id}><td><div className="trainer-inline">{t.photo?<img className="profile-photo" src={t.photo} alt={t.name}/>:<Avatar name={t.name}/>}<div className="trainer-name"><strong>{t.name}</strong>{(!t.days.length||!t.hours.length)&&<small>Dostępność nieustawiona</small>}</div></div></td><td>{db.accounts.find(a=>a.trainerId===t.id)?.email}<small>{t.phone}</small></td><td>{(t.products||['personal','physio']).map(p=><span className="trainer-product" key={p}>{serviceName(p)} <span>{money(t.productRates?.[p as 'personal'|'physio']??t.rate)} / h</span></span>)}</td><td><button className="text-button" onClick={()=>open({type:'trainerClients',id:t.id})}>{count} klientów</button></td><td><div className="session-actions"><button className="trainer-action" title="Ustaw dostępność" onClick={()=>open({type:'availability',id:t.id})}><CalendarDays size={16}/>Grafik</button><button className="trainer-action" title="Dodatkowe godziny pracy" onClick={()=>open({type:'companyHours',id:t.id})}><Clock size={16}/>Godziny</button><button className="trainer-action icon-only" aria-label={"Wyzeruj hasło - "+t.name} title="Wyzeruj hasło" onClick={()=>open({type:'resetPassword',id:db.accounts.find(a=>a.trainerId===t.id)!.id})}><KeyRound size={16}/></button><button className="icon-btn" aria-label={"Edytuj - "+t.name} onClick={()=>open({type:'editTrainer',id:t.id})}><Pencil size={16}/></button><button className="icon-btn danger" aria-label={"Usuń - "+t.name} disabled={count>0} title={count?'Najpierw przenieś klientów do innego trenera':'Usuń trenera'} onClick={()=>run({type:'deleteTrainer',id:t.id})}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table>{!db.trainers.some(t=>!t.deleted)&&<Empty title="Brak trenerów" body="Dodaj trenera, aby udostępnić grafik."/>}</section></>}
export function TrainerClients({id}:{id:string}){const {db,run}=useApp();const [client,setClient]=useState('');const t=db.trainers.find(t=>t.id===id)!;return <><h2>Klienci - {t.name}</h2><p>Usunięcie klienta z tej listy wymaga przypisania nowego prowadzącego.</p>{db.clients.filter(c=>c.trainerId===id).map(c=><form key={c.id} className="inset spaced" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);run({type:'transferClient',clientId:c.id,trainerId:String(data.get('trainer'))})}}><h3>{c.name}</h3><Field label="Nowy trener prowadzący"><select name="trainer" required defaultValue=""><option value="" disabled>Wybierz trenera</option>{db.trainers.filter(x=>x.id!==id&&!x.deleted).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><button className="button secondary">Usuń z listy i przenieś</button></form>)}<section className="inset spaced"><h3>Dodaj istniejącego klienta</h3><Field label="Klient"><select value={client} onChange={e=>setClient(e.target.value)}><option value="">Wybierz klienta</option>{db.clients.filter(c=>c.trainerId!==id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><button className="button primary" disabled={!client} onClick={()=>run({type:'transferClient',clientId:client,trainerId:id})}>Przypisz do trenera</button></section></>}
export {MessagesPage} from './messages-page';
export {AvailabilityPage} from './availability-page';
