import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDatabase} from './auth';
import {execute,currentPackage,dayAdd,dayIndex,saleDay,formatDateTime,canSee} from './domain';
import {renewalAllowed} from './business';
import {applyCommand} from '../server/commands';
import {projectState} from '../server/access';
import {validPhone,validPesel} from './validation';
async function fixture(){const db=await initialDatabase();db.now='2026-10-08T10:00:00.000Z';db.accounts=[{id:'admin',role:'admin',email:'a@example.test'},{id:'client',role:'client',clientId:'c1',email:'c@example.test'}];db.clients=[{id:'c1',name:'Client',email:'c@example.test',phone:'500600700',trainerId:'t1',active:true,invited:true,prescribed:true,service:'personal',intensity:1,answers:[]}];db.trainers=[{id:'t1',name:'Trainer',products:['personal'],rate:80,days:[0,1,2,3,4,5,6],hours:[10]}];return db}
const actor={role:'admin' as const,trainerId:'',clientId:''};
const pack=(id:string,start:string,validUntil:string)=>({id,clientId:'c1',start,validUntil,cycleEnd:dayAdd(start,28),protectionUntil:dayAdd(validUntil,7),count:4,service:'personal',intensity:1,price:1599,slots:[]});
test('ACO-20: shortened expiry opens renewal and permits an earlier replacement cycle',async()=>{let db=await fixture();db.packages=[pack('old','2026-10-01','2026-10-08')];assert.equal(renewalAllowed(db,'c1'),true);const start='2026-10-10';db=execute(db,actor,{type:'hold',clientId:'c1',start,slots:[{day:dayIndex(start),hour:10}],dates:[0,1,2,3].map(w=>({date:dayAdd(start,w*7),hour:10}))}) as typeof db;assert.equal(db.holds[0].start,start)});
test('ACO-21: a newer expired cycle does not revive unbooked entries from an older valid package',async()=>{const db=await fixture();db.packages=[pack('old','2026-09-01','2026-11-01'),pack('new','2026-10-01','2026-10-07')];assert.equal(currentPackage(db,'c1')?.id,'new');assert.throws(()=>execute(db,actor,{type:'makeup',packageId:'old',date:'2026-10-10',hour:10}),/ważnego wejścia/)});
test('ACO-01/12: reported payment keeps its authoritative discount after coupon visibility or validity changes',async()=>{let db=await fixture();db.promotions=[{id:'promo',kind:'code',value:'AUDIT',percent:100,maxUses:2,used:0,expires:'2026-11-01',active:true}];const start='2026-10-10';db=execute(db,actor,{type:'hold',clientId:'c1',start,slots:[{day:dayIndex(start),hour:10}],dates:[0,1,2,3].map(w=>({date:dayAdd(start,w*7),hour:10}))}) as typeof db;const id=db.holds[0].id;db=applyCommand(db,'client',{type:'requestPayment',id,code:'AUDIT'},db.now);const clientView=projectState(db,'client');assert.equal(clientView.promotions?.length,0);assert.equal(clientView.holds[0].paymentRequest?.pricing?.total,0);assert.equal(clientView.holds[0].price,0);db.promotions![0].active=false;db=applyCommand(db,'client',{type:'requestPayment',id,code:'INVALID'},db.now);db=applyCommand(db,'admin',{type:'payHold',id},db.now);assert.equal(db.sales[0].amount,0);assert.equal(db.packages[0].discountPercent,100);assert.equal(db.promotions![0].used,1)});
test('repeat freezing extends validity by seven days each time, thawing does not extend it',async()=>{let db=await fixture();db.packages=[pack('p','2026-10-01','2026-11-01')];for(const expected of ['2026-11-08','2026-11-15']){db=execute(db,actor,{type:'freeze',packageId:'p'}) as typeof db;assert.equal(db.packages[0].validUntil,expected);db=execute(db,actor,{type:'freeze',packageId:'p'}) as typeof db;assert.equal(db.packages[0].validUntil,expected)}});
test('ACO-08/09: phone and PESEL reject malformed values and accept formatted legitimate values',()=>{assert.equal(validPhone('abc'),false);assert.equal(validPhone('123'),false);assert.equal(validPhone('+48 500 600 700'),true);assert.equal(validPesel('12345678901'),false);assert.equal(validPesel('44051401458'),true)});
test('ACO-14/19: transaction day and payment deadline use Warsaw in summer and winter',()=>{assert.equal(saleDay('2026-10-31T23:23:00Z'),'2026-11-01');assert.equal(saleDay('2026-09-30T22:23:00Z'),'2026-10-01');assert.match(formatDateTime('2026-10-08T10:00:00Z'),/12:00/);assert.match(formatDateTime('2026-11-08T10:00:00Z'),/11:00/)});
test('ACO-02: absent client after live access expiry is inaccessible without throwing',async()=>{assert.equal(canSee(await fixture(),actor,undefined),false)});
