import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed,dayAdd,currentPackage,nextPackage,at,endAt} from './domain';
import {applyCommand} from '../server/commands';
import {renewalAllowed} from './business';
import {csv} from './csv';
import type {Database} from './auth';
function fixture(){const d=seed() as Database;d.now='2026-10-01T06:00:00.000Z';d.sessions=[];d.packages=[];d.holds=[];d.blocks=[];d.messages=[];d.accounts=[{id:'admin',role:'admin',email:'admin@aco.test'},...d.clients.map(c=>({id:'user-'+c.id,role:'client' as const,clientId:c.id,email:c.email}))];d.trainers.forEach(t=>{t.products=['personal','physio'];t.days=[0,1,2,3,4,5,6];t.hours=[8,9,10,11,12,13,14,15,16,17,18,19,20]});d.clients.forEach(c=>{c.active=true;c.prescribed=true;c.intensity=1});return d}
function reserve(){const d=fixture();return applyCommand(d,'user-c1',{type:'hold',clientId:'c1',start:'2026-10-05',slots:[{day:0,hour:8}],dates:[0,1,2,3].map(w=>({date:dayAdd('2026-10-05',w*7),hour:8}))},d.now)}
test('payment review preserves reservations beyond checkout and retries do not extend or duplicate requests',()=>{let d=reserve();const id=d.holds[0].id;d=applyCommand(d,'user-c1',{type:'requestPayment',id},'2026-10-01T06:05:00.000Z');const expiry=d.holds[0].expires,messages=d.messages.length;d=applyCommand(d,'user-c1',{type:'requestPayment',id},'2026-10-01T06:20:00.000Z');assert.equal(d.holds[0].expires,expiry);assert.equal(d.messages.length,messages);d=applyCommand(d,'admin',{type:'payHold',id},'2026-10-01T07:00:00.000Z');assert.equal(d.packages.length,1);assert.equal(d.holds[0].status,'paid')});
test('future package is separate from current and prevents another future purchase',()=>{const d=fixture();const base={clientId:'c1',count:4,slots:[],intensity:1,service:'personal' as const,price:600,protectionUntil:'2026-12-15'};d.now='2026-10-26T06:00:00.000Z';d.packages=[{...base,id:'current',start:'2026-10-05',cycleEnd:'2026-11-02',validUntil:'2026-11-16'},{...base,id:'future',start:'2026-11-02',cycleEnd:'2026-11-30',validUntil:'2026-12-14'}];assert.equal(currentPackage(d,'c1')?.id,'current');assert.equal(nextPackage(d,'c1')?.id,'future');assert.equal(renewalAllowed(d,'c1'),false);d.now='2026-11-02T06:00:00.000Z';assert.equal(currentPackage(d,'c1')?.id,'future')});
test('substitution requires the client product and follows the last moved session',()=>{let d=fixture();d.sessions=[{id:'s',clientId:'c1',trainerId:'t1',date:'2026-10-05',hour:8,kind:'training',status:'scheduled',publicNote:'',privateNote:'',comments:[],packageId:'p'}];d.packages=[{id:'p',clientId:'c1',count:4,start:'2026-10-01',cycleEnd:'2026-11-01',validUntil:'2026-12-01',protectionUntil:'2026-12-02',slots:[],intensity:1,service:'personal',price:600}];d.trainers[1].products=['physio'];assert.throws(()=>applyCommand(d,'admin',{type:'substitute',clientId:'c1',trainerId:'t2',from:'2026-10-05',to:'2026-10-06'},d.now),/produkt/);d.trainers[1].products=['personal'];d=applyCommand(d,'admin',{type:'substitute',clientId:'c1',trainerId:'t2',from:'2026-10-05',to:'2026-10-06'},d.now);d=applyCommand(d,'admin',{type:'reschedule',id:'s',date:'2026-10-20',hour:8},d.now);assert.equal(Date.parse(d.substitutions[0].until),+endAt(d.sessions[0])+48*3600000)});
test('freeze extends recurring protection with validity',()=>{let d=fixture();d.packages=[{id:'p',clientId:'c1',count:4,start:'2026-10-01',cycleEnd:'2026-10-29',validUntil:'2026-11-12',protectionUntil:'2026-11-13',slots:[],intensity:1,service:'personal',price:600}];d=applyCommand(d,'admin',{type:'freeze',packageId:'p'},d.now);assert.equal(d.packages[0].protectionUntil,dayAdd(d.packages[0].validUntil,1))});
test('CSV quotes delimiters and line breaks and neutralizes spreadsheet formulas',()=>{assert.equal(csv([['=1+1','A;B','He said "yes"','two\nlines']]),'\ufeff"\'=1+1";"A;B";"He said ""yes""";"two\nlines"');for(const x of ['+CMD','-CMD','@SUM(A1)','\t=1'])assert.ok(csv([[x]]).startsWith('\ufeff"\''))});
