import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDatabase,setupLocalAdmin,authenticate,addTrainer,actorFor,guest,registerAccount,activateAccount,TrainerInput} from './auth';
import {dayAdd,execute} from './domain';
export const trainerInput:TrainerInput={name:'Anna Testowa',email:'anna@example.test',products:['personal','physio'],productRates:{personal:100,physio:130},days:[0,1,2,3,4,5,6],hours:[8,9,10,11,12,13,14,15,16,17,18],password:'TrainerTest!2026',phone:'',pesel:'',student:false,address:'',taxOffice:'',photo:''};
test('Lokalny administrator wymaga własnego hasła i konfiguracji tylko raz',async()=>{const empty=await initialDatabase();assert.equal(empty.clients.length,0);assert.equal(empty.accounts[0].password,undefined);await assert.rejects(authenticate(empty,'administrator@aco.pl','not-configured'));const password=crypto.randomUUID();const db=await setupLocalAdmin(empty,password);assert.equal((await authenticate(db,' ADMINISTRATOR@ACO.PL ',password)).role,'admin');await assert.rejects(setupLocalAdmin(db,crypto.randomUUID()));await assert.rejects(authenticate(db,'administrator@aco.pl','wrong-password'));assert.ok(!JSON.stringify(db).includes(password))});
test('Trener: unikalny email, produkty, stawki i edycja bez zmiany hasła',async()=>{const db=await initialDatabase(),admin=actorFor(db.accounts[0]);await assert.rejects(addTrainer(db,guest,trainerInput));const next=await addTrainer(db,admin,trainerInput);const account=await authenticate(next,trainerInput.email,trainerInput.password);assert.equal(account.trainerId,next.trainers[0].id);assert.equal(next.trainers[0].productRates?.physio,130);await assert.rejects(addTrainer(next,admin,{...trainerInput,email:'ANNA@example.test'}));await assert.rejects(addTrainer(db,admin,{...trainerInput,products:[]}));await assert.rejects(addTrainer(db,admin,{...trainerInput,password:'short'}));const edited=await addTrainer(next,admin,{...trainerInput,id:account.trainerId,name:'Anna Nowa',password:''});assert.equal((await authenticate(edited,trainerInput.email,trainerInput.password)).id,account.id)});
test('Aktywacja wymaga emaila, daty urodzenia, zatwierdzenia i działa raz',async()=>{let db=await initialDatabase();const admin=actorFor(db.accounts[0]);db=await addTrainer(db,admin,trainerInput);db=execute(db,admin,{type:'availability',trainerId:db.trainers[0].id,days:trainerInput.days,hours:trainerInput.hours}) as typeof db;const cmd={type:'register' as const,name:'Jan Testowy',email:'jan@example.test',phone:'500000000',birthDate:'1990-03-12',trainerId:db.trainers[0].id,date:dayAdd(db.now.slice(0,10),1),hour:10,answers:['B','C']};await assert.rejects(registerAccount(db,{...cmd,birthDate:'1990-02-31'}));await assert.rejects(registerAccount(db,{...cmd,birthDate:''}));db=(await registerAccount(db,cmd)).db;const client=db.clients[0];assert.equal(db.accounts.at(-1)?.token,undefined);await assert.rejects(activateAccount(db,cmd.email,cmd.birthDate,'ClientTest!2026'));db=execute(db,admin,{type:'prescribe',id:client.id,service:'personal',intensity:2}) as typeof db;assert.throws(()=>execute(db,actorFor(db.accounts[1]),{type:'activate',id:client.id}));db=execute(db,admin,{type:'activate',id:client.id}) as typeof db;await assert.rejects(activateAccount(db,cmd.email,'1990-03-13','ClientTest!2026'));await assert.rejects(activateAccount(db,'invalid@example.test',cmd.birthDate,'ClientTest!2026'));db=await activateAccount(db,' JAN@EXAMPLE.TEST ',cmd.birthDate,'ClientTest!2026');assert.equal((await authenticate(db,cmd.email,'ClientTest!2026')).clientId,client.id);await assert.rejects(activateAccount(db,cmd.email,cmd.birthDate,'OtherPass!2026'))});
test('Hasło tymczasowe, własne hasło i reset wymagają ponownej zmiany',async()=>{const {changeOwnPassword,resetAccountPassword}=await import('./auth');let db=await initialDatabase();const admin=actorFor(db.accounts[0]);db=await addTrainer(db,admin,trainerInput);const a=db.accounts[1];assert.equal(a.mustChangePassword,true);await assert.rejects(addTrainer(db,admin,{...trainerInput,id:a.trainerId,password:'OtherPassword!2026'}));await assert.rejects(changeOwnPassword(db,a.id,trainerInput.password,trainerInput.password));db=await changeOwnPassword(db,a.id,trainerInput.password,'PrivatePassword!2026');assert.equal(db.accounts[1].mustChangePassword,false);await assert.rejects(resetAccountPassword(db,actorFor(a),a.id));const reset=await resetAccountPassword(db,admin,a.id);assert.equal(reset.db.accounts[1].mustChangePassword,true);await assert.rejects(authenticate(reset.db,a.email,'PrivatePassword!2026'));assert.equal((await authenticate(reset.db,a.email,reset.temporary)).id,a.id)});
