import {Brand} from './brand';
import React,{useState} from 'react';
import {Field} from './context';
import {RegistrationPage} from './registration';
export {TrainerWizard} from './trainer-wizard';
export function AuthScreen({login,activate}:{login:(e:string,p:string)=>Promise<void>;activate:(e:string,d:string,password?:string)=>Promise<void>}){
 const [view,setView]=useState('login'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <div className="auth-shell"><header className="auth-header"><Brand/><nav className="filter-tabs">{[['login','Logowanie'],['register','Rejestracja'],['activate','Aktywacja konta']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>{setView(key);setError('');setMessage('')}}>{label}</button>)}</nav></header>{view==='register'?<main className="auth-registration"><RegistrationPage/></main>:view==='activate'?<DirectActivation activate={activate} done={()=>{setView('login');setMessage('Konto jest aktywne. Zaloguj się swoim nowym hasłem.')}}/>:<section className="auth-form card" style={{margin:'60px auto'}}><h2>Logowanie</h2><form onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const d=new FormData(e.currentTarget);try{await login(String(d.get('email')),String(d.get('password')))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="E-mail"><input name="email" type="email" required autoComplete="username"/></Field><Field label="Hasło"><input name="password" type="password" required autoComplete="current-password"/></Field>{message&&<p className="hint spaced" role="status">{message}</p>}{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Proszę czekać…':'Zaloguj się'}</button></form></section>}</div>
}
function DirectActivation({activate,done}:{activate:(email:string,birthDate:string,password?:string)=>Promise<void>;done:()=>void}){
 const [email,setEmail]=useState(''),[birthDate,setBirthDate]=useState(''),[verified,setVerified]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <section className="auth-form card" style={{margin:'60px auto'}}><h2>{verified?'Ustaw hasło':'Aktywacja konta'}</h2><form key={String(verified)} onSubmit={async e=>{e.preventDefault();setError('');const d=new FormData(e.currentTarget);setBusy(true);try{if(!verified){await activate(email,birthDate);setVerified(true)}else{if(d.get('password')!==d.get('confirm'))throw Error('Hasła muszą być takie same.');await activate(email,birthDate,String(d.get('password')));done()}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{verified?<><p className="hint spaced">{email}</p><Field label="Hasło"><input name="password" type="password" minLength={12} maxLength={200} required autoComplete="new-password"/></Field><Field label="Powtórz hasło"><input name="confirm" type="password" minLength={12} maxLength={200} required autoComplete="new-password"/></Field><p className="hint spaced">Minimum 12 znaków.</p></>:<><Field label="E-mail"><input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Data urodzenia"><input type="date" required autoComplete="bday" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></Field></>}{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Proszę czekać…':verified?'Ustaw hasło i aktywuj konto':'Dalej'}</button>{verified&&<button type="button" className="text-button spaced" disabled={busy} onClick={()=>{setVerified(false);setError('')}}>Wróć do danych konta</button>}</form></section>
}
export function LocalSetup({save}:{save:(password:string)=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="auth-shell"><header className="auth-header"><Brand/></header><section className="auth-form card" style={{margin:'60px auto'}}><h2>Konfiguracja administratora</h2><p className="hint spaced">Dane tej wersji są zapisywane wyłącznie w tej przeglądarce. Ustaw hasło do lokalnego konta administrator@aco.pl.</p><form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setError('');setBusy(true);try{if(data.get('password')!==data.get('confirm'))throw Error('Hasła muszą być takie same.');await save(String(data.get('password')))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="Hasło"><input name="password" type="password" required minLength={10} autoComplete="new-password"/></Field><Field label="Powtórz hasło"><input name="confirm" type="password" required minLength={10} autoComplete="new-password"/></Field>{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Zapisywanie…':'Zapisz hasło'}</button></form></section></div>}
