import {Brand} from './brand';
import React,{useState} from 'react';
import {Field} from './context';
import {RegistrationPage} from './pages';
export {TrainerWizard} from './trainer-wizard';
export function AuthScreen({login,activate}:{login:(e:string,p:string)=>Promise<void>;activate:(e:string,d:string)=>Promise<void>}){const [view,setView]=useState('login'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);return <div className="auth-shell"><header className="auth-header"><Brand/><nav className="filter-tabs">{[['login','Logowanie'],['register','Rejestracja'],['activate','Aktywacja konta']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>{setView(key);setError('');setMessage('')}}>{label}</button>)}</nav></header>{view==='register'?<main className="auth-registration"><RegistrationPage/></main>:<section className="auth-form card" style={{margin:'60px auto'}}><h2>{view==='activate'?'Aktywacja konta':'Logowanie'}</h2><form key={view} onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const d=new FormData(e.currentTarget);try{if(view==='activate'){await activate(String(d.get('email')),String(d.get('birthDate')));setMessage('Jeśli dane są zgodne i konsultacja została zatwierdzona, otrzymasz e-mail z linkiem do ustawienia hasła.')}else await login(String(d.get('email')),String(d.get('password')))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="E-mail"><input name="email" type="email" required autoComplete="username"/></Field>{view==='activate'?<Field label="Data urodzenia"><input name="birthDate" type="date" required autoComplete="bday"/></Field>:<Field label="Hasło"><input name="password" type="password" required autoComplete="current-password"/></Field>}{message&&<p className="hint spaced" role="status">{message}</p>}{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Proszę czekać…':view==='activate'?'Wyślij link aktywacyjny':'Zaloguj się'}</button></form></section>}</div>}
export function OnlineActivation({save}:{save:(password:string)=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="auth-shell"><header className="auth-header"><Brand/></header><section className="auth-form card" style={{margin:'60px auto'}}><h2>Ustaw hasło</h2><form onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{if(d.get('password')!==d.get('confirm'))throw Error('Hasła muszą być takie same.');await save(String(d.get('password')))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}}><Field label="Hasło"><input name="password" type="password" minLength={12} required autoComplete="new-password"/></Field><Field label="Powtórz hasło"><input name="confirm" type="password" minLength={12} required autoComplete="new-password"/></Field>{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Zapisywanie…':'Zapisz hasło i aktywuj konto'}</button></form></section></div>}

export function LocalSetup({save}:{save:(password:string)=>Promise<void>}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="auth-shell"><header className="auth-header"><Brand/></header><section className="auth-form card" style={{margin:'60px auto'}}><h2>Konfiguracja administratora</h2><p className="hint spaced">Dane tej wersji są zapisywane wyłącznie w tej przeglądarce. Ustaw hasło do lokalnego konta administrator@aco.pl.</p><form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setError('');setBusy(true);try{if(data.get('password')!==data.get('confirm'))throw Error('Hasła muszą być takie same.');await save(String(data.get('password')))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><Field label="Hasło"><input name="password" type="password" required minLength={10} autoComplete="new-password"/></Field><Field label="Powtórz hasło"><input name="confirm" type="password" required minLength={10} autoComplete="new-password"/></Field>{error&&<p className="alert" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Zapisywanie…':'Zapisz hasło'}</button></form></section></div>}
