import {State,Actor,Command,execute,uid} from './domain';
export interface Account {mustChangePassword?:boolean;name?:string;phone?:string;photo?:string;id:string;email:string;role:'admin'|'trainer'|'client';trainerId?:string;clientId?:string;password?:{salt:string;hash:string};token?:string;disabled?:boolean}
export interface Letter {id:string;from:string;to:string;fromName:string;toName:string;subject:string;body:string;at:string;read:boolean}
export type Database=State&{accounts:Account[];letters?:Letter[];noticeReads?:Record<string,string[]>};
export const guest:Actor={role:'guest',trainerId:'',clientId:''};
export function actorFor(a:Account):Actor{return {role:a.role,trainerId:a.trainerId||'',clientId:a.clientId||''}}
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
export async function digest(value:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))}
export async function passwordHash(value:string,salt:string=uid()){if(value.length<10)throw Error('Hasło musi mieć co najmniej 10 znaków.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']);return {salt,hash:hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:210000},key,256))}}
export async function initialDatabase():Promise<Database>{return {version:1,now:new Date().toISOString(),clients:[],trainers:[],sessions:[],packages:[],holds:[],messages:[],sales:[],substitutions:[],audit:[],blocks:[],settings:{personal:180,physio:220,consultation:250,cancelHours:24},accounts:[{id:uid(),email:'administrator@aco.pl',role:'admin'}]}}
export async function authenticate(db:Database,email:string,password:string){const a=db.accounts.find(a=>a.email===email.trim().toLowerCase());if(a?.disabled||!a?.password||password.length<10||(await passwordHash(password,a.password.salt)).hash!==a.password.hash)throw Error('Nieprawidłowy e-mail lub hasło.');if(a.role==='client'&&!db.clients.find(c=>c.id===a.clientId)?.active)throw Error('Konto oczekuje na aktywację.');return a}
function unique(db:Database,email:string){if(!/^\S+@\S+\.\S+$/.test(email))throw Error('Podaj poprawny e-mail.');if(db.accounts.some(a=>a.email===email)||db.clients.some(c=>c.email===email))throw Error('Konto z tym adresem e-mail już istnieje.')}
export function validBirthDate(value:string,now:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&value>='1900-01-01'&&value<=now.slice(0,10)&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value}
export async function registerAccount(db:Database,cmd:Extract<Command,{type:'register'}>){unique(db,cmd.email.trim().toLowerCase());if(!validBirthDate(cmd.birthDate||'',db.now))throw Error('Podaj poprawną datę urodzenia.');const next=execute(db,guest,cmd) as Database;const client=next.clients.at(-1)!;next.accounts.push({id:uid(),email:client.email,role:'client',clientId:client.id});return {db:next}}
export async function activateAccount(db:Database,email:string,birthDate:string,password:string){const a=db.accounts.find(a=>a.email===email.trim().toLowerCase()&&a.role==='client'&&!a.disabled);const c=db.clients.find(c=>c.id===a?.clientId);if(!a||!c?.birthDate||c.birthDate!==birthDate)throw Error('E-mail lub data urodzenia są nieprawidłowe.');if(a.password||c.active)throw Error('Konto jest już aktywne. Przejdź do logowania.');if(!c.prescribed||!c.invited)throw Error('Konto oczekuje na zatwierdzenie po konsultacji.');const credential=await passwordHash(password);const next=execute(db,actorFor(a),{type:'acceptInvite',id:c.id}) as Database;const account=next.accounts.find(x=>x.id===a.id)!;account.password=credential;delete account.token;return next}
export interface TrainerInput {id?:string;name:string;email:string;products:('personal'|'physio')[];productRates:{personal:number;physio:number};days:number[];hours:number[];password:string;phone:string;pesel:string;student:boolean;address:string;taxOffice:string;photo:string}
export async function addTrainer(db:Database,actor:Actor,input:TrainerInput){if(actor.role!=='admin')throw Error('Tylko administrator może zarządzać trenerami.');const email=input.email.trim().toLowerCase();const old=input.id?db.trainers.find(t=>t.id===input.id&&!t.deleted):undefined;if(old&&input.password)throw Error('Użyj opcji wyzerowania hasła.');if(input.id&&!old)throw Error('Nie znaleziono trenera.');const existing=db.accounts.find(a=>a.trainerId===old?.id&&a.role==='trainer');if(existing?.email!==email)unique(db,email);if(!input.name.trim()||!input.products.length||input.products.some(p=>!['personal','physio'].includes(p)||!Number.isFinite(input.productRates[p])||input.productRates[p]<=0)||input.days.some(d=>!Number.isInteger(d)||d<0||d>6)||input.hours.some(h=>!Number.isInteger(h)||h<0||h>23))throw Error('Uzupełnij dane, produkty, stawki i dostępność.');if(input.pesel&&!/^\d{11}$/.test(input.pesel))throw Error('PESEL musi zawierać 11 cyfr.');if(old&&db.clients.some(c=>c.trainerId===old.id&&c.prescribed&&!input.products.includes(c.service)))throw Error('Nie można wyłączyć produktu przypisanego podopiecznym.');if(!old&&!input.password)throw Error('Ustaw hasło trenera.');const password=input.password?await passwordHash(input.password):undefined;const next=structuredClone(db),id=old?.id||uid();const {password:ignored,email:ignoredEmail,days:ignoredDays,hours:ignoredHours,...fields}=input;const history=old?.productRateHistory||old?.rates?.map(r=>({from:r.from,personal:r.rate,physio:r.rate}))||[{from:'1900-01-01',...(old?.productRates||{personal:old?.rate||0,physio:old?.rate||0})}];const trainer={...old,...fields,id,days:old?.days||[],hours:old?.hours||[],rate:input.productRates[input.products[0]],productRateHistory:[...history.filter(r=>r.from!==db.now.slice(0,10)),{from:db.now.slice(0,10),...input.productRates}]};delete trainer.specialty;if(old)next.trainers[next.trainers.findIndex(t=>t.id===id)]=trainer;else next.trainers.push(trainer);if(existing){const a=next.accounts.find(a=>a.id===existing.id)!;a.email=email;if(password)a.password=password}else next.accounts.push({id:uid(),email,role:'trainer',trainerId:id,password,mustChangePassword:true});next.audit.unshift({id:uid(),at:db.now,text:`${old?'Zmieniono':'Dodano'} trenera: ${input.name}`});return next}

export function migrateDatabase(source:Database):Database {const db=structuredClone(source);db.letters??=[];db.noticeReads??={};for(const a of db.accounts)delete a.token;for(const t of db.trainers){t.products??=['personal','physio'];t.productRates??={personal:t.rate,physio:t.rate};t.productRateHistory??=t.rates?.map(r=>({from:r.from,personal:r.rate,physio:r.rate}))||[{from:'1900-01-01',...t.productRates}];delete t.specialty}for(const m of db.messages){const c=db.clients.find(c=>c.id===m.clientId);if(c&&!m.body.includes(c.name))m.body=c.name+' · '+m.body;m.body=m.body.replace(/za pomocą swojego kodu aktywacyjnego/g,'podając e-mail i datę urodzenia').replace(/za pomocą kodu aktywacyjnego/g,'podając e-mail i datę urodzenia')}return db}

export async function changeOwnPassword(db:Database,accountId:string,old:string,next:string){const a=db.accounts.find(a=>a.id===accountId&&!a.disabled);if(!a)throw Error('Brak konta.');await authenticate(db,a.email,old);if(old===next)throw Error('Nowe hasło musi różnić się od tymczasowego.');const result=structuredClone(db),target=result.accounts.find(x=>x.id===accountId)!;target.password=await passwordHash(next);target.mustChangePassword=false;return result}
export async function resetAccountPassword(db:Database,actor:Actor,id:string){if(actor.role!=='admin')throw Error('Tylko administrator może zerować hasła.');const result=structuredClone(db),a=result.accounts.find(a=>a.id===id&&!a.disabled);if(!a||!a.password)throw Error('Konto nie zostało jeszcze aktywowane.');const temporary='ACO!'+crypto.randomUUID().replaceAll('-','').slice(0,16);a.password=await passwordHash(temporary);a.mustChangePassword=true;return {db:result,temporary}}

// This bootstrap is exclusive to the browser-local database, never a server API.
export function needsLocalSetup(db:Database){return db.accounts.length===1&&db.accounts[0].role==='admin'&&!db.accounts[0].password&&!db.accounts[0].disabled}
export async function setupLocalAdmin(db:Database,password:string){if(!needsLocalSetup(db))throw Error('Konto administratora zostało już skonfigurowane.');const next=structuredClone(db);next.accounts[0].password=await passwordHash(password);return next}
