import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed,at,bookingLeadAllowed,rules} from './domain';
import {applyCommand} from '../server/commands';
import type {Database} from './auth';
function fixture(){const d=seed() as Database;d.now=at('2026-10-05',12).toISOString();d.sessions=[];d.packages=[];d.holds=[];d.blocks=[];d.accounts=[{id:'admin',email:'admin@test.pl',role:'admin'},{id:'trainer',email:'trainer@test.pl',role:'trainer',trainerId:'t1'},{id:'client',email:'client@test.pl',role:'client',clientId:'c1'}];d.trainers[0].days=[0,1,2,3,4,5,6];d.trainers[0].hours=[8,9,10,11,12,13,14,15,16,17,18];d.clients.find(c=>c.id==='c1')!.intensity=2;d.packages=[{id:'p',clientId:'c1',start:'2026-10-05',cycleEnd:'2026-11-02',validUntil:'2026-11-16',protectionUntil:'2026-11-17',intensity:2,count:8,slots:[],service:'personal',price:1200}];return d}
test('separate lead times default to 24h and use exact instants across DST',()=>{const d=fixture();assert.equal(rules(d).trainingLeadHours,24);assert.equal(bookingLeadAllowed(d,'training','2026-10-06',11),false);assert.equal(bookingLeadAllowed(d,'training','2026-10-06',12),true);d.now=new Date(Date.parse(d.now)+1).toISOString();assert.equal(bookingLeadAllowed(d,'training','2026-10-06',12),false);d.settings.rules={...rules(d),consultationLeadHours:48,trainingLeadHours:0};assert.equal(bookingLeadAllowed(d,'consultation','2026-10-06',13),false);assert.equal(bookingLeadAllowed(d,'training','2026-10-05',13),true);d.now=at('2026-10-24',12).toISOString();d.settings.rules.trainingLeadHours=24;assert.equal(bookingLeadAllowed(d,'training','2026-10-25',11),true)});
test('staff may reschedule inside 24h while clients cannot; UI flags are valid commands',()=>{const d=fixture();d.sessions=[{id:'s',clientId:'c1',trainerId:'t1',packageId:'p',date:'2026-10-05',hour:14,kind:'training',status:'scheduled',publicNote:'',privateNote:'',comments:[]}];const cmd={type:'reschedule',id:'s',date:'2026-10-05',hour:16,ignoreLimits:false,holidayOverride:false};for(const actor of ['admin','trainer']){const next=applyCommand(d,actor,cmd,d.now);assert.equal(next.sessions[0].hour,16)}assert.throws(()=>applyCommand(d,'client',cmd,d.now),/wyprzedzeniem|mniej niż/);assert.equal(d.sessions[0].hour,14)});
test('staff may book makeup today; clients must satisfy target lead time',()=>{const d=fixture(),cmd={type:'makeup',packageId:'p',date:'2026-10-05',hour:16,ignoreLimits:false,holidayOverride:false};for(const actor of ['admin','trainer'])assert.equal(applyCommand(d,actor,cmd,d.now).sessions.length,1);assert.throws(()=>applyCommand(d,'client',cmd,d.now),/wyprzedzeniem/);assert.equal(applyCommand(d,'client',{...cmd,date:'2026-10-06',hour:12},d.now).sessions.length,1)});
test('client cannot bypass consultation lead time at registration',()=>{const d=fixture();assert.throws(()=>applyCommand(d,'admin',{type:'register',name:'Test',email:'new@example.test',phone:'123',birthDate:'1990-01-01',trainerId:'t1',date:'2026-10-06',hour:11,answers:[]},d.now),/wyprzedzeniem|rejestrac|operac/i)});
