import {ResponsiveTable} from './responsive-table';
import {ProductColorPicker} from './product-color-picker';
import {Select,Input} from './controls';
import {dateOf} from './domain';
import React,{useState} from 'react';
import {Activity,Check,Plus,Trash2,Mail,Ticket,Pencil} from 'lucide-react';
import {useApp,Field} from './context';
import {productCopy,productColor} from './business';
import {money,serviceName,packagePrice,rules,trainingCount,labelDate,dayAdd} from './domain';
import {AmountInput} from './admin-ui';
export function ProductDescriptions(){return <><div className="page-heading"><div><h1>Produkty</h1><p>Kliknij nazwę, opis lub punkt na karcie, aby go edytować.</p></div></div><div className="inline-product-grid">{['personal','physio'].map(service=><ProductEditor key={service} service={service}/>)}</div></>}
function InlineText({value,onChange,label,heading=false}:{value:string;onChange:(s:string)=>void;label:string;heading?:boolean}){const [editing,setEditing]=useState(false);return editing?<textarea autoFocus aria-label={label} className={'inline-input '+(heading?'inline-title':'')} rows={heading?2:3} value={value} onChange={e=>onChange(e.target.value)} onBlur={()=>setEditing(false)} onKeyDown={e=>{if(e.key==='Escape'||e.key==='Enter'&&!e.shiftKey){e.preventDefault();setEditing(false)}}}/>:<button type="button" className={'inline-copy '+(heading?'inline-title':'')} aria-label={'Edytuj: '+label} onClick={()=>setEditing(true)}><span>{value||label}</span><Pencil size={14}/></button>}
function ProductEditor({service}:{service:string}){const {db,run}=useApp();const [copy,setCopy]=useState(()=>productCopy(db,service)),[intensity,setIntensity]=useState(1);const dirty=JSON.stringify(copy)!==JSON.stringify(productCopy(db,service));return <section className="card product-card inline-product"><div className="preview-toolbar"><span>{serviceName(service)}</span><Select aria-label={'Intensywność - '+serviceName(service)} value={intensity} onChange={e=>setIntensity(Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n} × w tygodniu</option>)}</Select></div><div className="product-symbol" style={{color:copy.color||productColor(db,service),background:(copy.color||productColor(db,service))+'18'}}><Activity size={32}/></div><ProductColorPicker value={copy.color||productColor(db,service)} onChange={color=>setCopy({...copy,color})}/><InlineText heading label="Nazwa produktu" value={copy.name} onChange={name=>setCopy({...copy,name})}/><InlineText label="Krótki opis" value={copy.subtitle} onChange={subtitle=>setCopy({...copy,subtitle})}/><div className="product-frequency">{intensity}<span>{intensity===1?'raz':'razy'} w tygodniu</span><strong>{trainingCount(intensity*rules(db).cycleWeeks)} / {rules(db).cycleWeeks} tygodnie</strong></div><ul className="product-features editable-features">{copy.bullets.map((text,i)=><li key={i}><Check size={16}/><InlineText label={'Punkt '+(i+1)} value={text} onChange={value=>setCopy({...copy,bullets:copy.bullets.map((b,j)=>j===i?value:b)})}/><button className="icon-btn" aria-label={'Usuń punkt '+(i+1)} onClick={()=>setCopy({...copy,bullets:copy.bullets.filter((_,j)=>j!==i)})}><Trash2 size={14}/></button></li>)}</ul><button className="text-button add-bullet" onClick={()=>setCopy({...copy,bullets:[...copy.bullets,'']})}><Plus size={16}/>Dodaj punkt</button><div className="product-price"><strong>{money(packagePrice(db,service,intensity))}</strong><small>Cena z cennika · {money(packagePrice(db,service,intensity)/(intensity*rules(db).cycleWeeks))} za trening</small></div><div className="editor-save"><span>{dirty?'Niezapisane zmiany':'Zapisano'}</span><button className="button primary" disabled={!dirty||!copy.name.trim()||!copy.subtitle.trim()||!!copy.color&&!/^#[0-9a-fA-F]{6}$/.test(copy.color)} onClick={async()=>{const clean={...copy,bullets:copy.bullets.map(b=>b.trim()).filter(Boolean)};if(await run({type:'productCopy',service,copy:clean},'Opis produktu zapisany.'))setCopy(clean)}}>Zapisz opis</button></div></section>}
export function Promotions(){const {db,run}=useApp();const active=(db.promotions||[]).filter(p=>p.active&&(p.kind==='email'||p.used<p.maxUses&&p.expires>=dateOf(new Date(db.now)))).slice().reverse();return <><div className="page-heading"><div><h1>Promocje</h1><p>Rabaty dla konkretnych klientów i kody do wykorzystania przy zakupie.</p></div></div><div className="promotion-panels"><PromotionPanel kind="email"/><PromotionPanel kind="code"/></div><section className="card active-promotions"><header><h2>Aktywne promocje <span className="number-badge">{active.length}</span></h2><p>Rabaty nie łączą się - klient otrzymuje korzystniejszy.</p></header>{active.length?<div className="table-wrap"><ResponsiveTable><table><thead><tr><th>Odbiorca / kod</th><th>Typ</th><th>Rabat</th><th>Wykorzystanie</th><th>Ważność</th><th/></tr></thead><tbody>{active.map(p=><tr key={p.id}><td><strong>{p.value}</strong></td><td>{p.kind==='email'?'Rabat imienny':'Kod promocyjny'}</td><td><span className="discount-chip">−{p.percent}%</span></td><td>{p.kind==='code'?`${p.used} / ${p.maxUses}`:'Bez limitu'}</td><td>{p.kind==='code'?labelDate(p.expires):'Bezterminowo'}</td><td><button className="trainer-action" onClick={()=>run({type:'disablePromotion',id:p.id})}>Wyłącz</button></td></tr>)}</tbody></table></ResponsiveTable></div>:<div className="promotion-empty">Brak aktywnych promocji. Dodaj rabat lub kod powyżej.</div>}</section></>}
function PromotionPanel({kind}:{kind:'email'|'code'}){const {db,run}=useApp(),email=kind==='email';const [value,setValue]=useState(''),[percent,setPercent]=useState(10),[maxUses,setMaxUses]=useState(10),[expires,setExpires]=useState(dayAdd(dateOf(new Date(db.now)),30));const all=(db.promotions||[]).filter(p=>p.kind===kind),active=(p:typeof all[number])=>p.active&&(email||p.used<p.maxUses&&p.expires>=dateOf(new Date(db.now)));return <section className="card promotion-panel"><header><span className="promotion-icon">{email?<Mail size={22}/>:<Ticket size={22}/>}</span><div><h2>{email?'Rabaty imienne':'Kody promocyjne'}</h2><p>{email?'Niższa cena widoczna od razu w sklepie.':'Klient wpisuje kod podczas płatności.'}</p></div><span className="number-badge">{all.filter(active).length}</span></header><form className="promotion-form" onSubmit={async e=>{e.preventDefault();if(await run({type:'promotion',promotion:{kind,value,percent,maxUses,expires,active:true}},'Promocja dodana.'))setValue('')}}><div className="promotion-primary-fields"><Field label={email?'E-mail klienta':'Kod promocyjny'}><Input placeholder={email?'np. anna@firma.pl':'np. WITAJ20'} required type={email?'email':'text'} value={value} onChange={e=>setValue(email?e.target.value:e.target.value.toUpperCase())}/></Field><Field label="Rabat"><div className="percent-input"><Input aria-label={email?'Rabat imienny (%)':'Rabat kodu (%)'} required type="number" min="1" max="100" value={percent} onChange={e=>setPercent(Number(e.target.value))}/><span>%</span></div></Field></div>{!email&&<div className="form-grid"><Field label="Limit użyć"><Input required type="number" min="1" step="1" value={maxUses} onChange={e=>setMaxUses(Number(e.target.value))}/></Field><Field label="Ważny do"><Input required type="date" min={dateOf(new Date(db.now))} value={expires} onChange={e=>setExpires(e.target.value)}/></Field></div>}<button className="button primary"><Plus size={16}/>{email?'Dodaj rabat':'Utwórz kod'}</button></form></section>}
export {CompanyHours} from './company-hours';
