import {test} from 'node:test';
import assert from 'node:assert/strict';
import {seed,execute,Actor,at,dayAdd,rules} from './domain';
import {quote,renewalAllowed,productCopy} from './business';
import {workSummary} from './work-summary';
const admin:Actor={role:'admin',trainerId:'t1',clientId:''},trainer:Actor={...admin,role:'trainer'};
function fresh(){let db=seed();db=execute(db,trainer,{type:'prescribe',id:'c9',service:'personal',intensity:2});return db}
const holdCommand={type:'hold' as const,clientId:'c9',start:'2026-10-20',slots:[{day:1,hour:16},{day:3,hour:16}],dates:Array.from({length:4},(_,i)=>[{date:dayAdd('2026-10-20',i*7),hour:16},{date:dayAdd('2026-10-22',i*7),hour:16}]).flat()};
test('Jeden trening dziennie: wzorzec i wyjątki',()=>{const db=fresh();assert.throws(()=>execute(db,trainer,{...holdCommand,slots:[{day:1,hour:16},{day:1,hour:17}]}),/jeden/);const dates=structuredClone(holdCommand.dates);dates[1]={date:dates[0].date,hour:17};assert.throws(()=>execute(db,trainer,{...holdCommand,dates}),/jeden trening dziennie/)});
test('Nieobecność na konsultacji od 30 minut, trening dopiero po końcu',()=>{const db=seed(),s=db.sessions.find(s=>s.id==='consult1')!;s.status='scheduled';db.now=new Date(+at(s.date,s.hour)+29*60000).toISOString();assert.throws(()=>execute(db,trainer,{type:'outcome',id:s.id,status:'no_show'}),/30 minut/);db.now=new Date(+at(s.date,s.hour)+30*60000).toISOString();assert.equal(execute(db,trainer,{type:'outcome',id:s.id,status:'no_show'}).sessions.find(x=>x.id===s.id)!.status,'no_show')});
test('Promocje: korzystniejszy rabat, limit użyć, ważność i zapis ceny',()=>{let db=fresh();db=execute(db,admin,{type:'promotion',promotion:{kind:'email',value:' JULIA@PRZYKLAD.PL ',percent:10,maxUses:1,expires:'',active:true}});db=execute(db,admin,{type:'promotion',promotion:{kind:'code',value:'START',percent:20,maxUses:1,expires:'2026-10-19',active:true}});assert.equal(quote(db,'c9','personal',2).percent,10);assert.equal(quote(db,'c9','personal',2,'start').percent,20);db=execute(db,trainer,holdCommand);db=execute(db,admin,{type:'payHold',id:db.holds[0].id,code:'START'});assert.equal(db.packages.at(-1)!.price,960);assert.equal(db.packages.at(-1)!.basePrice,1200);assert.equal(db.promotions![1].used,1);assert.throws(()=>quote(db,'c9','personal',2,'START'),/wykorzystany/);assert.throws(()=>execute(db,admin,{type:'payHold',id:db.holds[0].id,code:'START'}),/opłacony/);assert.equal(db.promotions![1].used,1);const expired=fresh();expired.promotions=[{id:'p',kind:'code',value:'OLD',percent:20,maxUses:1,used:0,expires:'2026-10-18',active:true}];assert.throws(()=>quote(expired,'c9','personal',2,'OLD'),/wygasł/)});
test('Kolejny pakiet dostępny dokładnie siedem dni przed końcem cyklu',()=>{const db=seed(),p=db.packages[0];db.now=dayAdd(p.cycleEnd,-8)+'T10:00:00Z';assert.equal(renewalAllowed(db,p.clientId),false);db.now=dayAdd(p.cycleEnd,-7)+'T10:00:00Z';assert.equal(renewalAllowed(db,p.clientId),true);db.settings.rules={...rules(db),renewalDays:3};assert.equal(renewalAllowed(db,p.clientId),false)});
test('Dodatkowe godziny nie tworzą sesji, są oddzielne i uwzględnione w prognozie',()=>{let db=seed();const count=db.sessions.length,old=workSummary(db,'t1');assert.throws(()=>execute(db,trainer,{type:'extraHours',trainerId:'t1',month:'2026-10',hours:2,rate:75,description:'Spotkanie zespołu'}));db=execute(db,admin,{type:'extraHours',trainerId:'t1',month:'2026-10',hours:2,rate:75,description:'Spotkanie zespołu'});const next=workSummary(db,'t1');assert.equal(db.sessions.length,count);assert.equal(next.earned,old.earned+150);assert.equal(next.forecast,old.forecast+150);assert.equal(next.rows[0].earned,old.rows[0].earned);assert.equal(next.rows[1].earned,old.rows[1].earned)});
test('Opisy kart modyfikuje wyłącznie administrator',()=>{const db=seed(),command={type:'productCopy' as const,service:'personal',copy:{name:'Nowy plan',subtitle:'Opis',bullets:['Punkt A','Punkt B']}};assert.throws(()=>execute(db,trainer,command));assert.equal(productCopy(execute(db,admin,command),'personal').name,'Nowy plan')});
