import {dateOf} from './domain';
import {Actor,State,uid,packagePrice,currentPackage,dayAdd,rules} from './domain';
export interface ProductCopy {name:string;subtitle:string;bullets:string[]}
export interface Promotion {id:string;kind:'email'|'code';value:string;percent:number;maxUses:number;used:number;expires:string;active:boolean}
export interface ExtraHours {id:string;trainerId:string;month:string;hours:number;rate:number;amount:number;description:string}
export type BusinessCommand={type:'productCopy';service:string;copy:ProductCopy}|{type:'promotion';promotion:Omit<Promotion,'id'|'used'>}|{type:'disablePromotion';id:string}|{type:'extraHours';trainerId:string;month:string;hours:number;rate:number;description:string};
export const productCopy=(db:State,s:string):ProductCopy=>db.productCopies?.[s]||{name:s==='physio'?'Powrót do zdrowia':'Trening personalny',subtitle:'Pakiet treningów indywidualnych. Stałe godziny i wsparcie trenera.',bullets:['60 minut tylko dla Ciebie','Stałe godziny w grafiku','Dziennik i komentarze trenera']};
export function quote(db:State,clientId:string,service:string,intensity:number,code=''){const c=db.clients.find(c=>c.id===clientId);const base=packagePrice(db,service,intensity);const promos=(db.promotions||[]).filter(p=>p.active);const email=promos.filter(p=>p.kind==='email'&&p.value===c?.email.toLowerCase()).sort((a,b)=>b.percent-a.percent)[0];let coupon:Promotion|undefined;if(code.trim()){coupon=promos.find(p=>p.kind==='code'&&p.value===code.trim().toUpperCase());if(!coupon||coupon.used>=coupon.maxUses||coupon.expires<dateOf(new Date(db.now)))throw Error('Kod jest nieprawidłowy, wygasł lub został wykorzystany.')}const chosen=coupon&&coupon.percent>(email?.percent||0)?coupon:email;const percent=chosen?.percent||0;return {base,percent,total:Math.round(base*(100-percent))/100,promotionId:chosen?.id,code:chosen?.kind==='code'?chosen.value:undefined}}
export function renewalAllowed(db:State,id:string){const p=currentPackage(db,id);return !p||dateOf(new Date(db.now))>=dayAdd(p.cycleEnd,-rules(db).renewalDays)}
export function business(db:State,a:Actor,cmd:BusinessCommand){if(a.role!=='admin')throw Error('Ta operacja jest dostępna tylko administratorowi.');switch(cmd.type){case 'productCopy':if(!['personal','physio'].includes(cmd.service)||!cmd.copy.name.trim()||!cmd.copy.subtitle.trim())throw Error('Uzupełnij nazwę i podtytuł.');(db.productCopies??={})[cmd.service]={name:cmd.copy.name.trim(),subtitle:cmd.copy.subtitle.trim(),bullets:cmd.copy.bullets.map(s=>s.trim()).filter(Boolean)};break;case 'promotion':{const p=cmd.promotion,value=p.kind==='email'?p.value.trim().toLowerCase():p.value.trim().toUpperCase();if(!value||(p.kind==='email'&&!/^\S+@\S+\.\S+$/.test(value))||!Number.isFinite(p.percent)||p.percent<=0||p.percent>100)throw Error('Podaj poprawny e-mail lub kod oraz rabat od 1 do 100%.');if(p.kind==='code'&&(!Number.isInteger(p.maxUses)||p.maxUses<1||!/^\d{4}-\d{2}-\d{2}$/.test(p.expires)||p.expires<dateOf(new Date(db.now))))throw Error('Podaj liczbę użyć i przyszłą datę ważności.');if((db.promotions||[]).some(x=>x.active&&x.kind===p.kind&&x.value===value))throw Error('Aktywna promocja o tej wartości już istnieje.');(db.promotions??=[]).push({...p,id:uid(),value,used:0});break}case 'disablePromotion':{const p=db.promotions?.find(p=>p.id===cmd.id);if(p)p.active=false;break}case 'extraHours':if(!db.trainers.some(t=>t.id===cmd.trainerId&&!t.deleted)||!/^\d{4}-\d{2}$/.test(cmd.month)||!Number.isFinite(cmd.hours)||cmd.hours<=0||!Number.isFinite(cmd.rate)||cmd.rate<=0||!cmd.description.trim())throw Error('Wybierz trenera, miesiąc, liczbę godzin, stawkę i opis.');(db.extraHours??=[]).push({...cmd,id:uid(),amount:Math.round(cmd.hours*cmd.rate*100)/100});break}db.audit.unshift({id:uid(),at:db.now,text:cmd.type==='extraHours'?'Dodano pozatreningowy czas pracy':cmd.type==='productCopy'?'Zmieniono opis karty produktu':'Zmieniono promocje'});return db}
