import {dateOf} from './domain';
import {Actor,State,uid,packagePrice,currentPackage,dayAdd,rules} from './domain';
export interface ProductCopy {color?:string;name:string;subtitle:string;bullets:string[]}
export interface Promotion {id:string;kind:'email'|'code';value:string;percent:number;maxUses:number;used:number;expires:string;active:boolean}
export interface HoursValues {hours:number;rate:number;amount:number;description:string}
export interface ExtraHours extends HoursValues {id:string;trainerId:string;month:string;settledAt?:string;corrections?:{at:string;reason:string;before:HoursValues;after:HoursValues}[]}
export type BusinessCommand={type:'editExtraHours';id:string;hours:number;rate:number;description:string}|{type:'deleteExtraHours';id:string}|{type:'settleExtraHours';id:string}|{type:'correctExtraHours';id:string;hours:number;rate:number;description:string;reason:string}|{type:'productCopy';service:string;copy:ProductCopy}|{type:'promotion';promotion:Omit<Promotion,'id'|'used'>}|{type:'disablePromotion';id:string}|{type:'extraHours';trainerId:string;month:string;hours:number;rate:number;description:string};
export const productColor=(db:State,s:string)=>db.productCopies?.[s]?.color||(s==='physio'?'#317E77':'#CF513C');
export const productCopy=(db:State,s:string):ProductCopy=>db.productCopies?.[s]||{name:s==='physio'?'Powrót do zdrowia':'Trening personalny',subtitle:'Pakiet treningów indywidualnych. Stałe godziny i wsparcie trenera.',bullets:['60 minut tylko dla Ciebie','Stałe godziny w grafiku','Dziennik i komentarze trenera']};
export function quote(db:State,clientId:string,service:string,intensity:number,code='',baseOverride?:number){const c=db.clients.find(c=>c.id===clientId);const base=baseOverride??(c?.individualPlan?.status==='approved'?c.individualPlan.price:packagePrice(db,service,intensity));const promos=(db.promotions||[]).filter(p=>p.active);const email=promos.filter(p=>p.kind==='email'&&p.value===c?.email.toLowerCase()).sort((a,b)=>b.percent-a.percent)[0];let coupon:Promotion|undefined;if(code.trim()){coupon=promos.find(p=>p.kind==='code'&&p.value===code.trim().toUpperCase());if(!coupon||coupon.used>=coupon.maxUses||coupon.expires<dateOf(new Date(db.now)))throw Error('Kod jest nieprawidłowy, wygasł lub został wykorzystany.')}const chosen=coupon&&coupon.percent>(email?.percent||0)?coupon:email;const percent=chosen?.percent||0;return {base,percent,total:Math.round(base*(100-percent))/100,promotionId:chosen?.id,code:chosen?.kind==='code'?chosen.value:undefined}}
export function renewalAllowed(db:State,id:string){const p=currentPackage(db,id);return !p||dateOf(new Date(db.now))>=dayAdd(p.cycleEnd,-rules(db).renewalDays)}
export function business(db:State,a:Actor,cmd:BusinessCommand){if(a.role!=='admin')throw Error('Ta operacja jest dostępna tylko administratorowi.');switch(cmd.type){
 case 'editExtraHours':case 'deleteExtraHours':case 'settleExtraHours':case 'correctExtraHours':{
 const h=db.extraHours?.find(h=>h.id===cmd.id);if(!h)throw Error('Nie znaleziono dodatkowych godzin.');
 if(cmd.type==='deleteExtraHours'){if(h.settledAt)throw Error('Rozliczonych godzin nie można usunąć. Dodaj korektę.');db.extraHours=db.extraHours!.filter(x=>x.id!==h.id)}
 else if(cmd.type==='settleExtraHours'){if(h.settledAt)throw Error('Te godziny są już rozliczone.');h.settledAt=db.now}
 else {if(cmd.type==='editExtraHours'&&h.settledAt)throw Error('Rozliczone godziny wymagają korekty z uzasadnieniem.');if(cmd.type==='correctExtraHours'&&(!h.settledAt||!cmd.reason.trim()))throw Error('Podaj powód korekty rozliczonych godzin.');if(!Number.isFinite(cmd.hours)||cmd.hours<(cmd.type==='correctExtraHours'?0:.01)||cmd.hours>744||!Number.isFinite(cmd.rate)||cmd.rate<=0||!cmd.description.trim())throw Error('Sprawdź godziny, stawkę i opis.');const after={hours:cmd.hours,rate:cmd.rate,amount:Math.round(cmd.hours*cmd.rate*100)/100,description:cmd.description.trim()};if(cmd.type==='correctExtraHours')(h.corrections??=[]).push({at:db.now,reason:cmd.reason.trim(),before:{hours:h.hours,rate:h.rate,amount:h.amount,description:h.description},after});Object.assign(h,after)}
 db.audit.unshift({id:uid(),at:db.now,text:({editExtraHours:'Edytowano',deleteExtraHours:'Usunięto nierozliczone',settleExtraHours:'Oznaczono jako rozliczone',correctExtraHours:'Skorygowano rozliczone'}[cmd.type])+' dodatkowe godziny: '+h.description});return db}
 case 'productCopy':if(cmd.copy.color&&!/^#[0-9a-fA-F]{6}$/.test(cmd.copy.color))throw Error('Wybierz poprawny kolor produktu.');if(!['personal','physio'].includes(cmd.service)||!cmd.copy.name.trim()||!cmd.copy.subtitle.trim())throw Error('Uzupełnij nazwę i podtytuł.');(db.productCopies??={})[cmd.service]={color:cmd.copy.color||productColor(db,cmd.service),name:cmd.copy.name.trim(),subtitle:cmd.copy.subtitle.trim(),bullets:cmd.copy.bullets.map(s=>s.trim()).filter(Boolean)};break;case 'promotion':{const p=cmd.promotion,value=p.kind==='email'?p.value.trim().toLowerCase():p.value.trim().toUpperCase();if(!value||(p.kind==='email'&&!/^\S+@\S+\.\S+$/.test(value))||!Number.isFinite(p.percent)||p.percent<=0||p.percent>100)throw Error('Podaj poprawny e-mail lub kod oraz rabat od 1 do 100%.');if(p.kind==='code'&&(!Number.isInteger(p.maxUses)||p.maxUses<1||!/^\d{4}-\d{2}-\d{2}$/.test(p.expires)||p.expires<dateOf(new Date(db.now))))throw Error('Podaj liczbę użyć i przyszłą datę ważności.');if((db.promotions||[]).some(x=>x.active&&x.kind===p.kind&&x.value===value))throw Error('Aktywna promocja o tej wartości już istnieje.');(db.promotions??=[]).push({...p,id:uid(),value,used:0});break}case 'disablePromotion':{const p=db.promotions?.find(p=>p.id===cmd.id);if(p)p.active=false;break}case 'extraHours':if(!db.trainers.some(t=>t.id===cmd.trainerId&&!t.deleted)||!/^\d{4}-\d{2}$/.test(cmd.month)||!Number.isFinite(cmd.hours)||cmd.hours<=0||!Number.isFinite(cmd.rate)||cmd.rate<=0||!cmd.description.trim())throw Error('Wybierz trenera, miesiąc, liczbę godzin, stawkę i opis.');(db.extraHours??=[]).push({...cmd,id:uid(),amount:Math.round(cmd.hours*cmd.rate*100)/100});break}db.audit.unshift({id:uid(),at:db.now,text:cmd.type==='extraHours'?'Dodano pozatreningowy czas pracy':cmd.type==='productCopy'?'Zmieniono opis karty produktu':'Zmieniono promocje'});return db}
