import React,{useState} from 'react';
import {Plus,Pencil,Trash2,Check,History} from 'lucide-react';
import {Field,useApp} from './context';
import {Input} from './controls';
import {AmountInput} from './admin-ui';
import {dateOf,money} from './domain';
import type {ExtraHours} from './business';
export function CompanyHours({id}:{id:string}){
 const {db,run}=useApp(),trainer=db.trainers.find(t=>t.id===id)!;
 const [month,setMonth]=useState(dateOf(new Date(db.now)).slice(0,7)),[editing,setEditing]=useState<ExtraHours|null>(null),[hours,setHours]=useState(1),[rate,setRate]=useState(trainer.rate||100),[description,setDescription]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState<{id:string;mode:'delete'|'settle'}|null>(null),[busy,setBusy]=useState(false);
 const history=(db.extraHours||[]).filter(h=>h.trainerId===id&&h.month===month).slice().reverse();
 const reset=()=>{setEditing(null);setHours(1);setRate(trainer.rate||100);setDescription('');setReason('')};
 const begin=(h:ExtraHours)=>{setEditing(h);setHours(h.hours);setRate(h.rate);setDescription(h.description);setReason('')};
 return <><div className="modal-title"><span className="eyebrow">DODATKOWY CZAS PRACY</span><h2>{trainer.name}</h2><p>Spotkania zespołu i pozostała praca dla ACO!</p></div><Field label="Miesiąc rozliczenia"><Input type="month" required disabled={!!editing} value={month} onChange={e=>setMonth(e.target.value)}/></Field><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const command=editing?editing.settledAt?{type:'correctExtraHours' as const,id:editing.id,hours,rate,description,reason}:{type:'editExtraHours' as const,id:editing.id,hours,rate,description}:{type:'extraHours' as const,trainerId:id,month,hours,rate,description};if(await run(command,'Dodatkowe godziny zapisane.'))reset()}finally{setBusy(false)}}}>
 <h3>{editing?(editing.settledAt?'Korekta rozliczonych godzin':'Edytuj godziny'):'Dodaj godziny'}</h3><Field label="Opis pracy"><Input placeholder="np. Spotkanie zespołu" required value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="form-grid"><Field label="Liczba godzin"><Input type="number" min={editing?.settledAt?0:.25} step="0.25" required value={hours} onChange={e=>setHours(Number(e.target.value))}/></Field><Field label="Stawka za godzinę"><AmountInput value={rate} onChange={setRate}/></Field></div>{editing?.settledAt&&<><Field label="Powód korekty"><textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="hint">Poprzednie wartości pozostaną w historii. Wpisz 0 godzin, aby skorygować całość.</p><p>Różnica: <strong>{money(Math.round(hours*rate*100)/100-editing.amount)}</strong></p></>}<div className="hours-total"><span>{editing?'Po zmianie':'Do rozliczenia'}</span><strong>{money(hours*rate)}</strong></div><div className="form-actions">{editing&&<button type="button" className="button secondary" onClick={reset}>Anuluj edycję</button>}<button className="button primary" disabled={busy}><Plus size={17}/>{editing?'Zapisz zmianę':'Dopisz godziny'}</button></div></form>
 <section className="hours-history"><h3>Zapisane w tym miesiącu <span className="number-badge">{history.length}</span></h3>{history.length?history.map(h=><article className="hours-entry" key={h.id}><div className="audit-row"><div><strong>{h.description}</strong><small>{h.hours} h × {money(h.rate)}</small></div><strong>{money(h.amount)}</strong></div><div className="hours-entry-actions"><span className={'badge '+(h.settledAt?'green':'neutral')}>{h.settledAt?'Rozliczone':'Nierozliczone'}{h.corrections?.length?' · po korekcie':''}</span><button className="button secondary" disabled={!!editing} onClick={()=>begin(h)}><Pencil size={14}/>{h.settledAt?'Korekta':'Edytuj'}</button>{!h.settledAt&&<><button className="icon-btn" title="Oznacz jako rozliczone" aria-label={'Rozlicz: '+h.description} disabled={!!editing} onClick={()=>setConfirm({id:h.id,mode:'settle'})}><Check size={17}/></button><button className="icon-btn" title="Usuń godziny" aria-label={'Usuń: '+h.description} disabled={!!editing} onClick={()=>setConfirm({id:h.id,mode:'delete'})}><Trash2 size={17}/></button></>}</div>{confirm?.id===h.id&&<div className="inset spaced" role="alert"><p>{confirm.mode==='delete'?'Usunąć nierozliczone godziny?':'Oznaczyć godziny jako rozliczone? Dalsze zmiany będą zapisywane jako korekty.'}</p><div className="form-actions"><button className="button secondary" onClick={()=>setConfirm(null)}>Anuluj</button><button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{if(await run({type:confirm.mode==='delete'?'deleteExtraHours':'settleExtraHours',id:h.id}))setConfirm(null)}finally{setBusy(false)}}}>Potwierdź</button></div></div>}{!!h.corrections?.length&&<details className="hours-corrections"><summary><History size={14}/> Historia korekt ({h.corrections.length})</summary>{h.corrections.map((c,i)=><div key={i}><strong>{new Date(c.at).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw'})}</strong><p>{c.reason}</p><p>{c.before.hours} h × {money(c.before.rate)} → {c.after.hours} h × {money(c.after.rate)}</p><small>{money(c.before.amount)} → {money(c.after.amount)} · różnica {money(c.after.amount-c.before.amount)}</small>{c.before.description!==c.after.description&&<p>{c.before.description} → {c.after.description}</p>}</div>)}</details>}</article>):<p className="hint">Brak dodatkowych godzin w tym miesiącu.</p>}</section></>;
}
