import {business,quote,renewalAllowed,BusinessCommand,ProductCopy,Promotion,ExtraHours} from './business';
export interface Rules {renewalDays:number;cycleWeeks:number;validWeeks:number;coachHoldHours:number;checkoutMinutes:number;protectionDays:number;consultationDays:number;startDays:number;substituteHours:number;freezeDays:number}
export const defaultRules:Rules={renewalDays:7,cycleWeeks:4,validWeeks:6,coachHoldHours:48,checkoutMinutes:15,protectionDays:1,consultationDays:7,startDays:14,substituteHours:48,freezeDays:7};
export const rules=(db:State):Rules=>Object.fromEntries(Object.entries(defaultRules).map(([key,value])=>[key,db.settings.rules?.[key as keyof Rules]??value])) as unknown as Rules;
export const packagePrice=(db:State,service:string,intensity:number)=>db.settings.packagePrices?.[service]?.[intensity]??db.settings[service as 'personal'|'physio']*intensity*rules(db).cycleWeeks;
export const trainerHours=(t:Trainer,day:number)=>t.weeklyHours?t.weeklyHours[day]||[]:t.days.includes(day)?t.hours:[];
export type Role = 'trainer' | 'client' | 'admin' | 'guest';
export type Status = 'scheduled' | 'completed' | 'no_show' | 'cancelled_early' | 'cancelled_late' | 'cancelled_trainer';
export interface Trainer { weeklyHours?:Record<number,number[]>; id:string; name:string; specialty?:string; deleted?:boolean; photo?:string; products?:('personal'|'physio')[]; productRates?:{personal:number;physio:number}; productRateHistory?:{from:string;personal:number;physio:number}[]; phone?:string; pesel?:string; student?:boolean; address?:string; taxOffice?:string; rate:number; days:number[]; hours:number[]; rates?:{from:string;rate:number}[] }
export interface Client { photo?:string; id:string; name:string; email:string; birthDate?:string; phone:string; trainerId:string; active:boolean; invited:boolean; service:'personal'|'physio'; intensity:number; prescribed:boolean; answers:string[] }
export interface Package {basePrice?:number;discountPercent?:number;promotionId?:string; id:string; clientId:string; count:number; start:string; cycleEnd:string; validUntil:string; protectionUntil:string; slots:{day:number;hour:number}[]; service:string; intensity:number; price:number; frozen?:boolean }
export interface Session { consultationPrice?:number; id:string; clientId:string; trainerId:string; packageId?:string; date:string; hour:number; kind:'training'|'consultation'; status:Status; publicNote:string; privateNote:string; comments:{id:string;author:string;text:string;at:string}[]; original?:string; earned?:number; rate?:number; substituteId?:string }
export interface Hold { paymentRequest?:{code:string;at:string}; terms?:Rules; id:string; clientId:string; trainerId:string; dates:{date:string;hour:number;original?:string}[]; slots:{day:number;hour:number}[]; start:string; expires:string; service:string; intensity:number; price:number; status:'active'|'paid'|'expired'; type:'coach'|'checkout' }
export interface Message { id:string; clientId?:string; title:string; body:string; at:string; read:boolean; target:'all'|'client'|'staff'|'admin' }
export interface Sale { packageId?:string; sessionId?:string; id:string; clientId:string; label:string; amount:number; date:string; status:'paid'|'refunded' }
export interface Substitution { id:string; clientId:string; trainerId:string; until:string }
export interface State {productCopies?:Record<string,ProductCopy>;promotions?:Promotion[];extraHours?:ExtraHours[]; version:1; now:string; clients:Client[]; trainers:Trainer[]; sessions:Session[]; packages:Package[]; holds:Hold[]; messages:Message[]; sales:Sale[]; substitutions:Substitution[]; audit:{id:string;text:string;at:string}[]; settings:{rules?:Rules;packagePrices?:Record<string,Record<number,number>>;personal:number;physio:number;consultation:number;cancelHours:number}; blocks:{visibility?:'busy'|'hidden';id:string;trainerId:string;date:string;hour:number}[] }
export interface Actor { role:Role; trainerId:string; clientId:string }
export const uid = () => crypto.randomUUID();
export const dateOf=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
export const dayAdd=(s:string,n:number)=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export const at=(d:string,h:number)=>{
 const target=Date.parse(`${d}T${String(h).padStart(2,'0')}:00:00Z`);
 if(!Number.isFinite(target))return new Date(NaN);
 const formatter=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
 let instant=target;
 for(let i=0;i<3;i++){const wall=Date.parse(formatter.format(new Date(instant)).replace(' ','T')+'Z');instant+=target-wall}
 const resolved=new Date(instant);
 return formatter.format(resolved).slice(0,13)===`${d} ${String(h).padStart(2,'0')}`?resolved:new Date(NaN);
};
export const endAt=(s:Session)=>new Date(+at(s.date,s.hour)+(s.kind==='consultation'?90:60)*60000);
export const weekOf=(s:string)=>dayAdd(s,-dayIndex(s));
export const dayIndex=(s:string)=>(new Date(s+'T12:00:00Z').getUTCDay()+6)%7;
export const money = (n:number) => new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(n);
export const labelDate = (s:string, opts:Intl.DateTimeFormatOptions={day:'numeric',month:'long'}) => new Date(s.slice(0,10)+'T12:00:00').toLocaleDateString('pl-PL',opts);
export const hourLabel = (h:number) => `${String(h).padStart(2,'0')}:00`;
export const serviceName = (s:string) => s==='physio'?'Powrót do zdrowia':'Trening personalny';
export const statusLabels:Record<Status,string>={scheduled:'Zaplanowany',completed:'Zrealizowany',no_show:'Nieobecność',cancelled_early:'Odwołany na czas',cancelled_late:'Późne odwołanie',cancelled_trainer:'Odwołany przez trenera'};
export const spends = (s:Session) => ['completed','no_show','cancelled_late'].includes(s.status);
export const counts = (s:Session) => s.status==='scheduled'||spends(s);
export const remaining = (db:State,p:Package) => Math.max(0,p.count-db.sessions.filter(s=>s.packageId===p.id&&spends(s)).length);
export const unbooked = (db:State,p:Package) => Math.max(0,p.count-db.sessions.filter(s=>s.packageId===p.id&&counts(s)).length);
export const currentPackage = (db:State,id:string) => db.packages.filter(p=>p.clientId===id).sort((a,b)=>b.start.localeCompare(a.start))[0];
export const canSee = (db:State,a:Actor,c:Client) => a.role==='admin'||(a.role==='client'&&a.clientId===c.id&&c.active)||(a.role==='trainer'&&(a.trainerId===c.trainerId||db.substitutions.some(s=>s.clientId===c.id&&s.trainerId===a.trainerId&&s.until>db.now)));
export const balance = (db:State,id:string) => db.packages.filter(p=>p.clientId===id&&p.validUntil>dateOf(new Date(db.now))&&!p.frozen).reduce((n,p)=>n+unbooked(db,p),0);
export function available(db:State,trainerId:string,date:string,hour:number,clientId?:string,exclude?:string,ignoreHold?:string):boolean {
 const t=db.trainers.find(t=>t.id===trainerId)!; const now=new Date(db.now);
 if(!Number.isFinite(+at(date,hour))||!t||t.deleted||!trainerHours(t,dayIndex(date)).includes(hour)||+at(date,hour)<=+now)return false;
 if(db.blocks.some(b=>b.trainerId===trainerId&&b.date===date&&b.hour===hour))return false;
 if(db.sessions.some(s=>s.id!==exclude&&s.date===date&&(s.status==='scheduled'||s.kind==='consultation'&&s.status==='completed'&&endAt(s)>now)&&(s.trainerId===trainerId||s.clientId===clientId)&&hour>=s.hour&&hour<s.hour+(s.kind==='consultation'?2:1)))return false;
 if(db.holds.some(h=>h.id!==ignoreHold&&h.status==='active'&&h.expires>db.now&&(h.trainerId===trainerId||h.clientId===clientId)&&h.dates.some(d=>d.date===date&&d.hour===hour)))return false;
 if(db.packages.some(p=>p.clientId!==clientId&&db.clients.find(c=>c.id===p.clientId)?.trainerId===trainerId&&p.protectionUntil>dateOf(new Date(db.now))&&date>=p.start&&p.slots.some(s=>s.day===dayIndex(date)&&s.hour===hour)&&!db.sessions.some(s=>s.packageId===p.id&&((s.date===date&&s.hour===hour&&s.status.startsWith('cancelled'))||s.original===`${date} ${hourLabel(hour)}`))))return false;
 return true;
}
function notify(db:State,title:string,body:string,clientId?:string) {db.messages.unshift({id:uid(),title,body:clientId?`${db.clients.find(c=>c.id===clientId)?.name||'Klient'} · ${body}`:body,clientId,at:db.now,read:false,target:'all'})}
function audit(db:State,text:string) {db.audit.unshift({id:uid(),text,at:db.now})}
export function effectiveRate(db:State,s:Session){const t=db.trainers.find(t=>t.id===s.trainerId)!;const service=(db.packages.find(p=>p.id===s.packageId)?.service||db.clients.find(c=>c.id===s.clientId)?.service||'personal') as 'personal'|'physio';const rates=t.productRateHistory?.filter(r=>r.from<=s.date).sort((a,b)=>b.from.localeCompare(a.from))[0]||t.productRates;if(rates)return rates[service];return t.rates?.filter(r=>r.from<=s.date).sort((a,b)=>b.from.localeCompare(a.from))[0]?.rate??t.rate}
function requireStaff(a:Actor){if(!['admin','trainer'].includes(a.role))throw Error('Ta operacja wymaga uprawnień trenera.')}
function requireAdmin(a:Actor){if(a.role!=='admin')throw Error('Ta operacja jest dostępna tylko administratorowi.')}
function getSession(db:State,a:Actor,id:string){const s=db.sessions.find(s=>s.id===id);if(!s)throw Error('Nie znaleziono sesji.');const c=db.clients.find(c=>c.id===s.clientId)!;if(!canSee(db,a,c))throw Error('Brak dostępu do tego klienta.');return s}
function limitCheck(db:State,c:Client,date:string,exclude?:string,extra:{date:string}[]=[],ignoreHold?:string){if(db.sessions.some(s=>s.id!==exclude&&s.clientId===c.id&&s.kind==='training'&&s.date===date&&counts(s))||extra.some(d=>d.date===date)||db.holds.some(h=>h.id!==ignoreHold&&h.clientId===c.id&&h.status==='active'&&h.expires>db.now&&h.dates.some(d=>d.date===date)))throw Error('Można umówić tylko jeden trening dziennie.');const n=db.sessions.filter(s=>s.id!==exclude&&s.clientId===c.id&&s.kind==='training'&&weekOf(s.date)===weekOf(date)&&counts(s)).length+db.holds.filter(h=>h.id!==ignoreHold&&h.clientId===c.id&&h.status==='active'&&h.expires>db.now).flatMap(h=>h.dates).filter(d=>weekOf(d.date)===weekOf(date)).length+extra.filter(d=>weekOf(d.date)===weekOf(date)).length;if(n>=c.intensity)throw Error(`Limit ${c.intensity} treningów w tygodniu został wykorzystany. Wybierz inny tydzień.`)}
export type Command = BusinessCommand
 | {type:'requestPayment';id:string;code?:string}
 | {type:'confirmConsultation';id:string}
 | {type:'updateProfile';name:string;email:string;phone:string;photo:string}
 | {type:'availability';trainerId?:string;days:number[];hours:number[];weeklyHours?:Record<number,number[]>}
 | {type:'transferClient';clientId:string;trainerId:string}
 | {type:'deleteTrainer';id:string}
 | {type:'birthDate';id:string;value:string}
 | {type:'sendLetter';to:string;subject:string;body:string}
 | {type:'readLetter'|'readNotice';id:string}
 | {type:'outcome';id:string;status:Status}
 | {type:'notes';id:string;publicNote:string;privateNote:string}
 | {type:'comment';id:string;text:string}
 | {type:'reschedule';id:string;date:string;hour:number}
 | {type:'prescribe';id:string;service:'personal'|'physio';intensity:number}
 | {type:'activate';id:string;service?:'personal'|'physio';intensity?:number}
 | {type:'acceptInvite';id:string}
 | {type:'register';birthDate?:string;name:string;email:string;phone:string;trainerId:string;date:string;hour:number;answers:string[]}
 | {type:'manualClient';name:string;email:string;phone:string;trainerId:string}
 | {type:'hold';clientId:string;start:string;slots:{day:number;hour:number}[];dates:{date:string;hour:number;original?:string}[]}
 | {type:'payHold';id:string;code?:string}
 | {type:'editHold';id:string;dates:{date:string;hour:number;original?:string}[]}
 | {type:'makeup';packageId:string;date:string;hour:number}
 | {type:'substitute';clientId:string;trainerId:string;from:string;to:string}
 | {type:'extend';packageId:string;days:number}
 | {type:'validity';packageId:string;date:string}
 | {type:'freeze';packageId:string}
 | {type:'block';visibility?:'busy'|'hidden';trainerId:string;date:string;hour:number}
 | {type:'unblock';id:string}
 | {type:'settings';rules?:Rules;packagePrices?:Record<string,Record<number,number>>;personal:number;physio:number;consultation:number;cancelHours:number}
 | {type:'rate';trainerId:string;rate:number}
 | {type:'read';id:string}
 | {type:'clock';hours:number};
export function execute(source:State,a:Actor,cmd:Command):State {
 const db=structuredClone(source);const now=new Date(db.now);if(['productCopy','promotion','disablePromotion','extraHours'].includes(cmd.type))return business(db,a,cmd as BusinessCommand);
 db.holds.forEach(h=>{if(h.status==='active'&&h.expires<=db.now)h.status='expired'});
 switch(cmd.type){
 case 'availability':{requireAdmin(a);const t=db.trainers.find(t=>t.id===cmd.trainerId&&!t.deleted);if(!t)throw Error('Nie znaleziono trenera.');if(cmd.days.some(d=>!Number.isInteger(d)||d<0||d>6)||cmd.hours.some(h=>!Number.isInteger(h)||h<0||h>23))throw Error('Wybierz dni i godziny pracy.');const weekly=cmd.weeklyHours||Object.fromEntries(cmd.days.map(d=>[d,cmd.hours]));if(Object.entries(weekly).some(([d,hs])=>!Number.isInteger(Number(d))||Number(d)<0||Number(d)>6||!Array.isArray(hs)||hs.some(h=>!Number.isInteger(h)||h<0||h>23)))throw Error('Niepoprawny zakres godzin.');const fits=(date:string,hour:number)=>(weekly[dayIndex(date)]||[]).includes(hour);if(db.sessions.some(s=>s.trainerId===t.id&&s.status==='scheduled'&&at(s.date,s.hour)>now&&(!fits(s.date,s.hour)||s.kind==='consultation'&&!fits(s.date,s.hour+1)))||db.holds.some(h=>h.trainerId===t.id&&h.status==='active'&&h.expires>db.now&&h.dates.some(d=>!fits(d.date,d.hour))))throw Error('Zmiana koliduje z zaplanowaną wizytą lub rezerwacją. Najpierw zmień jej termin.');t.weeklyHours=structuredClone(weekly);t.days=[...new Set(Object.keys(weekly).map(Number).filter(d=>weekly[d].length))].sort((a,b)=>a-b);t.hours=[...new Set(Object.values(weekly).flat())].sort((a,b)=>a-b);audit(db,'Administrator zaktualizował dostępność: '+t.name);break}

 case 'outcome': {const s=getSession(db,a,cmd.id);if(s.status!=='scheduled')throw Error('Ta sesja została już rozliczona.');
  if(['completed','no_show'].includes(cmd.status)){requireStaff(a);if(a.role==='trainer'&&s.trainerId!==a.trainerId)throw Error('Sesję rozlicza trener, który ją prowadził.');if((s.kind==='consultation'?+at(s.date,s.hour)+30*60000:+endAt(s))>+now)throw Error(s.kind==='consultation'?'Konsultację można rozliczyć 30 minut po rozpoczęciu.':'Sesję można rozliczyć dopiero po jej zakończeniu.');s.status=cmd.status;s.rate=effectiveRate(db,s);s.earned=s.rate*(s.kind==='consultation'?1.5:1)}
  else {if(s.kind==='consultation'&&a.role!=='admin')throw Error('W sprawie zmiany konsultacji skontaktuj się z administratorem ACO!.');if(+at(s.date,s.hour)<=+now)throw Error('Ta sesja już się rozpoczęła. Oznacz realizację lub nieobecność.');
   const coach=a.role==='trainer'||(a.role==='admin'&&cmd.status==='cancelled_trainer');s.status=coach?'cancelled_trainer':(+at(s.date,s.hour)-+now>=db.settings.cancelHours*3600000?'cancelled_early':'cancelled_late');
   if(s.status==='cancelled_late'){s.rate=effectiveRate(db,s);s.earned=s.rate*(s.kind==='consultation'?1.5:1)}

  }notify(db,statusLabels[s.status],`${labelDate(s.date)}, ${hourLabel(s.hour)}. ${s.status==='cancelled_trainer'?'Wejście jest dostępne do ponownego umówienia.':''}`,s.clientId);audit(db,`${statusLabels[s.status]}: ${s.id}`);break}
 case 'notes':{requireStaff(a);const s=getSession(db,a,cmd.id);s.publicNote=cmd.publicNote;s.privateNote=cmd.privateNote;if(a.role==='trainer')db.messages.unshift({id:uid(),title:'Trener dodał notatkę',body:`${db.trainers.find(t=>t.id===a.trainerId)?.name}: ${db.clients.find(c=>c.id===s.clientId)?.name}, ${labelDate(s.date)}.`,at:db.now,read:false,target:'admin'});audit(db,`Zapisano notatki sesji ${s.id}`);break}
 case 'comment':{const s=getSession(db,a,cmd.id);if(!cmd.text.trim())throw Error('Wpisz treść komentarza.');s.comments.push({id:uid(),author:a.role==='client'?db.clients.find(c=>c.id===a.clientId)!.name:a.role==='admin'?'Administrator':db.trainers.find(t=>t.id===a.trainerId)!.name,text:cmd.text.trim(),at:db.now});notify(db,'Nowy komentarz',`Nowa wiadomość przy sesji ${labelDate(s.date)}.`,s.clientId);break}
 case 'reschedule':{const s=getSession(db,a,cmd.id);if(s.kind==='consultation'){requireAdmin(a);if(s.status!=='scheduled'||at(s.date,s.hour)<=now)throw Error('Można zmienić tylko przyszłą konsultację.');if(!available(db,s.trainerId,cmd.date,cmd.hour,s.clientId,s.id)||!available(db,s.trainerId,cmd.date,cmd.hour+1,s.clientId,s.id))throw Error('Konsultacja wymaga dwóch wolnych godzin.');s.original=s.original||`${s.date} ${hourLabel(s.hour)}`;s.date=cmd.date;s.hour=cmd.hour;notify(db,'Zmieniono konsultację',`${labelDate(s.date)}, ${hourLabel(s.hour)}`,s.clientId);break;}if(s.status!=='scheduled')throw Error('Można przełożyć tylko zaplanowany trening.');if(+at(s.date,s.hour)-+now<db.settings.cancelHours*3600000)throw Error(`Zostało mniej niż ${db.settings.cancelHours} h. Odwołaj sesję (wejście przepadnie), a nową umów z wolnego wejścia.`);const p=db.packages.find(p=>p.id===s.packageId)!;if(cmd.date<p.start||cmd.date>=p.validUntil||p.frozen)throw Error('Termin jest poza ważnością pakietu albo pakiet jest zamrożony.');if(!available(db,s.trainerId,cmd.date,cmd.hour,s.clientId,s.id))throw Error('Ten termin jest niedostępny.');limitCheck(db,db.clients.find(c=>c.id===s.clientId)!,cmd.date,s.id);s.original=s.original||`${s.date} ${hourLabel(s.hour)}`;s.date=cmd.date;s.hour=cmd.hour;notify(db,'Zmieniono termin treningu',`Nowy termin: ${labelDate(s.date)}, ${hourLabel(s.hour)}.`,s.clientId);audit(db,`Przełożono sesję ${s.id}`);break}
 case 'prescribe':{requireStaff(a);const c=db.clients.find(c=>c.id===cmd.id)!;if(c.invited||c.active)throw Error('Po aktywacji nie można zmieniać produktu.');if(!canSee(db,a,c)||(a.role==='trainer'&&c.trainerId!==a.trainerId))throw Error('Produkt przypisuje trener prowadzący.');if(!db.trainers.find(t=>t.id===c.trainerId)?.products?.includes(cmd.service)&&db.trainers.find(t=>t.id===c.trainerId)?.products)throw Error('Trener nie prowadzi wybranego produktu.');if(![1,2,3].includes(cmd.intensity))throw Error('Wybierz intensywność 1, 2 lub 3.');if(db.packages.some(p=>p.clientId===c.id&&p.validUntil>dateOf(new Date(db.now)))&&cmd.intensity!==c.intensity)throw Error('Zmień intensywność po zakończeniu bieżących pakietów.');c.service=cmd.service;c.intensity=cmd.intensity;c.prescribed=true;audit(db,`Przypisano wariant: ${c.name}, ${c.intensity}× / tydzień`);break}
 case 'activate':{requireStaff(a);const c=db.clients.find(c=>c.id===cmd.id)!;if(!c)throw Error('Nie znaleziono klienta.');if(a.role==='trainer'&&c.trainerId!==a.trainerId)throw Error('Aktywuje trener prowadzący.');if(c.invited||c.active)throw Error('Klient jest już zatwierdzony.');const consultation=db.sessions.find(s=>s.clientId===c.id&&s.kind==='consultation'&&['scheduled','completed'].includes(s.status)&&+at(s.date,s.hour)+30*60000<=+now);if(a.role!=='admin'&&!consultation)throw Error('Aktywacja jest dostępna 30 minut po rozpoczęciu konsultacji.');const service=cmd.service||(c.prescribed?c.service:undefined),intensity=cmd.intensity||(c.prescribed?c.intensity:undefined);if(!service||!intensity||![1,2,3].includes(intensity)||!['personal','physio'].includes(service))throw Error('Wybierz produkt i intensywność.');const t=db.trainers.find(t=>t.id===c.trainerId)!;if(t.products&&!t.products.includes(service))throw Error('Trener nie prowadzi tego produktu.');c.service=service;c.intensity=intensity;c.prescribed=true;c.invited=true;if(consultation&&consultation.status==='scheduled'){consultation.status='completed';consultation.rate=effectiveRate(db,consultation);consultation.earned=consultation.rate*1.5}notify(db,'Możesz aktywować konto','Możesz ustawić hasło podając e-mail i datę urodzenia.',c.id);db.messages[0].target='client';audit(db,`Zatwierdzono aktywację i produkt: ${c.name}`);break}
 case 'acceptInvite':{const c=db.clients.find(c=>c.id===cmd.id)!;if(a.role!=='client'||a.clientId!==c.id||!c.invited)throw Error('Brak zaproszenia do aktywacji.');c.active=true;notify(db,'Witaj w ACO!','Twoje konto jest aktywne. Możesz wybrać terminy treningów.',c.id);break}
 case 'register':case 'manualClient':{if(cmd.type==='manualClient')requireAdmin(a);if(!cmd.name.trim()||!/^\S+@\S+\.\S+$/.test(cmd.email.trim()))throw Error('Podaj imię, nazwisko i poprawny e-mail.');if(db.clients.some(c=>c.email.toLowerCase()===cmd.email.trim().toLowerCase()))throw Error('Profil z tym adresem e-mail już istnieje.');const id=uid();
 if(cmd.type==='register'){if(cmd.date>dayAdd(dateOf(new Date(db.now)),rules(db).consultationDays))throw Error(`Konsultację można umówić maksymalnie ${rules(db).consultationDays} dni naprzód.`);if(!available(db,cmd.trainerId,cmd.date,cmd.hour)||!available(db,cmd.trainerId,cmd.date,cmd.hour+1))throw Error('Konsultacja wymaga dwóch wolnych godzin.');db.sessions.push({id:uid(),clientId:id,trainerId:cmd.trainerId,date:cmd.date,hour:cmd.hour,kind:'consultation',status:'scheduled',publicNote:'',privateNote:'',comments:[]});db.sales.unshift({id:uid(),clientId:id,label:'Konsultacja',amount:db.settings.consultation,date:db.now,status:'paid'})}
 db.clients.push({id,name:cmd.name.trim(),email:cmd.email.trim().toLowerCase(),phone:cmd.phone,trainerId:cmd.trainerId,active:false,invited:false,service:db.trainers.find(t=>t.id===cmd.trainerId)?.products?.[0]||'personal',intensity:2,prescribed:false,birthDate:cmd.type==='register'?cmd.birthDate:undefined,answers:cmd.type==='register'?cmd.answers:[]});notify(db,cmd.type==='register'?'Konsultacja zarezerwowana':'Dodano profil klienta',`${cmd.type==='register'?labelDate(cmd.date)+', '+hourLabel(cmd.hour)+' · '+db.trainers.find(t=>t.id===cmd.trainerId)?.name+'. ':''}Aktywacja nastąpi po konsultacji i zatwierdzeniu przez trenera. Aby zmienić konsultację, skontaktuj się z administratorem.`,id);audit(db,`Dodano profil: ${cmd.name}`);break}
 case 'hold':{const c=db.clients.find(c=>c.id===cmd.clientId)!;if(!renewalAllowed(db,c.id))throw Error(`Kolejny pakiet można kupić ${rules(db).renewalDays} dni przed końcem obecnego cyklu.`);if(new Set(cmd.slots.map(s=>s.day)).size!==cmd.slots.length)throw Error('Wybierz najwyżej jeden trening w każdym dniu.');if(!canSee(db,a,c)||!c.prescribed)throw Error('Najpierw przypisz produkt klientowi.');if(cmd.slots.length!==c.intensity||cmd.dates.length!==c.intensity*rules(db).cycleWeeks)throw Error('Wybierz wszystkie stałe godziny i terminy pakietu.');if(db.packages.some(p=>p.clientId===c.id&&cmd.start<p.cycleEnd&&dayAdd(cmd.start,rules(db).cycleWeeks*7)>p.start))throw Error('Nowy cykl nie może nakładać się na obecny.');if(db.holds.some(h=>h.clientId===c.id&&h.status==='active'&&h.expires>db.now))throw Error('Ten klient ma już rezerwację wstępną.');for(const slot of cmd.slots){const occurrences=Array.from({length:rules(db).cycleWeeks},(_,w)=>dayAdd(cmd.start,(slot.day-dayIndex(cmd.start)+7)%7+w*7));if(occurrences.filter(d=>!available(db,c.trainerId,d,slot.hour,c.id)).length>rules(db).cycleWeeks/2)throw Error('Ponad połowa terminów tej stałej godziny jest zajęta. Wybierz inną godzinę.');}const selected:{date:string}[]=[];
 for(const d of cmd.dates){if(d.date<cmd.start||d.date>=dayAdd(cmd.start,rules(db).cycleWeeks*7))throw Error(`Wszystkie daty muszą zmieścić się w ${rules(db).cycleWeeks} tygodniach.`);if(!available(db,c.trainerId,d.date,d.hour,c.id))throw Error(`Termin ${labelDate(d.date)} ${hourLabel(d.hour)} jest niedostępny.`);if(cmd.dates.filter(x=>x.date===d.date&&x.hour===d.hour).length>1)throw Error('Dwa treningi nie mogą mieć tego samego terminu.');limitCheck(db,c,d.date,undefined,selected);selected.push(d)}
 if([...cmd.dates].sort((a,b)=>a.date.localeCompare(b.date))[c.intensity-1].date>dayAdd(dateOf(new Date(db.now)),rules(db).startDays))throw Error(`Pierwsze ${c.intensity} treningi muszą odbyć się w ciągu ${rules(db).startDays} dni od zakupu.`);const first=Math.min(...cmd.dates.map(d=>+at(d.date,d.hour)));const expires=new Date(Math.min(+now+(a.role==='client'?rules(db).checkoutMinutes/60:rules(db).coachHoldHours)*3600000,first)).toISOString();db.holds.unshift({id:uid(),clientId:c.id,trainerId:c.trainerId,dates:cmd.dates,slots:cmd.slots,start:[...cmd.dates].sort((a,b)=>a.date.localeCompare(b.date))[0].date,expires,service:c.service,intensity:c.intensity,price:packagePrice(db,c.service,c.intensity),terms:rules(db),status:'active',type:a.role==='client'?'checkout':'coach'});notify(db,'Terminy czekają na opłacenie',`Zarezerwowano ${cmd.dates.length} treningów z ${db.trainers.find(t=>t.id===c.trainerId)?.name}. Pierwszy: ${labelDate(cmd.dates.slice().sort((a,b)=>a.date.localeCompare(b.date))[0].date)}. Płatność do ${new Date(expires).toLocaleString('pl-PL')}.`,c.id);break}
 case 'editHold':{const h=db.holds.find(h=>h.id===cmd.id)!;const c=db.clients.find(c=>c.id===h.clientId)!;if(!canSee(db,a,c)||h.status!=='active'||h.expires<=db.now)throw Error('Rezerwacja nie jest aktywna.');if(cmd.dates.length!==h.dates.length)throw Error('Zachowaj wszystkie treningi.');const selected:{date:string}[]=[];for(const d of cmd.dates){if(d.date<h.start||d.date>=dayAdd(h.start,(h.terms||defaultRules).cycleWeeks*7))throw Error('Wybierz termin w cyklu zarezerwowanego pakietu.');if(!available(db,h.trainerId,d.date,d.hour,c.id,undefined,h.id))throw Error('Wybrany termin jest niedostępny.');if(cmd.dates.filter(x=>x.date===d.date&&x.hour===d.hour).length>1)throw Error('Daty nie mogą się powtarzać.');limitCheck(db,c,d.date,undefined,selected,h.id);selected.push(d)}h.dates=cmd.dates;audit(db,'Zmieniono wyjątki rezerwacji bez przedłużenia terminu płatności');break}
 case 'payHold':{const h=db.holds.find(h=>h.id===cmd.id)!;const c=db.clients.find(c=>c.id===h.clientId)!;if(!canSee(db,a,c))throw Error('Brak dostępu.');if(h.status==='paid')throw Error('Ten pakiet został już opłacony.');if(h.terms&&h.terms.cycleWeeks!==rules(db).cycleWeeks)throw Error('Zmieniono długość pakietu. Wybierz terminy ponownie.');if(h.expires<=db.now)throw Error('Rezerwacja wygasła. Wybierz terminy ponownie.');for(const d of h.dates)if(!available(db,h.trainerId,d.date,d.hour,h.clientId,undefined,h.id))throw Error('Termin przestał być dostępny. Skontaktuj się z administratorem.');
 if([...h.dates].sort((a,b)=>a.date.localeCompare(b.date))[h.intensity-1].date>dayAdd(dateOf(new Date(db.now)),rules(db).startDays))throw Error('Pierwsze treningi wypadają poza dozwolonym terminem rozpoczęcia.');if(!renewalAllowed(db,c.id))throw Error('Zakup kolejnego pakietu nie jest jeszcze dostępny.');const pricing=quote(db,c.id,h.service,h.intensity,cmd.code);h.price=pricing.total;const terms=h.terms||defaultRules;const id=uid();db.packages.push({id,clientId:h.clientId,count:h.dates.length,start:h.start,cycleEnd:dayAdd(h.start,(h.terms||defaultRules).cycleWeeks*7),validUntil:dayAdd(h.start,terms.validWeeks*7),protectionUntil:dayAdd(h.start,terms.cycleWeeks*7+terms.protectionDays),slots:h.slots,service:h.service,intensity:h.intensity,price:h.price,basePrice:pricing.base,discountPercent:pricing.percent,promotionId:pricing.promotionId});if(pricing.code){const promo=db.promotions!.find(p=>p.id===pricing.promotionId)!;promo.used++}for(const d of h.dates)db.sessions.push({id:uid(),clientId:h.clientId,trainerId:h.trainerId,packageId:id,date:d.date,hour:d.hour,kind:'training',status:'scheduled',publicNote:'',privateNote:'',comments:[],original:d.original});h.status='paid';db.sales.unshift({id:uid(),packageId:id,clientId:c.id,label:`${serviceName(h.service)} · ${trainingCount(h.dates.length)}`,amount:h.price,date:db.now,status:'paid'});notify(db,'Twój pakiet jest aktywny',`${trainingCount(h.dates.length)}. Pakiet aktywny.`,c.id);audit(db,`Potwierdzenie płatności za pakiet: ${c.name}`);break}
 case 'makeup':{const p=db.packages.find(p=>p.id===cmd.packageId)!;const c=db.clients.find(c=>c.id===p.clientId)!;if(!canSee(db,a,c)||p.frozen||!unbooked(db,p)||cmd.date>=p.validUntil||cmd.date<p.start)throw Error('Brak ważnego wejścia na ten termin.');if(!available(db,c.trainerId,cmd.date,cmd.hour,c.id))throw Error('Termin jest zajęty.');limitCheck(db,c,cmd.date);db.sessions.push({id:uid(),clientId:c.id,trainerId:c.trainerId,packageId:p.id,date:cmd.date,hour:cmd.hour,kind:'training',status:'scheduled',publicNote:'',privateNote:'',comments:[]});notify(db,'Umówiono trening',`${labelDate(cmd.date)}, ${hourLabel(cmd.hour)}.`,c.id);break}
 case 'substitute':{requireAdmin(a);const c=db.clients.find(c=>c.id===cmd.clientId)!;if(cmd.trainerId===c.trainerId)throw Error('Wybierz innego trenera.');const list=db.sessions.filter(s=>s.clientId===c.id&&s.status==='scheduled'&&s.date>=cmd.from&&s.date<=cmd.to);if(!list.length)throw Error('Brak przyszłych wizyt w tym okresie.');for(const s of list){if(!available(db,cmd.trainerId,s.date,s.hour,c.id,s.id))throw Error(`Zastępca nie jest dostępny ${labelDate(s.date)} o ${hourLabel(s.hour)}.`);if(s.kind==='consultation'&&!available(db,cmd.trainerId,s.date,s.hour+1,c.id,s.id))throw Error('Brak dwóch godzin dla konsultacji.')}const id=uid();const until=new Date(Math.max(...list.map(s=>+endAt(s)))+rules(db).substituteHours*3600000).toISOString();list.forEach(s=>{s.trainerId=cmd.trainerId;s.substituteId=id});db.substitutions.push({id,clientId:c.id,trainerId:cmd.trainerId,until});notify(db,'Wyznaczono zastępstwo',`${db.trainers.find(t=>t.id===cmd.trainerId)!.name} poprowadzi ${list.length} sesji.`,c.id);audit(db,`Przydzielono zastępstwo: ${c.name}`);break}
 case 'validity':{requireAdmin(a);const p=db.packages.find(p=>p.id===cmd.packageId);if(!p)throw Error('Nie znaleziono pakietu.');if(!/^\d{4}-\d{2}-\d{2}$/.test(cmd.date)||!Number.isFinite(+at(cmd.date,12))||dayAdd(cmd.date,0)!==cmd.date||cmd.date<p.start)throw Error('Wybierz poprawną datę nie wcześniejszą niż początek pakietu.');const until=dayAdd(cmd.date,1);if(db.sessions.some(s=>s.packageId===p.id&&s.status==='scheduled'&&s.date>=until))throw Error('Po tej dacie są zaplanowane treningi. Najpierw przełóż je lub odwołaj.');p.validUntil=until;notify(db,'Zmieniono ważność pakietu',`Nowa ważność: ${labelDate(cmd.date)}.`,p.clientId);audit(db,`Zmieniono ważność pakietu klienta ${db.clients.find(c=>c.id===p.clientId)?.name} na ${cmd.date}`);break}
 case 'extend':{requireAdmin(a);const p=db.packages.find(p=>p.id===cmd.packageId)!;p.validUntil=dayAdd(p.validUntil,cmd.days);audit(db,`Przedłużono pakiet ${p.id} o ${cmd.days} dni`);break}
 case 'freeze':{requireAdmin(a);const p=db.packages.find(p=>p.id===cmd.packageId)!;p.frozen=!p.frozen;if(p.frozen){db.sessions.filter(s=>s.packageId===p.id&&s.status==='scheduled'&&at(s.date,s.hour)>now).forEach(s=>s.status='cancelled_early');p.validUntil=dayAdd(p.validUntil,rules(db).freezeDays)}audit(db,`${p.frozen?'Zamrożono pakiet i zwolniono wizyty':'Odmrożono pakiet'} ${p.id}`);break}
 case 'block':{requireAdmin(a);if(a.role==='trainer'&&a.trainerId!==cmd.trainerId)throw Error('Możesz zmienić tylko swój grafik.');if(!available(db,cmd.trainerId,cmd.date,cmd.hour))throw Error('Najpierw przełóż istniejące wizyty lub wybierz wolną godzinę.');db.blocks.push({id:uid(),trainerId:cmd.trainerId,date:cmd.date,hour:cmd.hour,visibility:cmd.visibility||'busy'});audit(db,'Dodano niedostępność');break}
 case 'unblock':{requireAdmin(a);const b=db.blocks.find(b=>b.id===cmd.id);if(!b||(a.role==='trainer'&&a.trainerId!==b.trainerId))throw Error('Brak dostępu.');db.blocks=db.blocks.filter(b=>b.id!==cmd.id);break}
 case 'settings':{requireAdmin(a);if([cmd.personal,cmd.physio,cmd.consultation,cmd.cancelHours].some(n=>!Number.isFinite(n)||n<=0))throw Error('Wartości muszą być większe od zera.');const r=cmd.rules||rules(db);if(Object.values(r).some(n=>!Number.isInteger(n)||n<1)||r.validWeeks<r.cycleWeeks)throw Error('Parametry muszą być dodatnimi liczbami całkowitymi; ważność nie może być krótsza niż cykl.');const prices=cmd.packagePrices||db.settings.packagePrices;if(prices&&['personal','physio'].some(s=>[1,2,3].some(i=>!Number.isFinite(prices[s]?.[i])||prices[s][i]<=0)))throw Error('Uzupełnij wszystkie ceny pakietów.');db.settings={...db.settings,personal:cmd.personal,physio:cmd.physio,consultation:cmd.consultation,cancelHours:cmd.cancelHours,rules:r,packagePrices:prices};audit(db,'Zmieniono cennik i zasady dla nowych operacji');break}
 case 'rate':{requireAdmin(a);if(!Number.isFinite(cmd.rate)||cmd.rate<=0)throw Error('Podaj poprawną stawkę.');const t=db.trainers.find(t=>t.id===cmd.trainerId)!;t.rates??=[{from:'2000-01-01',rate:t.rate}];t.rates=t.rates.filter(r=>r.from!==dateOf(new Date(db.now)));t.rates.push({from:dateOf(new Date(db.now)),rate:cmd.rate});t.rate=cmd.rate;audit(db,'Zmieniono stawkę trenera; naliczone sesje bez zmian');break}
 case 'read':{const m=db.messages.find(m=>m.id===cmd.id);if(m)m.read=true;break}
 case 'clock':{db.now=new Date(+now+cmd.hours*3600000).toISOString();db.holds.forEach(h=>{if(h.status==='active'&&h.expires<=db.now){h.status='expired';notify(db,'Rezerwacja wstępna wygasła','Nieopłacone terminy wróciły do puli.',h.clientId)}});break}
 }
 return db;
}
export function seed():State {
 const names=['Anna Kowalska','Piotr Zieliński','Marta Nowak','Aleksandra Mazur','Michał Dąbrowski','Ewa Wójcik','Krzysztof Baran','Natalia Król'];
 const slots=[[{day:0,hour:9},{day:3,hour:9}],[{day:0,hour:10},{day:2,hour:10}],[{day:0,hour:11},{day:3,hour:11}],[{day:0,hour:18},{day:2,hour:18}],[{day:0,hour:19},{day:3,hour:19}],[{day:1,hour:9},{day:4,hour:9}],[{day:1,hour:11},{day:4,hour:11}],[{day:2,hour:9},{day:4,hour:10}]];
 const db:State={version:1,now:'2026-10-19T08:30:00.000Z',clients:[],trainers:[{id:'t1',name:'Kamil Nowak',specialty:'Trening personalny',rate:55,days:[0,1,2,3,4,5],hours:[8,9,10,11,12,16,17,18,19,20]},{id:'t2',name:'Aleksandra Lis',specialty:'Fizjoterapia i ruch',rate:65,days:[0,1,2,3,4,5],hours:[8,9,10,11,12,16,17,18,19,20]}],sessions:[],packages:[],holds:[],messages:[],sales:[],substitutions:[],audit:[],blocks:[],settings:{personal:150,physio:180,consultation:145,cancelHours:24}};
 names.forEach((name,i)=>{const id=`c${i+1}`,pid=`p${i+1}`;const c:Client={id,name,email:`${name.split(' ')[0].toLowerCase()}@przyklad.pl`,phone:`500 120 ${230+i}`,trainerId:'t1',active:true,invited:true,service:i===2?'physio':'personal',intensity:2,prescribed:true,answers:['Lepsza kondycja i regularność','Dwa razy w tygodniu','Rano lub po pracy']};db.clients.push(c);db.packages.push({id:pid,clientId:id,count:8,start:'2026-10-05',cycleEnd:'2026-11-02',validUntil:'2026-11-16',protectionUntil:'2026-11-03',slots:slots[i],service:c.service,intensity:2,price:db.settings[c.service]*8});slots[i].forEach(slot=>{for(let w=0;w<4;w++){const date=dayAdd('2026-10-05',slot.day+7*w),past=+at(date,slot.hour)+3600000<+new Date(db.now);db.sessions.push({id:`s${i}-${slot.day}-${w}`,clientId:id,trainerId:'t1',packageId:pid,date,hour:slot.hour,kind:'training',status:past?'completed':'scheduled',publicNote:past?'Praca nad stabilizacją i siłą. Dobra kontrola ruchu, stopniowo zwiększamy obciążenie. Kolejny krok: utrzymanie tempa i regularny oddech.':'',privateNote:past?'Zwrócić uwagę na ustawienie kolan w przysiadzie. Następna sesja: progresja obciążenia o 2 kg.':'',comments:past&&i===0?[{id:`comment-${w}`,author:name,text:'Dzięki za trening! Czuję, że mam coraz więcej energii.',at:db.now}]:[],earned:past?55:undefined,rate:past?55:undefined})}});db.sales.push({id:`sale${i}`,clientId:id,label:`${serviceName(c.service)} · 8 treningów`,amount:db.settings[c.service]*8,date:'2026-10-04T12:00:00.000Z',status:'paid'})});
 db.clients.push({id:'c9',name:'Julia Wiśniewska',email:'julia@przyklad.pl',phone:'500 130 246',trainerId:'t1',active:false,invited:false,service:'personal',intensity:2,prescribed:false,answers:['Chcę wrócić do treningów','Początkująca','Dwa popołudnia w tygodniu']});
 db.sessions.push({id:'consult1',clientId:'c9',trainerId:'t1',date:'2026-10-18',hour:12,kind:'consultation',status:'completed',publicNote:'Omówiliśmy cele i plan współpracy. Rekomendacja: dwa treningi w tygodniu.',privateNote:'',comments:[],earned:82.5,rate:55});
 notify(db,'Julia czeka na aktywację','Konsultacja za nami. Przypisz produkt i pozwól Julii aktywować konto.','c9');notify(db,'Nowy komentarz Anny','„Dzięki za trening! Czuję, że mam coraz więcej energii.”','c1');notify(db,'Twój plan jest gotowy','Masz zarezerwowane stałe godziny: poniedziałek i czwartek, 9:00.','c1');
 return db;
}

export const trainingCount=(n:number)=>`${n} ${n===1?"trening":n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?"treningi":"treningów"}`;
