import React,{useState} from 'react';
import {useApp,Field} from './context';
import {Input,Select} from './controls';
import {AmountInput} from './admin-ui';
import {Client,IndividualPlan,money,serviceName} from './domain';
export function IndividualPlanEditor({client}:{client:Client}){const {db,actor,run}=useApp();const current=client.planProposal?.status==='pending'?client.planProposal:client.individualPlan;const [show,setShow]=useState(false),[plan,setPlan]=useState({service:current?.service||client.service,intensity:current?.intensity||client.intensity,cycleWeeks:current?.cycleWeeks||4,validWeeks:current?.validWeeks||6,price:current?.price||1200});return <section className="individual-plan inset spaced"><h3>Pakiet indywidualny</h3>{client.individualPlan&&<p>{client.individualPlan.intensity}× tygodniowo · {client.individualPlan.cycleWeeks} tygodni · {money(client.individualPlan.price)}<small>Warunki kolejnego zakupu. Kupione pakiety pozostają bez zmian.</small></p>}{client.planProposal&&<p className="alert">{client.planProposal.status==='pending'?'Propozycja czeka na akceptację administratora.':'Propozycja została odrzucona. Możesz przygotować nową.'}</p>}{!show?<button className="button secondary" onClick={()=>setShow(true)}>{current?'Zmień propozycję':'Ustal indywidualny pakiet'}</button>:<div className="plan-editor"><Field label="Produkt"><Select disabled={client.prescribed} value={plan.service} onChange={e=>setPlan({...plan,service:e.target.value as any})}>{(db.trainers.find(t=>t.id===client.trainerId)?.products||[]).map(s=><option value={s} key={s}>{serviceName(s)}</option>)}</Select></Field><div className="form-grid"><Field label="Treningi w tygodniu"><Select value={plan.intensity} onChange={e=>setPlan({...plan,intensity:Number(e.target.value)})}>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n}× tygodniowo</option>)}</Select></Field><Field label="Cykl (tygodnie)"><Input type="number" min={1} max={52} value={plan.cycleWeeks} onChange={e=>setPlan({...plan,cycleWeeks:Number(e.target.value)})}/></Field><Field label="Ważność (tygodnie)"><Input type="number" min={plan.cycleWeeks} max={104} value={plan.validWeeks} onChange={e=>setPlan({...plan,validWeeks:Number(e.target.value)})}/></Field>{actor.role==='admin'&&<Field label="Cena całego pakietu"><AmountInput value={plan.price} onChange={price=>setPlan({...plan,price})}/></Field>}</div><p><strong>{plan.intensity*plan.cycleWeeks} treningów</strong>{actor.role==='admin'?' · promocje naliczane przy zakupie.':' · cenę ustali administrator przy zatwierdzaniu.'}</p><button className="button primary" onClick={async()=>{if(await run({type:'individualPlan',clientId:client.id,plan:actor.role==='admin'?plan:{service:plan.service,intensity:plan.intensity,cycleWeeks:plan.cycleWeeks,validWeeks:plan.validWeeks}},actor.role==='admin'?'Zatwierdzono warunki następnego pakietu.':'Propozycja przesłana administratorowi.'))setShow(false)}}>{actor.role==='admin'?'Zatwierdź warunki':'Prześlij do akceptacji'}</button></div>}{actor.role==='admin'&&client.planProposal?.status==='pending'&&<Approval client={client}/>}</section>}
function Approval({client}:{client:Client}){const {run}=useApp();const p=client.planProposal!;const [price,setPrice]=useState(0);return <div className="plan-approval"><p>{serviceName(p.service)} · {p.intensity}× tygodniowo · cykl {p.cycleWeeks} tyg. · ważność {p.validWeeks} tyg.</p><strong>{p.intensity*p.cycleWeeks} wejść</strong><Field label="Cena pakietu do zatwierdzenia"><AmountInput value={price} onChange={setPrice}/></Field><div className="session-actions"><button className="button primary" onClick={()=>run({type:'reviewPlan',clientId:client.id,approve:true,price},'Pakiet zatwierdzony.')}>Ustal cenę i zaakceptuj</button><button className="button secondary" onClick={()=>run({type:'reviewPlan',clientId:client.id,approve:false},'Propozycja odrzucona.')}>Odrzuć</button></div></div>}
export function IndividualApprovals(){const {db,open}=useApp();const list=db.clients.filter(c=>c.planProposal?.status==='pending');return list.length?<section className="card pad spaced"><h2>Pakiety indywidualne do akceptacji <span className="number-badge">{list.length}</span></h2>{list.map(c=><div className="approval-row" key={c.id}><button className="text-button" onClick={()=>open({type:'client',id:c.id})}>{c.name}</button><Approval client={c}/></div>)}</section>:null}
export function IgnoreLimits({value,onChange}:{value:boolean;onChange:(v:boolean)=>void}){const {actor}=useApp();return actor.role==='admin'||actor.role==='trainer'?<div className={'ignore-limits '+(value?'enabled':'')}><label><Input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>Ignoruj limit dzienny i tygodniowy</label>{value&&<small>Zajętość trenera, liczba wejść i ważność pakietu nadal obowiązują.</small>}</div>:null}
