import React,{useEffect,useRef,useState} from 'react';
import {Archive,Trash2,Clock,X} from 'lucide-react';
import {Field,useApp} from './context';
import {Input,Select} from './controls';
import type {createOnlineClient,OnlineState} from './online';
import {localClockValue} from './test-clock';
export function RemoveAccount({id}:{id:string}){
 const {db,adminTool,open}=useApp();const a=db.accounts.find(a=>a.id===id),person=a?.role==='trainer'?db.trainers.find(t=>t.id===a.trainerId):db.clients.find(c=>c.id===a?.clientId);
 const [mode,setMode]=useState<'archive'|'purge'>('archive'),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!a||!person)return <p>Konto nie jest dostępne.</p>;
 const blocked=a.role==='trainer'&&db.clients.some(c=>!c.archived&&c.trainerId===a.trainerId);
 return <><h2>Usuń {a.role==='trainer'?'trenera':'klienta'}</h2><p className="spaced">{person.name}</p><div className="removal-options">{(['archive','purge'] as const).map(m=><button key={m} className={'removal-option '+(m===mode?'selected':'')} aria-pressed={m===mode} onClick={()=>{setMode(m);setConfirm('')}}>{m==='archive'?<Archive size={22}/>:<Trash2 size={22}/>}<span><strong>{m==='archive'?'Zachowaj historię':'Usuń trwale'}</strong><small>{m==='archive'?'Konto zostanie zablokowane i zniknie z bieżących list. Historia pozostanie w dzienniku.':'Konto, profil, zdjęcie, wiadomości i powiązana historia zostaną bezpowrotnie usunięte.'}</small></span></button>)}</div><p className="hint spaced">{a.role==='client'?'Przyszłe wizyty i rezerwacje klienta zostaną zwolnione.':'Trener nie może mieć przypisanych klientów ani nierozliczonych wizyt.'}</p>{blocked&&<p className="alert">Najpierw przenieś wszystkich klientów do innego trenera.</p>}{mode==='purge'&&<Field label="Aby potwierdzić trwałe usunięcie, wpisz USUŃ"><Input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></Field>}{error&&<p className="alert" role="alert">{error}</p>}<div className="form-actions"><button className="button secondary" disabled={busy} onClick={()=>open(null)}>Anuluj</button><button className="button primary" disabled={busy||blocked||mode==='purge'&&confirm!=='USUŃ'} onClick={async()=>{setBusy(true);setError('');try{await adminTool('accountLifecycle',{accountId:id,mode,confirmation:mode==='purge'?confirm:''});open(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Usuwanie…':mode==='archive'?'Zablokuj i zachowaj historię':'Usuń bezpowrotnie'}</button></div></>;
}
export function AdminTools({online,receive}:{online:ReturnType<typeof createOnlineClient>;receive:(r:OnlineState)=>void}){
 const {db}=useApp();const [visible,setVisible]=useState(false),[value,setValue]=useState(''),[initial,setInitial]=useState(''),[discard,setDiscard]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.code==='KeyY'){e.preventDefault();if(document.querySelector('dialog[open]'))return;const v=localClockValue(db.now);setValue(v);setInitial(v);setError('');setDiscard(false);setVisible(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[db.now]);
 useEffect(()=>{if(visible)ref.current?.showModal()},[visible]);const close=()=>{if(busy)return;if(value!==initial)setDiscard(true);else setVisible(false)};
 const save=async(reset=false)=>{setBusy(true);setError('');try{receive(await online.adminTool('testClock',{target:reset?null:new Date(value).toISOString()}));setVisible(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!visible)return null;return <dialog ref={ref} className="dialog" onCancel={e=>{e.preventDefault();close()}}><div className="dialog-inner"><button className="dialog-close" aria-label="Zamknij" onClick={close}><X size={20}/></button><h2><Clock size={22}/> Czas testowy</h2><p className="spaced">Zmiana obejmie wszystkich użytkowników ACO!. Czas będzie dalej płynął z ustawionym przesunięciem.</p><p className="hint">Logowanie i zabezpieczenia działają według czasu rzeczywistego. Cofnięcie czasu nie cofnie zapisanych operacji.</p><form onSubmit={e=>{e.preventDefault();void save()}}><Field label="Data"><Input type="date" required value={value.slice(0,10)} onChange={e=>setValue(e.target.value+value.slice(10))}/></Field><div className="form-grid"><Field label="Godzina"><Select value={value.slice(11,13)} onChange={e=>setValue(value.slice(0,11)+e.target.value+value.slice(13))}>{Array.from({length:24},(_,i)=>String(i).padStart(2,'0')).map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Minuta"><Select value={value.slice(14,16)} onChange={e=>setValue(value.slice(0,14)+e.target.value)}>{Array.from({length:60},(_,i)=>String(i).padStart(2,'0')).map(x=><option key={x}>{x}</option>)}</Select></Field></div><p className="hint">Strefa: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Przesunięcie: {Math.round((db.timeOffsetSeconds||0)/60)} min.</p>{error&&<p className="alert" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>save(true)}>Przywróć rzeczywisty czas</button><button className="button primary" disabled={busy}>Ustaw dla wszystkich</button></div></form>{discard&&<div className="unsaved-confirm"><p>Odrzucić niezapisaną zmianę czasu?</p><button className="button secondary" onClick={()=>setDiscard(false)}>Wróć</button><button className="button primary" onClick={()=>setVisible(false)}>Odrzuć</button></div>}</div></dialog>;
}
