import {Database,Account,actorFor} from './auth';
import {Actor,Command,uid,available,at,dayIndex} from './domain';
export const accountOf=(db:Database,a:Actor)=>db.accounts.find(x=>!x.disabled&&x.role===a.role&&(a.role==='admin'||a.role==='trainer'&&x.trainerId===a.trainerId||a.role==='client'&&x.clientId===a.clientId));
export const accountName=(db:Database,a:Account)=>a.role==='admin'?(a.name||'Administrator ACO!'):a.role==='trainer'?db.trainers.find(t=>t.id===a.trainerId)?.name||'Były trener':db.clients.find(c=>c.id===a.clientId)?.name||'Klient';
export function recipients(db:Database,a:Actor){return db.accounts.filter(x=>!x.disabled&&x.id!==accountOf(db,a)?.id&&(a.role==='admin'||x.role==='admin'||a.role==='trainer'&&x.role==='client'&&db.clients.some(c=>c.id===x.clientId&&c.trainerId===a.trainerId)||a.role==='client'&&x.role==='trainer'&&db.clients.some(c=>c.id===a.clientId&&c.trainerId===x.trainerId)))}
export function notifications(db:Database,a:Actor){const existing=db.messages.filter(m=>a.role==='admin'?m.target==='admin':m.target!=='admin'&&(a.role==='client'?m.clientId===a.clientId:m.target!=='client'&&m.title!=='Możesz aktywować konto'&&!!m.clientId&&db.clients.some(c=>c.id===m.clientId&&c.trainerId===a.trainerId)));if(a.role!=='admin')return existing;return [...db.clients.filter(c=>!c.active).map(c=>({id:'activation-'+c.id,title:c.invited?'Klient nie aktywował konta':'Klient czeka na zatwierdzenie',body:`${c.name} · trener: ${db.trainers.find(t=>t.id===c.trainerId)?.name||'—'}`,at:db.now,read:false,target:'admin' as const})),...db.holds.filter(h=>h.status!=='paid').map(h=>({id:'payment-'+h.id,title:h.expires<=db.now?'Upłynął termin płatności':'Rezerwacja oczekuje na płatność',body:`${db.clients.find(c=>c.id===h.clientId)?.name} · termin: ${new Date(h.expires).toLocaleString('pl-PL')}`,at:h.expires,read:false,target:'admin' as const})),...existing]}
export function manage(source:Database,a:Actor,cmd:Command){const db=structuredClone(source),me=accountOf(db,a);if(!me)throw Error('Zaloguj się.');if(cmd.type==='updateProfile'){const email=cmd.email.trim().toLowerCase();if(!cmd.name.trim()||!/^\S+@\S+\.\S+$/.test(email))throw Error('Podaj imię, nazwisko i poprawny e-mail.');if(db.accounts.some(x=>x.id!==me.id&&x.email===email)||db.clients.some(c=>c.id!==me.clientId&&c.email.toLowerCase()===email))throw Error('Ten e-mail jest używany przez inne konto.');if(cmd.photo&&(!/^data:image\/(png|jpeg|webp);base64,/.test(cmd.photo)||cmd.photo.length>2900000))throw Error('Nieprawidłowy plik zdjęcia.');me.email=email;me.name=cmd.name.trim();me.phone=cmd.phone.trim();me.photo=cmd.photo;const person=a.role==='trainer'?db.trainers.find(t=>t.id===a.trainerId):a.role==='client'?db.clients.find(c=>c.id===a.clientId):undefined;if(person){person.name=me.name;person.phone=me.phone;person.photo=me.photo;if('email' in person)person.email=email}db.audit.unshift({id:uid(),at:db.now,text:'Zaktualizowano własny profil'});return db}if(cmd.type==='sendLetter'){const allowed=recipients(db,a);const targets=cmd.to.startsWith('group:')?allowed.filter(x=>cmd.to==='group:clients'?x.role==='client':a.role==='admin'&&(cmd.to==='group:all'||cmd.to==='group:trainers'&&x.role==='trainer')):allowed.filter(x=>x.id===cmd.to);if(!targets.length)throw Error('Brak uprawnionych odbiorców.');if(!cmd.subject.trim()||!cmd.body.trim())throw Error('Wpisz temat i treść.');for(const to of targets)(db.letters??=[]).unshift({id:uid(),from:me.id,to:to.id,fromName:accountName(db,me),toName:accountName(db,to),subject:cmd.subject.trim(),body:cmd.body.trim(),at:db.now,read:false});return db}
 if(cmd.type==='readLetter'){const m=db.letters?.find(m=>m.id===cmd.id&&m.to===me.id);if(!m)throw Error('Brak dostępu.');m.read=true;return db}
 if(cmd.type==='readNotice'){if(!notifications(db,a).some(n=>n.id===cmd.id))throw Error('Brak dostępu.');db.noticeReads??={};db.noticeReads[me.id]=[...new Set([...(db.noticeReads[me.id]||[]),cmd.id])];return db}
 if(a.role!=='admin')throw Error('Tylko administrator może wykonać tę operację.');
 if(cmd.type==='birthDate'){const c=db.clients.find(c=>c.id===cmd.id);if(!c||!/^\d{4}-\d{2}-\d{2}$/.test(cmd.value)||cmd.value<'1900-01-01'||cmd.value>db.now.slice(0,10)||new Date(cmd.value+'T12:00:00Z').toISOString().slice(0,10)!==cmd.value)throw Error('Podaj poprawną datę urodzenia.');c.birthDate=cmd.value}
 else if(cmd.type==='deleteTrainer'){const t=db.trainers.find(t=>t.id===cmd.id&&!t.deleted);if(!t)throw Error('Nie znaleziono trenera.');if(db.clients.some(c=>c.trainerId===t.id))throw Error('Trener ma klientów. Najpierw przypisz ich innemu prowadzącemu.');if(db.sessions.some(s=>s.trainerId===t.id&&s.status==='scheduled')||db.holds.some(h=>h.trainerId===t.id&&h.status==='active'&&h.expires>db.now))throw Error('Trener ma nierozliczone wizyty lub rezerwacje. Najpierw je rozlicz albo przekaż innemu trenerowi.');t.deleted=true;db.accounts.filter(a=>a.trainerId===t.id).forEach(a=>a.disabled=true)}
 else if(cmd.type==='transferClient'){const c=db.clients.find(c=>c.id===cmd.clientId),t=db.trainers.find(t=>t.id===cmd.trainerId&&!t.deleted);if(!c||!t||c.trainerId===t.id)throw Error('Wybierz innego trenera prowadzącego.');if(c.prescribed&&t.products&&!t.products.includes(c.service))throw Error('Nowy trener nie prowadzi produktu klienta.');const old=c.trainerId;const sessions=db.sessions.filter(s=>s.clientId===c.id&&s.trainerId===old&&s.status==='scheduled'&&at(s.date,s.hour)>new Date(db.now));const holds=db.holds.filter(h=>h.clientId===c.id&&h.status==='active'&&h.expires>db.now);for(const s of sessions){if(!available(db,t.id,s.date,s.hour,c.id,s.id)||s.kind==='consultation'&&!available(db,t.id,s.date,s.hour+1,c.id,s.id))throw Error(`Nowy trener ma zajęty termin ${s.date} ${s.hour}:00.`)}for(const h of holds)for(const d of h.dates)if(!available(db,t.id,d.date,d.hour,c.id,undefined,h.id))throw Error('Nowy trener ma kolizję z rezerwacją klienta.');c.trainerId=t.id;sessions.forEach(s=>s.trainerId=t.id);holds.forEach(h=>h.trainerId=t.id)}
 else throw Error('Nieznana operacja.');db.audit.unshift({id:uid(),at:db.now,text:cmd.type==='transferClient'?'Zmieniono trenera prowadzącego klienta':cmd.type==='deleteTrainer'?'Usunięto trenera z zespołu':'Uzupełniono datę urodzenia klienta'});return db}
export const managementTypes=['updateProfile','transferClient','deleteTrainer','birthDate','sendLetter','readLetter','readNotice'];
