import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDatabase,addTrainer,registerAccount,actorFor,authenticate,TrainerInput} from './auth';
import {manage,recipients,notifications} from './management';
import {dayAdd,execute} from './domain';
const input:TrainerInput={name:'A',email:'a@example.test',products:['personal','physio'],productRates:{personal:100,physio:150},days:[0,1,2,3,4,5,6],hours:[8,9,10,11,12],password:'Password!2026',phone:'',pesel:'',student:false,address:'',taxOffice:'',photo:''};
async function fixture(){let db=await initialDatabase();const admin=actorFor(db.accounts[0]);db=await addTrainer(db,admin,input);db=await addTrainer(db,admin,{...input,name:'B',email:'b@example.test'});for(const a of db.accounts.filter(a=>a.role==='trainer'))db=execute(db,admin,{type:'availability',trainerId:a.trainerId,days:input.days,hours:input.hours}) as typeof db;db=(await registerAccount(db,{type:'register',name:'Client',email:'client@example.test',phone:'500',birthDate:'1990-01-01',trainerId:db.trainers[0].id,date:dayAdd(db.now.slice(0,10),1),hour:10,answers:[]})).db;return {db,admin,first:actorFor(db.accounts[1]),second:actorFor(db.accounts[2]),client:actorFor(db.accounts[3])}}
test('Przeniesienie zachowuje prowadzącego, sprawdza kolizje; usunięcie blokuje klientów',async()=>{let {db,admin,first,second}=await fixture();assert.throws(()=>manage(db,admin,{type:'deleteTrainer',id:first.trainerId}));assert.throws(()=>manage(db,first,{type:'transferClient',clientId:db.clients[0].id,trainerId:second.trainerId}));assert.throws(()=>manage(db,admin,{type:'transferClient',clientId:db.clients[0].id,trainerId:'missing'}));const blocked=structuredClone(db);blocked.blocks.push({id:'x',trainerId:second.trainerId,date:db.sessions[0].date,hour:10});assert.throws(()=>manage(blocked,admin,{type:'transferClient',clientId:db.clients[0].id,trainerId:second.trainerId}));db=manage(db,admin,{type:'transferClient',clientId:db.clients[0].id,trainerId:second.trainerId});assert.equal(db.sessions[0].trainerId,second.trainerId);db=manage(db,admin,{type:'deleteTrainer',id:first.trainerId});assert.equal(db.trainers[0].deleted,true);await assert.rejects(authenticate(db,input.email,input.password))});
test('Korespondencja: odbiorcy według roli, prywatność i historia po transferze',async()=>{let {db,admin,first,second,client}=await fixture();assert.equal(recipients(db,first).length,2);assert.equal(recipients(db,client).length,2);assert.throws(()=>manage(db,second,{type:'sendLetter',to:db.accounts[3].id,subject:'X',body:'Y'}));db=manage(db,first,{type:'sendLetter',to:db.accounts[3].id,subject:'Plan',body:'Wiadomość'});const letter=db.letters![0];assert.throws(()=>manage(db,second,{type:'readLetter',id:letter.id}));db=manage(db,admin,{type:'transferClient',clientId:db.clients[0].id,trainerId:second.trainerId});assert.equal(db.letters![0].fromName,'A');assert.ok(!recipients(db,first).some(a=>a.clientId===client.clientId));assert.ok(recipients(db,second).some(a=>a.clientId===client.clientId));db=manage(db,client,{type:'readLetter',id:letter.id});assert.equal(db.letters![0].read,true)});
test('Administrator widzi powiadomienia zarządcze; stawka zależy od produktu',async()=>{let {db,admin,first,client}=await fixture();db=execute(db,first,{type:'notes',id:db.sessions[0].id,publicNote:'Uwagi',privateNote:'Poufne'}) as typeof db;assert.ok(notifications(db,admin).some(n=>n.title==='Trener dodał notatkę'));assert.ok(!notifications(db,client).some(n=>n.title==='Trener dodał notatkę'));assert.ok(!notifications(db,admin).some(n=>n.title==='Konsultacja zarezerwowana'));db.clients[0].service='physio';db.now=dayAdd(db.sessions[0].date,1)+'T12:00:00.000Z';db=execute(db,first,{type:'outcome',id:db.sessions[0].id,status:'completed'}) as typeof db;assert.equal(db.sessions[0].earned,225)});
test('Dostępność ustawia administrator; edycja danych trenera zachowuje grafik',async()=>{let db=await initialDatabase();const admin=actorFor(db.accounts[0]);db=await addTrainer(db,admin,input);assert.deepEqual(db.trainers[0].days,[]);assert.deepEqual(db.trainers[0].hours,[]);assert.throws(()=>execute(db,actorFor(db.accounts[1]),{type:'availability',trainerId:db.trainers[0].id,days:[0],hours:[10]}));const trainer=actorFor(db.accounts[1]);db=execute(db,admin,{type:'availability',trainerId:trainer.trainerId,days:[0,1],hours:[9,10,11]}) as typeof db;db=await addTrainer(db,admin,{...input,id:db.trainers[0].id,password:'',days:[6],hours:[22]});assert.deepEqual(db.trainers[0].days,[0,1]);assert.deepEqual(db.trainers[0].hours,[9,10,11])});
test('Zmiana dostępności nie porzuca zarezerwowanej konsultacji',async()=>{const {db,admin,first}=await fixture();assert.throws(()=>execute(db,admin,{type:'availability',trainerId:first.trainerId,days:[0,1,2,3,4,5,6],hours:[8,9]}))});
test('Edycja własnego profilu synchronizuje kontakt i chroni unikalność loginu',async()=>{let {db,admin,first,client}=await fixture();assert.throws(()=>manage(db,first,{type:'updateProfile',name:'Nowy',email:db.accounts[0].email,phone:'123',photo:''}));db=manage(db,first,{type:'updateProfile',name:'Nowy trener',email:'new@example.test',phone:'123',photo:''});assert.equal(db.trainers[0].name,'Nowy trener');assert.equal(db.trainers[0].phone,'123');assert.equal((await authenticate(db,'new@example.test',input.password)).role,'trainer');await assert.rejects(authenticate(db,input.email,input.password));db=manage(db,client,{type:'updateProfile',name:'Klient Nowy',email:'client-new@example.test',phone:'456',photo:''});assert.equal(db.clients[0].email,'client-new@example.test');assert.equal(db.clients[0].trainerId,first.trainerId);assert.equal(db.clients[0].active,false);assert.throws(()=>manage(db,admin,{type:'updateProfile',name:'Admin',email:'admin@example.test',phone:'',photo:'https://example.test/photo.png'}))});
test('Dostępność rozróżnia dni tygodnia i chroni istniejące rezerwacje',async()=>{const {available,dayIndex}=await import('./domain');let {db,admin,first}=await fixture();const date=db.sessions[0].date,day=dayIndex(date);const weeklyHours=Object.fromEntries(Array.from({length:7},(_,i)=>[i,i===day?[10,11]:[14,15]]));db=execute(db,admin,{type:'availability',trainerId:first.trainerId,days:[0,1,2,3,4,5,6],hours:[10,11,14,15],weeklyHours}) as typeof db;const same=dayAdd(date,7),other=dayAdd(date,1);assert.equal(available(db,first.trainerId!,same,10),true);assert.equal(available(db,first.trainerId!,same,14),false);assert.equal(available(db,first.trainerId!,other,10),false);assert.equal(available(db,first.trainerId!,other,14),true);assert.equal(available(db,first.trainerId!,other,16),false);assert.throws(()=>execute(db,admin,{type:'availability',trainerId:first.trainerId,days:[day],hours:[10],weeklyHours:{[day]:[10]}}))});
test('Kilka zakresów zachowuje przerwy w dostępności',async()=>{const {available,dayIndex}=await import('./domain');let {db,admin,first}=await fixture();const date=dayAdd(db.sessions[0].date,7),day=dayIndex(date);db=execute(db,admin,{type:'availability',trainerId:first.trainerId,days:[day],hours:[8,10,11,16,17],weeklyHours:{[day]:[8,10,11,16,17]}}) as typeof db;for(const h of [8,10,11,16,17])assert.equal(available(db,first.trainerId!,date,h),true);for(const h of [9,12,15,18])assert.equal(available(db,first.trainerId!,date,h),false)});
test('Wysyłka do grupy respektuje przypisanie klientów i nie ujawnia innych odbiorców',async()=>{let {db,admin,first,second,client}=await fixture();assert.throws(()=>manage(db,second,{type:'sendLetter',to:'group:clients',subject:'A',body:'B'}));assert.throws(()=>manage(db,client,{type:'sendLetter',to:'group:all',subject:'A',body:'B'}));db=manage(db,first,{type:'sendLetter',to:'group:clients',subject:'Plan',body:'Zmiana'});assert.equal(db.letters!.length,1);assert.equal(db.letters![0].to,db.accounts[3].id);db=manage(db,admin,{type:'sendLetter',to:'group:trainers',subject:'Zespół',body:'Spotkanie'});assert.equal(db.letters!.length,3);assert.equal(new Set(db.letters!.slice(0,2).map(m=>m.to)).size,2)});

test('Powiadomienie aktywacyjne otrzymuje klient, a nie prowadzący',async()=>{let {db,admin,first,client}=await fixture();db=execute(db,admin,{type:'activate',id:db.clients[0].id,service:'personal',intensity:1}) as typeof db;assert.ok(notifications(db,client).some(n=>n.title==='Możesz aktywować konto'));assert.ok(!notifications(db,first).some(n=>n.title==='Możesz aktywować konto'));});
