import {dateOf} from './domain';
import {Database,Account,actorFor} from './auth';
import {Actor,Command,Message,uid,available,at,dayIndex} from './domain';
export const accountOf=(db:Database,a:Actor)=>db.accounts.find(x=>!x.disabled&&x.role===a.role&&(a.role==='admin'||a.role==='trainer'&&x.trainerId===a.trainerId||a.role==='client'&&x.clientId===a.clientId));
export const accountName=(db:Database,a:Account)=>a.role==='admin'?(a.name||'Administrator ACO!'):a.role==='trainer'?db.trainers.find(t=>t.id===a.trainerId)?.name||'Były trener':db.clients.find(c=>c.id===a.clientId)?.name||'Klient';
export function recipients(db:Database,a:Actor){return db.accounts.filter(x=>!x.disabled&&x.id!==accountOf(db,a)?.id&&(a.role==='admin'||x.role==='admin'||a.role==='trainer'&&x.role==='client'&&db.clients.some(c=>c.id===x.clientId&&c.trainerId===a.trainerId)||a.role==='client'&&x.role==='trainer'&&db.clients.some(c=>c.id===a.clientId&&c.trainerId===x.trainerId)))}
function notificationForRole(db:Database,a:Actor,m:Message):Message {
 const name=db.clients.find(c=>c.id===m.clientId)?.name||'Klient';
 const detail=m.body.startsWith(name+' · ')?m.body.slice(name.length+3):m.body;
 if(a.role==='client')return {...m,body:detail};
 const titles:Record<string,string>={
  'Twój plan jest gotowy':'Plan treningowy klienta jest gotowy',
  'Twój pakiet jest aktywny':'Klient opłacił pakiet',
  'Witamy w ACO!':'Klient aktywował konto',
  'Witaj w ACO!':'Klient aktywował konto',
  'Terminy czekają na opłacenie':'Oczekujemy na płatność klienta',
  'Rezerwacja wstępna wygasła':'Nieopłacona rezerwacja klienta wygasła',
  'Konsultacja zarezerwowana':'Nowa konsultacja klienta',
  'Zatwierdzono pakiet indywidualny':'Administrator zatwierdził pakiet klienta',
  'Odrzucono propozycję pakietu':'Administrator odrzucił propozycję pakietu',
  'Umówiono trening':'Umówiono trening klienta',
  'Zmieniono termin treningu':'Zmieniono termin treningu klienta',
  'Zmieniono konsultację':'Zmieniono termin konsultacji klienta',
  'Zmieniono ważność pakietu':'Zmieniono ważność pakietu klienta'
 };
 const bodies:Record<string,string>={
  'Witamy w ACO!':'Konto klienta jest aktywne. Klient może wybrać terminy i kupić pakiet.',
  'Witaj w ACO!':'Konto klienta jest aktywne. Klient może wybrać terminy i kupić pakiet.',
  'Konsultacja zarezerwowana':detail.split('Aktywacja nastąpi')[0]+'Po konsultacji dobierz produkt i zatwierdź aktywację konta klienta.'
 };
 const body=bodies[m.title]||detail.replace('Masz zarezerwowane stałe godziny:','Stałe godziny klienta:').replace('Wejście jest dostępne do ponownego umówienia.','Klient ma wolne wejście do ponownego umówienia.');
 return {...m,title:titles[m.title]||m.title,body:name+' · '+body};
}
export function notifications(db:Database,a:Actor){const welcome=db.messages.findIndex(m=>m.clientId===a.clientId&&['Witaj w ACO!','Witamy w ACO!'].includes(m.title));if(a.role==='client'&&!db.clients.some(c=>c.id===a.clientId&&c.active))return [];const existing=db.messages.filter((m,index)=>a.role==='admin'?m.target==='admin':m.target!=='admin'&&(a.role==='client'?m.target!=='staff'&&m.clientId===a.clientId&&welcome>=0&&index<=welcome:m.target!=='client'&&m.title!=='Możesz aktywować konto'&&!!m.clientId&&db.clients.some(c=>c.id===m.clientId&&c.trainerId===a.trainerId)));if(a.role!=='admin')return existing.map(m=>notificationForRole(db,a,m));return [...db.clients.filter(c=>!c.active).map(c=>({id:'activation-'+c.id,title:c.invited?'Klient nie aktywował konta':'Klient czeka na zatwierdzenie',body:`${c.name} · trener: ${db.trainers.find(t=>t.id===c.trainerId)?.name||'-'}`,at:db.now,read:false,target:'admin' as const})),...db.holds.filter(h=>h.status!=='paid').map(h=>({id:'payment-'+h.id,title:h.expires<=db.now?'Upłynął termin płatności':'Rezerwacja oczekuje na płatność',body:`${db.clients.find(c=>c.id===h.clientId)?.name} · termin: ${new Date(h.expires).toLocaleString('pl-PL')}`,at:h.expires,read:false,target:'admin' as const})),...existing.map(m=>notificationForRole(db,a,m))]}
export function manage(source:Database,a:Actor,cmd:Command){const db=structuredClone(source),me=accountOf(db,a);if(!me)throw Error('Zaloguj się.');if(cmd.type==='updateProfile'){if(a.role==='trainer')throw Error('Dane trenera może zmieniać tylko administrator.');const email=cmd.email.trim().toLowerCase();if(!cmd.name.trim()||!/^\S+@\S+\.\S+$/.test(email))throw Error('Podaj imię, nazwisko i poprawny e-mail.');if(db.accounts.some(x=>x.id!==me.id&&x.email===email)||db.clients.some(c=>c.id!==me.clientId&&c.email.toLowerCase()===email))throw Error('Ten e-mail jest używany przez inne konto.');if(cmd.photo&&(!/^data:image\/(png|jpeg|webp);base64,/.test(cmd.photo)||cmd.photo.length>2900000))throw Error('Nieprawidłowy plik zdjęcia.');me.email=email;me.name=cmd.name.trim();me.phone=cmd.phone.trim();me.photo=cmd.photo;const person=a.role==='client'?db.clients.find(c=>c.id===a.clientId):undefined;if(person){person.name=me.name;person.phone=me.phone;person.photo=me.photo;if('email' in person)person.email=email}db.audit.unshift({id:uid(),at:db.now,text:'Zaktualizowano własny profil'});return db}if(cmd.type==='sendLetter'){const allowed=recipients(db,a);const targets=cmd.to.startsWith('group:')?allowed.filter(x=>cmd.to==='group:clients'?x.role==='client':a.role==='admin'&&(cmd.to==='group:all'||cmd.to==='group:trainers'&&x.role==='trainer')):allowed.filter(x=>x.id===cmd.to);if(!targets.length)throw Error('Brak uprawnionych odbiorców.');if(!cmd.subject.trim()||!cmd.body.trim())throw Error('Wpisz temat i treść.');for(const to of targets)(db.letters??=[]).unshift({id:uid(),from:me.id,to:to.id,fromName:accountName(db,me),toName:accountName(db,to),subject:cmd.subject.trim(),body:cmd.body.trim(),at:db.now,read:false});return db}
 if(cmd.type==='readLetter'){const m=db.letters?.find(m=>m.id===cmd.id&&m.to===me.id);if(!m)throw Error('Brak dostępu.');m.read=cmd.read!==false;return db}
 if(cmd.type==='readNotice'){if(!notifications(db,a).some(n=>n.id===cmd.id))throw Error('Brak dostępu.');db.noticeReads??={};db.noticeReads[me.id]=cmd.read===false?(db.noticeReads[me.id]||[]).filter(id=>id!==cmd.id):[...new Set([...(db.noticeReads[me.id]||[]),cmd.id])];return db}
 if(cmd.type==='readAll'){if(cmd.folder==='received'){for(const m of db.letters||[])if(m.to===me.id)m.read=true}else{db.noticeReads??={};db.noticeReads[me.id]=[...new Set([...(db.noticeReads[me.id]||[]),...notifications(db,a).map(n=>n.id)])]}return db}
 if(a.role!=='admin')throw Error('Tylko administrator może wykonać tę operację.');
 if(cmd.type==='clientProfile'){const c=db.clients.find(c=>c.id===cmd.id);if(!c||!cmd.name.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(cmd.birthDate)||cmd.birthDate<'1900-01-01'||cmd.birthDate>dateOf(new Date(db.now))||new Date(cmd.birthDate+'T12:00:00Z').toISOString().slice(0,10)!==cmd.birthDate)throw Error('Sprawdź dane klienta.');c.name=cmd.name.trim();c.phone=cmd.phone.trim();c.birthDate=cmd.birthDate;c.answers=cmd.answers;if(cmd.photo!==undefined){if(cmd.photo&&(!/^data:image\/(png|jpeg|webp);base64,/.test(cmd.photo)||cmd.photo.length>2900000))throw Error('Nieprawidłowy plik zdjęcia.');c.photo=cmd.photo}const account=db.accounts.find(a=>a.clientId===c.id);if(account){account.name=c.name;account.phone=c.phone}db.audit.unshift({id:uid(),at:db.now,text:'Administrator poprawił dane klienta: '+c.name});return db}
 if(cmd.type==='birthDate'){const c=db.clients.find(c=>c.id===cmd.id);if(!c||!/^\d{4}-\d{2}-\d{2}$/.test(cmd.value)||cmd.value<'1900-01-01'||cmd.value>dateOf(new Date(db.now))||new Date(cmd.value+'T12:00:00Z').toISOString().slice(0,10)!==cmd.value)throw Error('Podaj poprawną datę urodzenia.');c.birthDate=cmd.value}
 else if(cmd.type==='deleteTrainer'){const t=db.trainers.find(t=>t.id===cmd.id&&!t.deleted);if(!t)throw Error('Nie znaleziono trenera.');if(db.clients.some(c=>c.trainerId===t.id))throw Error('Trener ma klientów. Najpierw przypisz ich innemu prowadzącemu.');if(db.sessions.some(s=>s.trainerId===t.id&&s.status==='scheduled')||db.holds.some(h=>h.trainerId===t.id&&h.status==='active'&&h.expires>db.now))throw Error('Trener ma nierozliczone wizyty lub rezerwacje. Najpierw je rozlicz albo przekaż innemu trenerowi.');t.deleted=true;db.accounts.filter(a=>a.trainerId===t.id).forEach(a=>a.disabled=true)}
 else if(cmd.type==='transferClient'){const c=db.clients.find(c=>c.id===cmd.clientId),t=db.trainers.find(t=>t.id===cmd.trainerId&&!t.deleted);if(!c||!t||c.trainerId===t.id)throw Error('Wybierz innego trenera prowadzącego.');if(c.prescribed&&t.products&&!t.products.includes(c.service))throw Error('Nowy trener nie prowadzi produktu klienta.');const old=c.trainerId;const sessions=db.sessions.filter(s=>s.clientId===c.id&&s.trainerId===old&&s.status==='scheduled'&&at(s.date,s.hour)>new Date(db.now));const holds=db.holds.filter(h=>h.clientId===c.id&&h.status==='active'&&h.expires>db.now);for(const s of sessions){if(!available(db,t.id,s.date,s.hour,c.id,s.id)||s.kind==='consultation'&&!available(db,t.id,s.date,s.hour+1,c.id,s.id))throw Error(`Nowy trener ma zajęty termin ${s.date} ${s.hour}:00.`)}for(const h of holds)for(const d of h.dates)if(!available(db,t.id,d.date,d.hour,c.id,undefined,h.id))throw Error('Nowy trener ma kolizję z rezerwacją klienta.');c.trainerId=t.id;sessions.forEach(s=>s.trainerId=t.id);holds.forEach(h=>h.trainerId=t.id)}
 else throw Error('Nieznana operacja.');db.audit.unshift({id:uid(),at:db.now,text:cmd.type==='transferClient'?'Zmieniono trenera prowadzącego klienta':cmd.type==='deleteTrainer'?'Usunięto trenera z zespołu':'Uzupełniono datę urodzenia klienta'});return db}
export const managementTypes=['clientProfile','updateProfile','transferClient','deleteTrainer','birthDate','sendLetter','readLetter','readNotice','readAll'];
