import React,{useState,useEffect} from 'react';
import {dayAdd,weekOf,labelDate,hourLabel} from './domain';
import {ChevronLeft,ChevronRight} from 'lucide-react';
type Entry={id:string;date:string;hour:number;kind:string;name:string};
export function MobileCalendar({week,today,focusDate,max,entries,onWeek,onDay,mode,onMode,onOpen}:{focusDate?:string;week:string;today:string;max?:string;entries:Entry[];onWeek:(v:string)=>void;onDay:(v:string)=>void;mode:string;onMode:(v:string)=>void;onOpen:(id:string)=>void}){
 const month=(focusDate||dayAdd(week,3)).slice(0,7),first=month+'-01',start=weekOf(first),count=(d:string)=>entries.filter(s=>s.date===d),pick=(d:string)=>{onWeek(weekOf(d));onDay(d);onMode('day')};
 return <div className="mobile-calendar-views"><div className="calendar-view-tabs">{[['day','Dzień'],['week','Tydzień'],['month','Miesiąc']].map(([v,l])=><button key={v} aria-pressed={mode===v} onClick={()=>onMode(v)}>{l}</button>)}</div>{mode==='month'?<><div className="mobile-month-grid">{['Pn','Wt','Śr','Cz','Pt','So','Nd'].map(d=><small key={d}>{d}</small>)}{Array.from({length:Math.ceil((Math.round((+new Date(first+'T12:00:00')-+new Date(start+'T12:00:00'))/86400000)+new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate())/7)*7},(_,i)=>dayAdd(start,i)).map(d=><button key={d} disabled={!!max&&d>max} className={(d.slice(0,7)!==month?'outside ':'')+(d===today?'today':'')} aria-label={`${labelDate(d)}: ${count(d).length} spotkań`} onClick={()=>pick(d)}><strong>{Number(d.slice(8))}</strong>{count(d).length>0&&<span>{count(d).length}<i/></span>}</button>)}</div><p className="mobile-calendar-hint">Liczba oznacza spotkania. Wybierz dzień, aby zobaczyć godziny.</p></>:mode==='week'?<div className="mobile-week-agenda">{Array.from({length:7},(_,i)=>dayAdd(week,i)).map(d=><section key={d} className={d===today?'today':''}><button className="agenda-day" disabled={!!max&&d>max} onClick={()=>pick(d)}><strong>{labelDate(d,{weekday:'short'})}<span>{labelDate(d,{day:'numeric',month:'numeric'})}</span></strong><small>{d===today?'Dzisiaj':count(d).length+' spotkań'}</small></button><div>{count(d).length?count(d).sort((a,b)=>a.hour-b.hour).map(s=><button className="agenda-session" key={s.id} onClick={()=>onOpen(s.id)}><time>{hourLabel(s.hour)}</time><span>{s.name}<small>{s.kind==='consultation'?'Konsultacja':'Trening'}</small></span></button>):<button className="agenda-empty" disabled={!!max&&d>max} onClick={()=>pick(d)}>Zobacz dzień</button>}</div></section>)}</div>:null}</div>
}

export function MonthNav({week,max,onChange,focusDate}:{focusDate?:string;week:string;max?:string;onChange:(d:string)=>void}){const month=(focusDate||dayAdd(week,3)).slice(0,7),first=month+'-01';const shift=(n:number)=>{const d=new Date(first+'T12:00:00');d.setMonth(d.getMonth()+n);onChange(weekOf(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-15'))};return <div className="week-nav mobile-month-nav"><button aria-label="Poprzedni miesiąc" onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><strong>{labelDate(first,{month:'long',year:'numeric'})}</strong><button aria-label="Następny miesiąc" disabled={!!max&&month>=max.slice(0,7)} onClick={()=>shift(1)}><ChevronRight size={18}/></button></div>}
