import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,execute,recurringOwner,available,dayAdd,rules,State,Actor} from './domain';
import {holidayName} from './holidays';
import {workSummary} from './work-summary';
const admin:Actor={role:'admin',trainerId:'t1',clientId:''},coach:Actor={...admin,role:'trainer'};
function fixture(){const db=seed();db.now='2026-10-01T06:00:00Z';db.sessions=[];db.packages=[];db.holds=[];db.blocks=[];db.clients.forEach(c=>{c.intensity=1;c.prescribed=true;c.active=true});db.trainers[0].products=['personal','physio'];db.trainers[0].days=[0,1,2,3,4,5,6];db.trainers[0].hours=[8,9,10,11,12,16];return db}
function hold(db:State,id='c1',hour=8){return execute(db,coach,{type:'hold',clientId:id,start:'2026-10-05',slots:[{day:0,hour}],dates:[0,1,2,3].map(w=>({date:dayAdd('2026-10-05',w*7),hour}))})}
test('a 12-week plan cannot acquire a protected weekly hour through exceptions',()=>{let db=hold(fixture());db=execute(db,admin,{type:'payHold',id:db.holds[0].id});db=execute(db,admin,{type:'individualPlan',clientId:'c2',plan:{service:'personal',intensity:1,cycleWeeks:12,validWeeks:14,price:2000}});assert.throws(()=>execute(db,coach,{type:'hold',clientId:'c2',start:'2026-10-05',slots:[{day:0,hour:8}],dates:Array.from({length:12},(_,w)=>({date:dayAdd('2026-10-06',w*7),hour:10}))}),/przypisana/);assert.equal(db.holds.length,1)});
test('coach holds protect recurring rights for 72 hours; expiry releases them',()=>{const db=hold(fixture());assert.equal(+new Date(db.holds[0].expires)-+new Date(db.now),72*3600000);assert.equal(recurringOwner(db,'t1',0,8,'c2'),'c1');assert.equal(available(db,'t1','2026-11-02',8,'c2'),false);db.now=db.holds[0].expires;assert.equal(recurringOwner(db,'t1',0,8,'c2'),undefined)});
test('an individual cancelled date is free but recurring ownership remains',()=>{let db=hold(fixture());db=execute(db,admin,{type:'payHold',id:db.holds[0].id});db=execute(db,coach,{type:'outcome',id:db.sessions[0].id,status:'cancelled_trainer'});assert.equal(available(db,'t1','2026-10-05',8,'c2'),true);assert.equal(recurringOwner(db,'t1',0,8,'c2'),'c1');assert.equal(db.packages[0].protectionUntil,dayAdd(db.packages[0].validUntil,rules(db).protectionDays))});
test('staff can repair recurring hours without extending the payment deadline',()=>{let db=hold(fixture());const h=db.holds[0];db=execute(db,admin,{type:'editHold',id:h.id,slots:[{day:0,hour:10}],dates:h.dates.map(d=>({...d,hour:10}))});assert.equal(db.holds[0].slots[0].hour,10);assert.equal(db.holds[0].expires,h.expires);assert.equal(recurringOwner(db,'t1',0,8,'c2'),undefined);assert.equal(recurringOwner(db,'t1',0,10,'c2'),'c1')});
test('Polish movable and fixed holidays include Christmas Eve, not regular Sundays',()=>{for(const d of ['2026-04-05','2026-04-06','2026-05-24','2026-06-04','2026-12-24','2027-03-28','2027-05-27'])assert.ok(holidayName(d),d);assert.equal(holidayName('2024-12-24'),undefined);assert.equal(holidayName('2026-10-04'),undefined)});
test('holiday override is admin-only and retained for an approved booking',()=>{const db=fixture();db.packages=[{id:'p',clientId:'c1',count:4,start:'2026-10-01',cycleEnd:'2026-12-01',validUntil:'2026-12-15',protectionUntil:'2026-12-16',slots:[],service:'personal',intensity:1,price:700}];assert.equal(available(db,'t1','2026-11-11',10,'c1'),false);assert.throws(()=>execute(db,coach,{type:'makeup',packageId:'p',date:'2026-11-11',hour:10,holidayOverride:true}),/administrator/);assert.throws(()=>execute(db,admin,{type:'makeup',packageId:'p',date:'2026-11-11',hour:10}));const next=execute(db,admin,{type:'makeup',packageId:'p',date:'2026-11-11',hour:10,holidayOverride:true});assert.equal(next.sessions[0].holidayOverride,true)});
test('weekly settlements exclude undated monthly extra hours',()=>{const db=fixture();db.extraHours=[{id:'x',trainerId:'t1',month:'2026-10',hours:2,rate:100,amount:200,description:'Spotkanie'}];assert.equal(workSummary(db,'t1','2026-10').earned,200);assert.equal(workSummary(db,'t1','2026-10-05','week').earned,0)});
test('changing an approved offer releases unpaid holds but preserves purchased packages',()=>{let db=hold(fixture());const id=db.holds[0].id;db=execute(db,admin,{type:'individualPlan',clientId:'c1',plan:{service:'personal',intensity:2,cycleWeeks:5,validWeeks:7,price:2000}});assert.equal(db.holds[0].status,'expired');assert.throws(()=>execute(db,admin,{type:'payHold',id}),/wygas|aktyw|opłac/);db=execute(db,admin,{type:'standardPlan',clientId:'c1',intensity:1});assert.equal(db.clients[0].individualPlan,undefined);assert.equal(db.clients[0].intensity,1)});
