import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDatabase} from './auth';
import {identityAccount,projectState} from '../server/access';
async function fixture(){const db=await initialDatabase();db.now='2026-09-25T12:00:00.000Z';db.accounts=[{id:'a1',role:'admin',email:'admin@example.test',password:{salt:'secret-salt',hash:'secret-hash'}},{id:'a2',role:'admin',email:'second@example.test'},{id:'t1',role:'trainer',trainerId:'t1',email:'trainer@example.test'},{id:'t2',role:'trainer',trainerId:'t2',email:'sub@example.test'},{id:'c1',role:'client',clientId:'c1',email:'client@example.test'},{id:'c2',role:'client',clientId:'c2',email:'other@example.test'}];db.trainers=['t1','t2'].map(id=>({id,name:id,days:[0],hours:[10],rate:55,pesel:'12345678901',address:'Payroll secret'}));db.clients=['c1','c2'].map((id,i)=>({id,name:id,email:id+'@example.test',phone:'123',birthDate:'1990-01-01',trainerId:i?'t2':'t1',active:true,invited:true,prescribed:true,intensity:1,service:'personal' as const,answers:['Health secret']}));db.sessions=['c1','c2'].map((id,i)=>({id:'s'+id,clientId:id,trainerId:i?'t2':'t1',date:'2026-09-24',hour:10,kind:'consultation' as const,status:'completed' as const,publicNote:'Public',privateNote:'Coaching secret '+id,comments:[],earned:82.5,rate:55}));db.letters=[{id:'m1',from:'c1',to:'t1',fromName:'Client',toName:'Trainer',subject:'Private',body:'Message secret',at:db.now,read:false}];db.noticeReads={c1:['own'],c2:['other']};return db}
test('client projection excludes other clients, coaching notes, payroll and credentials',async()=>{const db=await fixture(),view=projectState(db,'c1'),json=JSON.stringify(view);assert.deepEqual(view.clients.map(c=>c.id),['c1']);assert.equal(view.sessions[0].privateNote,'');assert.equal(view.sessions[0].earned,undefined);for(const secret of ['Coaching secret','Payroll secret','12345678901','secret-hash','secret-salt'])assert.ok(!json.includes(secret),secret);assert.deepEqual(Object.keys(view.noticeReads!),['c1']);assert.equal(view.letters?.length,1)});
test('administrator cannot read correspondence between other people',async()=>{const view=projectState(await fixture(),'a2');assert.equal(view.letters?.length,0);assert.equal(view.accounts[0].id,'a2');assert.equal(view.accounts.find(a=>a.id==='a1')?.password,undefined)});
test('former trainer sees only own historical sessions and minimal client identity',async()=>{const db=await fixture();db.clients[0].trainerId='t2';const view=projectState(db,'t1');assert.equal(view.sessions.length,1);assert.equal(view.clients[0].email,'');assert.equal(view.clients[0].birthDate,undefined);assert.deepEqual(view.clients[0].answers,[]);assert.equal(view.letters?.length,1)});
test('substitute loses client and substituted historical sessions at expiry',async()=>{const db=await fixture();db.sessions[0].trainerId='t2';db.sessions[0].substituteId='sub';db.substitutions=[{id:'sub',clientId:'c1',trainerId:'t2',until:'2026-09-25T12:00:00.001Z'}];assert.ok(projectState(db,'t2').clients.some(c=>c.id==='c1'));db.now='2026-09-25T12:00:00.001Z';const view=projectState(db,'t2');assert.ok(!view.clients.some(c=>c.id==='c1'));assert.ok(!view.sessions.some(s=>s.clientId==='c1'))});
test('disabled identity and inactive clients fail closed',async()=>{const db=await fixture();db.accounts[0].disabled=true;assert.throws(()=>identityAccount(db,'a1'));db.clients[0].active=false;assert.throws(()=>identityAccount(db,'c1'));assert.throws(()=>identityAccount(db,'unknown'))});

import {applyCommand,parseCommand} from '../server/commands';
test('online commands reject role injection, clock, credentials and unknown fields',()=>{for(const input of [{type:'clock',hours:1},{type:'acceptInvite',id:'c1'},{type:'activate',id:'c1',service:'personal',intensity:1,role:'admin'},{type:'settings',personal:NaN,physio:1,consultation:1,cancelHours:1},{type:'outcome',id:'x',status:'scheduled'},{type:'validity',packageId:'x',date:'2026-02-30'},{type:'__proto__'},{type:'updateProfile',name:'x',email:'x@y.pl',phone:'',photo:'',password:'secret'}])assert.throws(()=>parseCommand(input));assert.equal(parseCommand({type:'notes',id:'s',publicNote:"'); DROP TABLE clients;--",privateNote:''}).type,'notes')});
test('server binds sender to actual authenticated administrator',async()=>{const db=await fixture();const next=applyCommand(db,'a2',{type:'sendLetter',to:'c1',subject:'Hello',body:'Test'},db.now);assert.equal(next.letters?.[0].from,'a2');assert.equal(db.letters?.length,1)});
test('client cannot declare payment paid or update another client session',async()=>{const db=await fixture();assert.throws(()=>applyCommand(db,'c1',{type:'payHold',id:'x'},db.now),/administrator/);assert.throws(()=>applyCommand(db,'c1',{type:'comment',id:'sc2',text:'intrusion'},db.now),/dostępu/);assert.throws(()=>applyCommand(db,'c1',{type:'notes',id:'sc1',publicNote:'x',privateNote:'x'},db.now),/uprawnień/)});
test('mandatory password rotation prevents domain commands',async()=>{const db=await fixture();db.accounts.find(a=>a.id==='t1')!.mustChangePassword=true;assert.throws(()=>applyCommand(db,'t1',{type:'comment',id:'sc1',text:'x'},db.now),/hasło/)});

import {encode,decode,changes} from '../server/store';
test('server store excludes local credentials and computes entity-level changes',async()=>{const db=await fixture(),entities=encode(db);assert.ok(!JSON.stringify(entities).includes('secret-hash'));const restored=decode({entities,now:db.now,revision:0,role:'admin'});assert.equal(restored.clients.length,2);const next=structuredClone(restored);next.clients[0].name='New name';const delta=changes(restored,next);assert.equal(delta.changes.length,1);assert.equal(delta.changes[0].kind,'clients');assert.deepEqual(delta.removed,[])});

import {at,dateOf,dayAdd,dayIndex} from './domain';
test('business time is Warsaw regardless of deployment timezone including DST',()=>{assert.equal(at('2026-01-15',10).toISOString(),'2026-01-15T09:00:00.000Z');assert.equal(at('2026-07-15',10).toISOString(),'2026-07-15T08:00:00.000Z');assert.equal(dateOf(new Date('2026-07-15T22:30:00Z')),'2026-07-16');assert.equal(dayAdd('2026-03-28',1),'2026-03-29');assert.equal(dayIndex('2026-09-28'),0);assert.ok(Number.isNaN(+at('2026-03-29',2)))});
