import React,{useRef,useState} from 'react';
import {Palette,X,Check} from 'lucide-react';
import {Popover} from './controls';
const palette=['#CF513C','#317E77','#4169A3','#8060A4','#A16B2C','#A4486A','#34404B'];
function hsv(hex:string){const [r,g,b]=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255),v=Math.max(r,g,b),d=v-Math.min(r,g,b);let h=d===0?0:v===r?((g-b)/d)%6:v===g?(b-r)/d+2:(r-g)/d+4;return {h:(h*60+360)%360,s:v?d/v:0,v}}
function hexColor(h:number,s:number,v:number){const c=v*s,x=c*(1-Math.abs(h/60%2-1)),m=v-c;const rgb=h<60?[c,x,0]:h<120?[x,c,0]:h<180?[0,c,x]:h<240?[0,x,c]:h<300?[x,0,c]:[c,0,x];return '#'+rgb.map(n=>Math.round((n+m)*255).toString(16).padStart(2,'0')).join('').toUpperCase()}
export function ProductColorPicker({value,onChange}:{value:string;onChange:(color:string)=>void}){
 const anchor=useRef<HTMLDivElement>(null),[shown,setShown]=useState(false),[draft,setDraft]=useState(value),[color,setColor]=useState(()=>hsv(value));
 const valid=/^#[0-9a-f]{6}$/i.test(draft),preview=hexColor(color.h,color.s,color.v);
 const update=(next:typeof color)=>{setColor(next);setDraft(hexColor(next.h,next.s,next.v))};
 const point=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();update({...color,s:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),v:Math.max(0,Math.min(1,1-(e.clientY-r.top)/r.height))})};
 const close=()=>{setShown(false);anchor.current?.querySelector<HTMLButtonElement>('.custom-color-trigger')?.focus()};
 return <div className="product-colors"><span className="product-colors-label">Kolor produktu</span><div className="color-options">{palette.map(c=><button type="button" key={c} aria-label={'Kolor '+c} aria-pressed={value.toUpperCase()===c} style={{background:c}} onClick={()=>onChange(c)}/>)}<div ref={anchor} className="custom-color-anchor"><button type="button" className="custom-color-trigger" title="Własny kolor" aria-label="Własny kolor produktu" aria-expanded={shown} aria-pressed={!palette.includes(value.toUpperCase())} onClick={()=>{setDraft(value);setColor(hsv(value));setShown(!shown)}}><Palette size={16}/>{!palette.includes(value.toUpperCase())&&<i style={{background:value}}/>}</button>{shown&&<Popover anchor={anchor} onClose={close} label="Własny kolor produktu"><div className="product-color-popover"><header><strong>Własny kolor</strong><button type="button" className="icon-btn" aria-label="Zamknij wybór koloru" onClick={close}><X size={16}/></button></header><div className="color-plane" role="slider" tabIndex={0} aria-label="Nasycenie i jasność koloru" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(color.s*100)} aria-valuetext={`Nasycenie ${Math.round(color.s*100)}%, jasność ${Math.round(color.v*100)}%`} style={{backgroundColor:`hsl(${color.h} 100% 50%)`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);point(e)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))point(e)}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();update({...color,s:Math.max(0,Math.min(1,color.s+(e.key==='ArrowRight'?.01:e.key==='ArrowLeft'?-.01:0))),v:Math.max(0,Math.min(1,color.v+(e.key==='ArrowUp'?.01:e.key==='ArrowDown'?-.01:0)))})}}><span style={{left:color.s*100+'%',top:(1-color.v)*100+'%',background:preview}}/></div><input className="color-hue" type="range" aria-label="Odcień koloru" min={0} max={359} value={Math.round(color.h)} onChange={e=>update({...color,h:Number(e.target.value)})}/><label className="color-hex"><span className="color-preview" style={{background:valid?draft:preview}}/><span className="hex-prefix">#</span><input autoComplete="off" spellCheck={false} aria-label="Własny kolor produktu HEX" aria-invalid={!valid} maxLength={7} value={draft.slice(1)} onChange={e=>{const next='#'+e.target.value.replace(/^#/,'').toUpperCase();setDraft(next);if(/^#[0-9a-f]{6}$/i.test(next))setColor(hsv(next))}} onKeyDown={e=>{if(e.key==='Enter'&&valid){e.preventDefault();onChange(draft.toUpperCase());close()}}}/><small>HEX</small></label>{!valid&&<small className="color-error">Wpisz 6 znaków: 0-9 lub A-F.</small>}<button type="button" className="button primary full" disabled={!valid} onClick={()=>{onChange(draft.toUpperCase());close()}}><Check size={16}/>Zastosuj kolor</button></div></Popover>}</div></div></div>
}
