import {ConsultationPicker} from './consultation-picker';
import {dateOf} from './domain';
import {trainerHours} from './domain';
import React,{useState} from 'react';
import {useApp,Field,Steps,Empty} from './context';
import {available,dayAdd,hourLabel,labelDate,money} from './domain';
import {validBirthDate} from './auth';
export function RegistrationPage(){const {db,registerClient}=useApp();const trainers=db.trainers.filter(t=>!t.deleted&&t.days.some(d=>trainerHours(t,d).some(h=>trainerHours(t,d).includes(h+1))));const [step,setStep]=useState(1),[trainer,setTrainer]=useState(trainers[0]?.id||''),[date,setDate]=useState(dayAdd(dateOf(new Date(db.now)),1)),[hour,setHour]=useState(-1),[done,setDone]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',email:'',phone:'',birthDate:'',b:'',c:''});const set=(k:string,v:string)=>setForm({...form,[k]:v});const validate=(n:number)=>{if(n>=1&&(!form.name.trim()||!/^\S+@\S+\.\S+$/.test(form.email)||!form.phone.trim()||!validBirthDate(form.birthDate,db.now))){setError('Uzupełnij dane kontaktowe i poprawną datę urodzenia.');return false}if(n>=2&&(hour<0||!available(db,trainer,date,hour)||!available(db,trainer,date,hour+1))){setError('Wybierz dostępny termin konsultacji.');return false}return true};const change=(n:number)=>{setError('');if(n<step||validate(n-1))setStep(n)};if(!trainers.length)return <Empty title="Brak terminów konsultacji" body="Grafik nie został jeszcze udostępniony."/>;
 if(done)return <section className="card activation"><h1>Dziękujemy za rejestrację</h1><p>Do zobaczenia na konsultacji!</p><h2>{labelDate(date)} · {hourLabel(hour)}</h2><p>Trener: {trainers.find(t=>t.id===trainer)?.name}</p><p>Konto będzie można aktywować po konsultacji i zatwierdzeniu przez trenera.</p></section>;
 return <><div className="page-heading"><h1>Rejestracja i konsultacja</h1></div><section className="card pad"><Steps labels={['Dane klienta','Termin','Potwierdzenie']} step={step} onChange={change}/><form onSubmit={async e=>{e.preventDefault();setError('');if(step<3){change(step+1);return}if(!validate(2))return;setBusy(true);try{await registerClient({type:'register',name:form.name,email:form.email,phone:form.phone,birthDate:form.birthDate,trainerId:trainer,date,hour,answers:[form.b,form.c]});setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{step===1?<div className="form-grid">{[['name','Imię i nazwisko','text'],['email','E-mail','email'],['phone','Telefon','tel'],['birthDate','Data urodzenia','date'],['b','Pytanie B','text'],['c','Pytanie C','text']].map(([key,label,type])=><Field key={key} label={label}><input type={type} required={!['b','c'].includes(key)} max={key==='birthDate'?dateOf(new Date(db.now)):undefined} min={key==='birthDate'?'1900-01-01':undefined} value={form[key as keyof typeof form]} onInput={e=>set(key,e.currentTarget.value)}/></Field>)}</div>:step===2?<ConsultationPicker db={db} trainers={trainers} trainerId={trainer} date={date} hour={hour} onTrainer={id=>{setTrainer(id);setHour(-1);setError('')}} onSlot={(d,h)=>{setDate(d);setHour(h);setError('')}}/>:<dl><dt>Klient</dt><dd>{form.name}</dd><dt>E-mail</dt><dd>{form.email}</dd><dt>Data urodzenia</dt><dd>{labelDate(form.birthDate,{day:'numeric',month:'long',year:'numeric'})}</dd><dt>Trener</dt><dd>{trainers.find(t=>t.id===trainer)?.name}</dd><dt>Termin</dt><dd>{labelDate(date)} · {hourLabel(hour)}</dd><dt>Cena konsultacji</dt><dd>{money(db.settings.consultation)}</dd></dl>}{error&&<p className="alert" role="alert">{error}</p>}<div className="form-actions">{step>1&&<button type="button" className="button secondary" onClick={()=>change(step-1)}>Wstecz</button>}<button className="button primary" disabled={busy||(step===2&&hour<0)}>{busy?'Zapisywanie…':step===3?'Zarezerwuj konsultację':'Dalej'}</button></div></form></section></>}
