import {notifications} from './management';
import test from 'node:test';
import assert from 'node:assert/strict';
import {execute,planIntensity,planTerms} from './domain';
import {initialDatabase,actorFor,addTrainer,resetAccountPassword,authenticate,changeOwnPassword,passwordHash,type Database} from './auth';
import {quote} from './business';
import {projectState} from '../server/access';
const admin={role:'admin' as const,trainerId:'',clientId:''},trainer={role:'trainer' as const,trainerId:'t',clientId:''},client={role:'client' as const,trainerId:'',clientId:'c'};
async function fixture(){const db=await initialDatabase();db.now='2026-09-27T06:00:00Z';db.trainers=[{id:'t',name:'Trener',rate:100,consultationRate:175,products:['personal'],productRates:{personal:100,physio:200},days:[0,1,2,3,4,5,6],hours:[8,9,10,11,12,16,17,18]}];db.clients=[{id:'c',name:'Klient',email:'c@test.pl',birthDate:'1990-01-01',phone:'123',trainerId:'t',active:true,invited:true,prescribed:true,service:'personal',intensity:1,answers:[]}];db.accounts.push({id:'client',role:'client',email:'c@test.pl',clientId:'c',password:await passwordHash('Old-password-123')},{id:'trainer',role:'trainer',email:'t@test.pl',trainerId:'t',password:await passwordHash('Old-password-123')});return db}
const plan={service:'personal' as const,intensity:3,cycleWeeks:5,validWeeks:7,price:2500};
test('trainer proposal needs admin approval and does not expose pending commercial terms to client',async()=>{let db=await fixture();db=execute(db,trainer,{type:'individualPlan',clientId:'c',plan:{...plan,price:undefined}}) as Database;assert.equal(db.clients[0].planProposal?.status,'pending');assert.equal(planIntensity(db.clients[0]),1);assert.equal(projectState(db,'client').clients[0].planProposal,undefined);assert.throws(()=>execute(db,trainer,{type:'reviewPlan',clientId:'c',approve:true}),/administrator/);db=execute(db,admin,{type:'reviewPlan',clientId:'c',approve:true,price:2500}) as Database;assert.equal(planIntensity(db.clients[0]),3);assert.equal(planTerms(db,db.clients[0]).cycleWeeks,5);assert.equal(quote(db,'c','personal',3).base,2500)});
test('individual offers cannot change product, unauthorized users cannot propose, invalid terms fail',async()=>{const db=await fixture();for(const actor of [client,{...trainer,trainerId:'stranger'}])assert.throws(()=>execute(db,actor,{type:'individualPlan',clientId:'c',plan}));for(const p of [{...plan,service:'physio' as const},{...plan,validWeeks:2},{...plan,price:-1},{...plan,intensity:0}])assert.throws(()=>execute(db,admin,{type:'individualPlan',clientId:'c',plan:p}))});
test('accepted individual plan snapshots, promotions and future changes preserve purchases',async()=>{let db=await fixture();db=execute(db,admin,{type:'individualPlan',clientId:'c',plan:{...plan,intensity:1,cycleWeeks:2,validWeeks:3}}) as Database;db.promotions=[{id:'promo',kind:'email',value:'c@test.pl',percent:10,maxUses:0,used:0,expires:'',active:true}];db=execute(db,client,{type:'hold',clientId:'c',start:'2026-09-28',slots:[{day:0,hour:10}],dates:[{date:'2026-09-28',hour:10},{date:'2026-10-05',hour:10}]}) as Database;const h=db.holds[0];assert.equal(h.terms?.cycleWeeks,2);assert.equal(h.basePrice,2500);db=execute(db,admin,{type:'payHold',id:h.id}) as Database;db=execute(db,admin,{type:'individualPlan',clientId:'c',plan:{...plan,intensity:2,price:9999}}) as Database;assert.equal(db.packages[0].count,2);assert.equal(db.packages[0].price,2250);assert.equal(db.packages[0].validUntil,'2026-10-19');assert.equal(db.packages[0].intensity,1)});
test('override is staff-only, allows same-day/weekly excess but not collisions, expiry or excess entries',async()=>{let db=await fixture();db.packages=[{id:'p',clientId:'c',count:2,start:'2026-09-28',cycleEnd:'2026-10-26',validUntil:'2026-11-09',protectionUntil:'2026-10-27',slots:[],service:'personal',intensity:1,price:700}];db=execute(db,client,{type:'makeup',packageId:'p',date:'2026-09-28',hour:10}) as Database;assert.throws(()=>execute(db,client,{type:'makeup',packageId:'p',date:'2026-09-28',hour:11,ignoreLimits:true}));assert.throws(()=>execute(db,trainer,{type:'makeup',packageId:'p',date:'2026-09-28',hour:11}));assert.throws(()=>execute(db,trainer,{type:'makeup',packageId:'p',date:'2026-09-28',hour:10,ignoreLimits:true}));assert.throws(()=>execute(db,admin,{type:'makeup',packageId:'p',date:'2026-11-10',hour:11,ignoreLimits:true}));assert.throws(()=>execute(db,admin,{type:'makeup',packageId:'p',date:'2026-09-28',hour:14,ignoreLimits:true}));db=execute(db,trainer,{type:'makeup',packageId:'p',date:'2026-09-28',hour:11,ignoreLimits:true}) as Database;assert.equal(db.sessions.length,2);assert.throws(()=>execute(db,admin,{type:'makeup',packageId:'p',date:'2026-09-29',hour:11,ignoreLimits:true}))});
test('consultation payout uses 90-minute price, trainer hourly product rate is irrelevant',async()=>{let db=await fixture();db.sessions=[{id:'s',clientId:'c',trainerId:'t',date:'2026-09-26',hour:10,kind:'consultation',status:'scheduled',publicNote:'',privateNote:'',comments:[]}];db=execute(db,trainer,{type:'outcome',id:'s',status:'completed'}) as Database;assert.equal(db.sessions[0].earned,175);assert.equal(projectState(db,'trainer').trainers[0].consultationRate,175);assert.equal(projectState(db,'client').trainers[0].consultationRate,undefined)});
test('administrator resets both roles; old password fails and new login requires own password',async()=>{for(const id of ['trainer','client']){const source=await fixture();const result=await resetAccountPassword(source,admin,id);const account=result.db.accounts.find(a=>a.id===id)!;await assert.rejects(authenticate(result.db,account.email,'Old-password-123'));assert.equal((await authenticate(result.db,account.email,result.temporary)).mustChangePassword,true);const db=await changeOwnPassword(result.db,id,result.temporary,'New-password-123');assert.equal((await authenticate(db,account.email,'New-password-123')).mustChangePassword,false)}});

test('only administrator sets individual package price',async()=>{let db=await fixture();assert.throws(()=>execute(db,trainer,{type:'individualPlan',clientId:'c',plan}),/wyłącznie administrator/);db=execute(db,trainer,{type:'individualPlan',clientId:'c',plan:{...plan,price:undefined}}) as Database;assert.equal(db.clients[0].planProposal?.price,0);assert.throws(()=>execute(db,admin,{type:'reviewPlan',clientId:'c',approve:true}),/cenę/);db=execute(db,admin,{type:'reviewPlan',clientId:'c',approve:true,price:3100}) as Database;assert.equal(db.clients[0].individualPlan?.price,3100)});

test('notifications use role-specific language and preserve audience restrictions',async()=>{const db=await fixture();db.messages=[{id:'plan',clientId:'c',title:'Twój plan jest gotowy',body:'Klient · Masz zarezerwowane stałe godziny: poniedziałek 09:00.',at:db.now,read:false,target:'all'},{id:'staff',clientId:'c',title:'Uwaga dla trenera',body:'Tylko personel',at:db.now,read:false,target:'staff'},{id:'welcome',clientId:'c',title:'Witamy w ACO!',body:'Klient · Twoje konto jest aktywne.',at:db.now,read:false,target:'all'}];const coach=notifications(db,trainer),customer=notifications(db,client);assert.equal(coach.find(m=>m.id==='plan')?.title,'Plan treningowy klienta jest gotowy');assert.match(coach.find(m=>m.id==='plan')!.body,/Klient · Stałe godziny klienta/);assert.equal(customer.find(m=>m.id==='plan')?.title,'Twój plan jest gotowy');assert.equal(customer.some(m=>m.id==='staff'),false);assert.equal(notifications(db,{...trainer,trainerId:'other'}).length,0);assert.equal(notifications(db,admin).some(m=>m.id==='plan'),false);assert.equal(coach.find(m=>m.id==='welcome')?.title,'Klient aktywował konto')});
