import test from 'node:test';
import assert from 'node:assert/strict';
import {initialDatabase} from './auth';
import {execute,at,defaultLocation,locationsOf,type Session} from './domain';
import {workSummary} from './work-summary';
import {upcomingSessions,journalSessions,currentEvent,sessionsAt} from './schedule-model';
import {notifications} from './management';
import {applyCommand} from '../server/commands';
import {encodeRelational,decodeRelational} from '../server/relational-store';
const admin={role:'admin' as const,trainerId:'',clientId:''};
async function fixture(){const db=await initialDatabase();db.now=at('2026-09-25',12).toISOString();db.accounts=[{id:'admin',role:'admin',email:'a@example.test'},{id:'coach',role:'trainer',trainerId:'t1',email:'t@example.test'},{id:'client',role:'client',clientId:'c1',email:'c@example.test'}];db.trainers=[{id:'t1',name:'Trener',days:[4],hours:[10,11,12,13,14],rate:100}];db.clients=[{id:'c1',name:'Klient',email:'c@example.test',phone:'',trainerId:'t1',active:true,invited:true,service:'personal',intensity:1,prescribed:true,answers:[]}];db.sessions=[];db.messages=[];return db}
function session(id:string,extra:Partial<Session>={}):Session{return {id,clientId:'c1',trainerId:'t1',date:'2026-09-25',hour:10,kind:'training',status:'completed',publicNote:'',privateNote:'',comments:[],earned:100,...extra}}
test('earnings separate completed training, consultation, late cancellation and absence without changing total',async()=>{const db=await fixture();db.sessions=[session('done'),session('late',{status:'cancelled_late'}),session('absent',{status:'no_show'}),session('consult',{kind:'consultation',earned:150}),session('future',{hour:14,status:'scheduled',earned:undefined})];const summary=workSummary(db,'t1');assert.equal(summary.rows[0].earned,100);assert.equal(summary.rows[1].earned,150);assert.equal(summary.absenceEarned,200);assert.equal(summary.earned,450);assert.equal(summary.forecast,550)});
test('upcoming includes today after current time and excludes earlier, cancelled and other trainers',async()=>{const db=await fixture();db.sessions=[session('past',{status:'scheduled',hour:11}),session('today',{status:'scheduled',hour:13}),session('tomorrow',{status:'scheduled',date:'2026-09-26'}),session('cancelled',{status:'cancelled_late',hour:14}),session('other',{trainerId:'t2',status:'scheduled',hour:15})];assert.deepEqual(upcomingSessions(db,'t1').map(s=>s.id),['today','tomorrow'])});
test('former trainer journal retains only their own history, not new lead sessions or expired substitutions',async()=>{const db=await fixture();db.clients[0].trainerId='t2';db.sessions=[session('mine'),session('other',{trainerId:'t2'}),session('sub',{substituteId:'expired'}),session('future',{date:'2026-09-26',status:'scheduled'})];assert.deepEqual(journalSessions(db,{role:'trainer',trainerId:'t1',clientId:''}).map(s=>s.id),['mine'])});
test('timeline anchor selects latest past event independently of ordering and nearest future otherwise',()=>{const items=[{date:'2026-09-24'},{date:'2026-09-26'},{date:'2026-09-25'}];assert.equal(currentEvent(items,'2026-09-25')?.date,'2026-09-25');assert.equal(currentEvent(items,'2026-09-23')?.date,'2026-09-24')});
test('team calendar counts consultations in both occupied hours and excludes cancelled sessions',async()=>{const db=await fixture();db.sessions=[session('consult',{kind:'consultation'}),session('training',{hour:11}),session('cancelled',{hour:11,status:'cancelled_early'})];assert.deepEqual(sessionsAt(db,'2026-09-25',11).map(s=>s.id),['consult','training']);assert.equal(sessionsAt(db,'2026-09-25',12).length,0)});
test('client notification stream starts with welcome, staff retain consultation operations',async()=>{let db=await fixture();db.clients[0].active=false;db.messages=[{id:'old',clientId:'c1',title:'Konsultacja zarezerwowana',body:'Termin',target:'all',at:db.now,read:false}];const actor={role:'client' as const,trainerId:'',clientId:'c1'};assert.equal(notifications(db,actor).length,0);db=execute(db,actor,{type:'acceptInvite',id:'c1'}) as typeof db;assert.deepEqual(notifications(db,actor).map(n=>n.title),['Witamy w ACO!']);assert.deepEqual(notifications(db,{role:'trainer',trainerId:'t1',clientId:''}).map(n=>n.id),['old'])});
test('locations require admin and roundtrip through typed storage with session association',async()=>{let db=await fixture();const command={type:'saveLocation',id:defaultLocation.id,name:'Studio przy parku',address:'Parkowa 2'};assert.throws(()=>applyCommand(db,'coach',command,db.now),/administrator/);assert.throws(()=>applyCommand(db,'client',command,db.now),/administrator/);db=applyCommand(db,'admin',command,db.now);db.sessions=[session('session')];db=applyCommand(db,'admin',{type:'sessionLocation',id:'session',locationId:defaultLocation.id},db.now);const rows=encodeRelational(db);const decoded=decodeRelational({rows,now:db.now,revision:1,role:'admin'});assert.equal(locationsOf(decoded)[0].address,'Parkowa 2');assert.equal(decoded.sessions[0].locationId,defaultLocation.id)});
