import React,{useState,useRef,useEffect} from 'react';
import {createPortal} from 'react-dom';
import {useApp,days} from './context';
import {Session,dayAdd,dateOf,hourLabel,labelDate,trainerHours,weekOf,statusLabels} from './domain';
import {sessionsAt} from './schedule-model';
export function AllTrainersCalendar({week,setWeek,selected,setSelected}:{week:string;setWeek:(week:string)=>void;selected:string;setSelected:(id:string)=>void}){
 const {db,open}=useApp(),trainers=db.trainers.filter(t=>!t.deleted),dates=Array.from({length:7},(_,i)=>dayAdd(week,i));
 const axis=[...new Set(dates.flatMap((date,day)=>[...trainers.flatMap(t=>trainerHours(t,day)),...db.sessions.filter(s=>s.date===date&&!s.status.startsWith('cancelled')).flatMap(s=>s.kind==='consultation'?[s.hour,s.hour+1]:[s.hour])]))].sort((a,b)=>a-b);
 const gap=(h:number)=>axis.indexOf(h)>0&&h>axis[axis.indexOf(h)-1]+1;
 return <><div className="page-heading"><div><h1>Grafik trenerów</h1><p>Cały zespół</p></div></div><section className="card calendar-card"><div className="calendar-toolbar"><div className="week-nav"><button aria-label="Poprzedni tydzień" onClick={()=>setWeek(dayAdd(week,-7))}>←</button><strong>{labelDate(week)} - {labelDate(dayAdd(week,6))}</strong><button aria-label="Następny tydzień" onClick={()=>setWeek(dayAdd(week,7))}>→</button></div><button className="button secondary" onClick={()=>setWeek(weekOf(dateOf(new Date(db.now))))}>Dziś</button><select aria-label="Grafik trenera" value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">Wszyscy trenerzy</option>{trainers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div className="calendar-days-columns aligned-calendar team-calendar"><div className="calendar-time-axis"><header/><div className="axis-hours">{axis.map(h=><React.Fragment key={h}>{gap(h)&&<div className="shared-gap-axis">⋯</div>}<div>{hourLabel(h)}</div></React.Fragment>)}</div></div>{dates.map((date,day)=><div className="calendar-day-column" key={date}><header className={date===dateOf(new Date(db.now))?'today':''}><strong>{days[day].slice(0,3)}</strong><span>{labelDate(date,{day:'numeric',month:'numeric'})}</span></header>{!axis.length&&<small className="no-hours">Brak terminów</small>}{axis.map(h=>{const list=sessionsAt(db,date,h),hasHours=trainers.some(t=>trainerHours(t,day).includes(h));return <React.Fragment key={h}>{gap(h)&&<div className="shared-calendar-gap"/>}<div className="calendar-hour-slot team-hour">{list.length?<TeamCount list={list} date={date} hour={h}/>:hasHours?<div className="team-empty">0</div>:null}</div></React.Fragment>})}</div>)}</div></section></>
}

function TeamCount({list,date,hour}:{list:Session[];date:string;hour:number}){const {db,open}=useApp();const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const keep=()=>clearTimeout(timer.current);const hide=()=>{keep();timer.current=setTimeout(()=>setPosition(null),180)};useEffect(()=>()=>keep(),[]);const [position,setPosition]=useState<{top:number;left:number}|null>(null);const show=(el:HTMLButtonElement)=>{keep();const r=el.getBoundingClientRect(),height=Math.min(320,70+list.length*72);setPosition({left:Math.max(12,Math.min(r.left,window.innerWidth-312)),top:r.bottom+height+8<window.innerHeight?r.bottom+6:Math.max(12,r.top-height-6)})};return <><button className="calendar-event team-count" aria-describedby={position?`team-${date}-${hour}`:undefined} onMouseEnter={e=>show(e.currentTarget)} onMouseLeave={hide} onFocus={e=>show(e.currentTarget)} onBlur={hide}><strong>{list.length}</strong><span>{list.length===1?'sesja':list.length<5?'sesje':'sesji'}</span></button>{position&&createPortal(<div className="team-session-tooltip team-tooltip-floating" style={position} id={`team-${date}-${hour}`} role="tooltip" onMouseEnter={keep} onMouseLeave={hide} onFocus={keep} onBlur={hide}><strong>{labelDate(date)} · {hourLabel(hour)}</strong>{list.map(s=><button className="team-tooltip-session" key={s.id} onClick={()=>open({type:'session',id:s.id})}><span>{db.clients.find(c=>c.id===s.clientId)?.name}</span><small>{s.kind==='consultation'?'Konsultacja':'Trening'} · {hourLabel(s.hour)}<br/>{db.trainers.find(t=>t.id===s.trainerId)?.name} · {statusLabels[s.status]}</small></button>)}</div>,document.body)}</>}
