import {Select,Input} from './controls';
import React,{useEffect,useRef,useState} from 'react';
import {Field} from './context';
export const clockKey='aco-test-clock-v1';
export function systemNow(){const value=localStorage.getItem(clockKey);return value&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():new Date().toISOString()}
export function localClockValue(iso:string){const d=new Date(iso);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
export function TestClock({onChange}:{onChange:()=>void}){const [visible,setVisible]=useState(false),[value,setValue]=useState(''),[error,setError]=useState(''),[draft,setDraft]=useState(''),[discard,setDiscard]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const overridden=!!localStorage.getItem(clockKey);
 const close=()=>{if(draft!==value){setDiscard(true);return}setVisible(false)};
 const show=()=>{const v=localClockValue(systemNow());setValue(v);setDraft(v);setDiscard(false);setError('');setVisible(true)};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.code==='KeyT'){e.preventDefault();e.stopPropagation();show()}};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[]);
 useEffect(()=>{if(visible)dialog.current?.showModal()},[visible]);
 const apply=(next:string|null)=>{try{if(next){const date=new Date(next);if(!Number.isFinite(+date))throw Error('Wybierz poprawną datę i godzinę.');localStorage.setItem(clockKey,date.toISOString())}else localStorage.removeItem(clockKey);onChange();setVisible(false)}catch(e){setError((e as Error).message)}};
 return <>{overridden&&<button className="test-clock-indicator" onClick={show}>Czas testowy: {new Date(systemNow()).toLocaleString('pl-PL',{dateStyle:'short',timeStyle:'short'})}</button>}{visible&&<dialog ref={dialog} className="dialog" aria-label="Czas systemu" onCancel={e=>{e.preventDefault();close()}}><div className="dialog-inner"><h2>Czas systemu</h2><p className="spaced">Wybrany czas zostanie zatrzymany dla wszystkich kont w tej przeglądarce.</p><form onSubmit={e=>{e.preventDefault();apply(draft)}}><div className="form-grid"><Field label="Data"><Input type="date" required value={draft.slice(0,10)} onChange={e=>setDraft(e.target.value+draft.slice(10))}/></Field><Field label="Godzina"><Select value={draft.slice(11,13)} onChange={e=>setDraft(draft.slice(0,11)+e.target.value+draft.slice(13))}>{Array.from({length:24},(_,i)=>String(i).padStart(2,'0')).map(h=><option key={h}>{h}</option>)}</Select></Field><Field label="Minuta"><Select value={draft.slice(14,16)} onChange={e=>setDraft(draft.slice(0,14)+e.target.value)}>{Array.from({length:60},(_,i)=>String(i).padStart(2,'0')).map(m=><option key={m}>{m}</option>)}</Select></Field></div><p className="hint">Strefa czasowa: {Intl.DateTimeFormat().resolvedOptions().timeZone}</p>{error&&<p className="alert" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={close}>Anuluj</button><button type="submit" className="button primary">Ustaw czas</button></div><button type="button" className="text-button spaced" onClick={()=>apply(null)}>Przywróć czas rzeczywisty</button></form>{discard&&<section className="unsaved-confirm" role="alertdialog"><h3>Niezapisane zmiany</h3><p>Odrzucić zmianę czasu?</p><div className="form-actions"><button className="button secondary" onClick={()=>setDiscard(false)}>Wróć do edycji</button><button className="button primary" onClick={()=>setVisible(false)}>Odrzuć zmiany</button></div></section>}</div></dialog>}</>}
