import {PhotoPicker,AmountInput} from './admin-ui';
import React,{useState} from 'react';
import {useApp,Field,days,Steps} from './context';
import {TrainerInput} from './auth';
import {serviceName} from './domain';
export function TrainerWizard({id}:{id?:string}){const {db,createTrainer,open}=useApp();const t=db.trainers.find(t=>t.id===id),account=db.accounts.find(a=>a.trainerId===id&&a.role==='trainer');const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState('');const [data,setData]=useState<TrainerInput>({id,name:t?.name||'',email:account?.email||'',products:t?.products||(t?['personal','physio']:['personal']),productRates:t?.productRates||{personal:t?.rate||100,physio:t?.rate||100},days:t?.days||[],hours:t?.hours||[],password:'',phone:t?.phone||'',pesel:t?.pesel||'',student:t?.student||false,address:t?.address||'',taxOffice:t?.taxOffice||'',photo:t?.photo||''});const set=(key:string,value:any)=>setData({...data,[key]:value});const [from,setFrom]=useState(8),[to,setTo]=useState(20);
 const valid=(n:number)=>{if(n===1&&(!data.name.trim()||!/^\S+@\S+\.\S+$/.test(data.email))){setError('Podaj imię, nazwisko i poprawny e-mail.');return false}if(n===2&&(!data.products.length||data.products.some(p=>(!Number.isFinite(data.productRates[p])||data.productRates[p]<=0)))){setError('Wybierz produkty i stawki.');return false}return true};const change=(n:number)=>{setError('');if(n<step||valid(step))setStep(n)};
 return <><h2>{id?'Edytuj trenera':'Dodaj trenera'}</h2><Steps labels={['Dane','Produkty','Księgowość','Konto']} step={step} onChange={change}/><form onSubmit={async e=>{e.preventDefault();setError('');if(step<4){change(step+1);return}if(!valid(1)){setStep(1);return}if(!valid(2)){setStep(2);return}if(data.password!==confirm){setError('Hasła muszą być takie same.');return}setBusy(true);try{await createTrainer(data);open(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
 {step===1?<><Field label="Imię i nazwisko"><input required value={data.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="E-mail"><input required type="email" value={data.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Telefon"><input type="tel" value={data.phone} onChange={e=>set('phone',e.target.value)}/></Field><PhotoPicker value={data.photo||''} onChange={v=>set('photo',v)}/></>:step===2?<><h3>Produkty i stawki godzinowe</h3><div className="product-options">{(['personal','physio'] as const).map(p=><div className={'product-option '+(data.products.includes(p)?'selected':'')} key={p}><label className="product-choice"><input type="checkbox" checked={data.products.includes(p)} onChange={()=>set('products',data.products.includes(p)?data.products.filter(x=>x!==p):[...data.products,p])}/><strong>{serviceName(p)}</strong></label>{data.products.includes(p)&&<div className="product-rate"><span>Stawka za godzinę</span><AmountInput label={'Stawka — '+serviceName(p)} value={data.productRates[p]} onChange={n=>set('productRates',{...data.productRates,[p]:n})}/></div>}</div>)}</div></>:step===3?<><Field label="PESEL"><input inputMode="numeric" maxLength={11} pattern="[0-9]{11}" value={data.pesel} onChange={e=>set('pesel',e.target.value)}/></Field><label className="checkbox-field"><input type="checkbox" checked={data.student} onChange={e=>set('student',e.target.checked)}/>Status studenta</label><Field label="Adres zamieszkania"><textarea value={data.address} onChange={e=>set('address',e.target.value)}/></Field><Field label="Urząd skarbowy"><input value={data.taxOffice} onChange={e=>set('taxOffice',e.target.value)}/></Field></>:<><p>{data.name} · {data.email}</p>{!id&&<><Field label="Pierwsze hasło (tymczasowe)"><input type="password" autoComplete="new-password" required={!id} minLength={12} value={data.password} onChange={e=>set('password',e.target.value)}/></Field><Field label="Powtórz hasło"><input type="password" autoComplete="new-password" required={!id||!!data.password} minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)}/></Field><p className="hint">Minimum 12 znaków. Trener zmieni hasło przy pierwszym logowaniu.</p></>}{id&&<p>Hasło użytkownika jest prywatne. Aby przywrócić dostęp, użyj opcji „Wyzeruj hasło” na liście trenerów.</p>}</>}{error&&<p className="alert" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>step===1?open(null):change(step-1)}>{step===1?'Anuluj':'Wstecz'}</button><button className="button primary" disabled={busy}>{busy?'Zapisywanie…':step===4?'Zapisz trenera':'Dalej'}</button></div></form></>}
