import {ResponsiveTable} from './responsive-table';
import {duration} from './display-format';
import {dateOf} from './domain';
import React,{useState} from 'react';
import {PeriodNav,PeriodMode,periodStart,periodShift} from './period-nav';
import {useApp} from './context';
import {State,at,effectiveRate,consultationPay,money} from './domain';
export function workSummary(db:State,trainerId:string,month=dateOf(new Date(db.now)).slice(0,7),mode:PeriodMode='month'){const start=periodStart(month.length===7?month+'-01':month,mode),end=periodShift(start,mode,1);const sessions=db.sessions.filter(s=>s.trainerId===trainerId&&s.date>=start&&s.date<end);const rows=(['training','consultation'] as const).map(kind=>{const list=sessions.filter(s=>s.kind===kind);return {label:kind==='training'?'Treningi':'Konsultacje',completed:list.filter(s=>s.status==='completed').length,planned:list.filter(s=>s.status==='scheduled').length,earned:list.filter(s=>s.status==='completed').reduce((n,s)=>n+(s.earned||0),0),future:list.filter(s=>s.status==='scheduled'&&at(s.date,s.hour)>new Date(db.now)).reduce((n,s)=>n+(kind==='consultation'?consultationPay(db,s):effectiveRate(db,s)),0)}});const absences=sessions.filter(s=>s.status==='no_show'||s.status==='cancelled_late');const absenceEarned=absences.reduce((n,s)=>n+(s.earned||0),0);const extras=(db.extraHours||[]).filter(h=>h.trainerId===trainerId&&mode==='month'&&h.month===start.slice(0,7));const extra=extras.reduce((n,h)=>n+h.amount,0);const earned=rows.reduce((n,r)=>n+r.earned,extra+absenceEarned),forecast=earned+rows.reduce((n,r)=>n+r.future,0);return {rows,extras,extra,earned,forecast,absences,absenceEarned}}
export function TrainerWorkSummary(){const {db,actor}=useApp();const [month,setMonth]=useState(dateOf(new Date(db.now)));const summary=workSummary(db,actor.trainerId,month);return <><div className="summary-period-heading"><h2>Twoje rozliczenie</h2><PeriodNav label="Rozliczenie trenera" date={month} mode="month" onDate={setMonth}/></div><div className="stats-grid three"><section className="stat"><span>Naliczone w wybranym miesiącu</span><strong>{money(summary.earned)}</strong></section><section className="stat accent"><span>Prognoza całego miesiąca</span><strong>{money(summary.forecast)}</strong><small>Naliczone + zaplanowane przyszłe sesje</small></section><section className="stat"><span>Dodatkowy czas dla firmy</span><strong>{duration(summary.extras.reduce((n,h)=>n+h.hours,0))}</strong><small>{money(summary.extra)}</small></section></div><section className="card table-wrap spaced financial-table-bottom financial-table"><ResponsiveTable><table><thead><tr><th>Rodzaj pracy</th><th>Liczba / godziny</th><th>Zaplanowane</th><th>Naliczone</th><th>Prognoza</th></tr></thead><tbody>{summary.rows.map(r=><tr key={r.label}><td>{r.label}</td><td>{r.completed}</td><td>{r.planned}</td><td>{money(r.earned)}</td><td>{money(r.earned+r.future)}</td></tr>)}<tr className="absence-pay-row"><td>Nieobecności i późne odwołania</td><td>{summary.absences.length}</td><td>-</td><td>{money(summary.absenceEarned)}</td><td>{money(summary.absenceEarned)}</td></tr><tr><td>Czas dla firmy</td><td>{duration(summary.extras.reduce((n,h)=>n+h.hours,0))}</td><td>-</td><td>{money(summary.extra)}</td><td>{money(summary.extra)}</td></tr></tbody></table></ResponsiveTable></section>{summary.extras.length>0&&<details className="card pad spaced-bottom"><summary>Dodatkowe godziny - szczegóły</summary>{summary.extras.map(h=><div className="audit-row" key={h.id}><span>{h.description} · {duration(h.hours)}</span><strong>{money(h.amount)}</strong></div>)}</details>}</>}
export function AdminWorkSummary(){const {db}=useApp();const [date,setDate]=useState(dateOf(new Date(db.now))),[mode,setMode]=useState<PeriodMode>('month');return <section className="card table-wrap spaced financial-table"><div className="pad summary-period-heading"><h2>Rozliczenie zespołu</h2><PeriodNav label="Rozliczenie zespołu" date={date} mode={mode} onDate={setDate} onMode={setMode}/></div>{mode==='week'&&<p className="pad hint">Czas dla firmy jest rozliczany miesięcznie i nie wchodzi do sumy tygodnia.</p>}<ResponsiveTable><table><thead><tr><th>Trener</th><th>Treningi</th><th>Konsultacje</th><th>Nieobecności / późne odwołania</th><th>Czas dla firmy</th><th>Razem naliczone</th><th>Prognoza</th></tr></thead><tbody>{db.trainers.filter(t=>!t.deleted||db.sessions.some(s=>s.trainerId===t.id&&s.date>=periodStart(date,mode)&&s.date<periodShift(periodStart(date,mode),mode,1))||(db.extraHours||[]).some(h=>h.trainerId===t.id&&h.month===date.slice(0,7))).map(t=>{const x=workSummary(db,t.id,date,mode);return <tr key={t.id}><td>{t.name}</td><td>{x.rows[0].completed} · {money(x.rows[0].earned)}</td><td>{x.rows[1].completed} · {money(x.rows[1].earned)}</td><td>{x.absences.length} · {money(x.absenceEarned)}</td><td>{mode==='week'?'Rozliczane miesięcznie':<>{duration(x.extras.reduce((n,h)=>n+h.hours,0))} · {money(x.extra)}</>}</td><td>{money(x.earned)}</td><td>{money(x.forecast)}</td></tr>})}</tbody></table></ResponsiveTable></section>}
